[package]
name = "vmhost-cli"
description = "The vmhost command-line interface"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "vmhost"
path = "src/main.rs"

[dependencies]
clap.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
control-api.workspace = true
debian-media.workspace = true
vmm-core.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
machine-x86.workspace = true
linux-boot.workspace = true
virtio-core.workspace = true
virtio-block.workspace = true
virtio-net.workspace = true
libc.workspace = true

[lints]
workspace = true
