// @generated by tools/venus-protocol/rust_protocol.py (templates/rust_group.rs)
// from venus-protocol git-70991d4c. DO NOT EDIT: regenerate with
//     python scripts/venus-gen.py

//! The `buffer` group: its commands and the structures only they reach.

#![allow(unused_imports)]

use super::*;
use crate::venus::wire::{CommandHeader, Decoder, Encoder};

/// `VkBufferCreateInfo` (`VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkBufferCreateInfo {
    /// The pNext chain, in the guest's order. Admits: `VkBufferUsageFlags2CreateInfo`, `VkExternalMemoryBufferCreateInfo`, `VkBufferOpaqueCaptureAddressCreateInfo`, `VkBufferDeviceAddressCreateInfoEXT`.
    pub p_next: Vec<VkBufferCreateInfoNext>,
    /// `VkBufferCreateFlags flags`
    pub flags: VkBufferCreateFlags,
    /// `VkDeviceSize size`
    pub size: VkDeviceSize,
    /// `VkBufferUsageFlags usage`
    pub usage: VkBufferUsageFlags,
    /// `VkSharingMode sharingMode`
    pub sharing_mode: VkSharingMode,
    /// `uint32_t queueFamilyIndexCount`
    pub queue_family_index_count: u32,
    /// `const uint32_t* pQueueFamilyIndices`
    pub p_queue_family_indices: Option<Vec<u32>>,
}

impl VkBufferCreateInfo {
    // No output parameter reaches this structure, so it has no skeleton
    // form and the `partial` flag below is ignored.

    /// `VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO`.
    pub const STRUCTURE_TYPE: i32 = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO;

    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// `decode` or `decode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        expect_structure_type(dec, "VkBufferCreateInfo", Self::STRUCTURE_TYPE)?;
        let p_next = decode_chain::<VkBufferCreateInfoNext>(dec, partial)?;
        let mut value = Self::decode_body(dec, partial)?;
        value.p_next = p_next;
        Ok(value)
    }

    /// `encode` or `encode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        enc.structure_type(Self::STRUCTURE_TYPE)?;
        encode_chain(enc, &self.p_next, partial)?;
        self.encode_body(enc, partial)
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them
    /// (`vn_decode_VkBufferCreateInfo_self_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_body(dec: &mut Decoder<'_>, _partial: bool) -> Result<Self, ProtocolError> {
        let flags: VkBufferCreateFlags = dec.u32()?;
        let size: VkDeviceSize = dec.u64()?;
        let usage: VkBufferUsageFlags = dec.u32()?;
        let sharing_mode: VkSharingMode = dec.i32()?;
        let queue_family_index_count: u32 = dec.u32()?;
        let p_queue_family_indices: Option<Vec<u32>> = match array_presence(
            dec,
            u64::from(queue_family_index_count),
            NullArray::Unchecked,
        )? {
            Some(n) => Some(dec.u32_array(n)?),
            None => None,
        };
        Ok(Self {
            p_next: Vec::new(),
            flags,
            size,
            usage,
            sharing_mode,
            queue_family_index_count,
            p_queue_family_indices,
        })
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_body(&self, enc: &mut Encoder, _partial: bool) -> Result<(), ProtocolError> {
        enc.u32(self.flags)?;
        enc.u64(self.size)?;
        enc.u32(self.usage)?;
        enc.i32(self.sharing_mode)?;
        enc.u32(self.queue_family_index_count)?;
        if self.sharing_mode == VK_SHARING_MODE_CONCURRENT {
            let v = self.p_queue_family_indices.as_deref().unwrap_or_default();
            let count = u64::from(self.queue_family_index_count);
            check_len("VkBufferCreateInfo", "pQueueFamilyIndices", count, v.len())?;
            enc.array_size(count)?;
            for e in v {
                enc.u32(*e)?;
            }
        } else {
            enc.array_size(0)?;
        }
        Ok(())
    }

    /// Visit every pNext link this structure carries — its own chain's and
    /// its members' — as `(parent, sType)`.
    pub fn for_each_link(&self, f: &mut dyn FnMut(&'static str, i32)) {
        for link in &self.p_next {
            f("VkBufferCreateInfo", link.structure_type());
        }
    }
}

/// A link of `VkBufferCreateInfo`'s pNext chain.
#[derive(Debug, Clone, PartialEq)]
pub enum VkBufferCreateInfoNext {
    /// `VK_STRUCTURE_TYPE_BUFFER_USAGE_FLAGS_2_CREATE_INFO`.
    VkBufferUsageFlags2CreateInfo(VkBufferUsageFlags2CreateInfo),
    /// `VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_BUFFER_CREATE_INFO`.
    VkExternalMemoryBufferCreateInfo(VkExternalMemoryBufferCreateInfo),
    /// `VK_STRUCTURE_TYPE_BUFFER_OPAQUE_CAPTURE_ADDRESS_CREATE_INFO`.
    VkBufferOpaqueCaptureAddressCreateInfo(VkBufferOpaqueCaptureAddressCreateInfo),
    /// `VK_STRUCTURE_TYPE_BUFFER_DEVICE_ADDRESS_CREATE_INFO_EXT`.
    VkBufferDeviceAddressCreateInfoEXT(VkBufferDeviceAddressCreateInfoEXT),
}

impl<'a> ChainLink<'a> for VkBufferCreateInfoNext {
    const PARENT: &'static str = "VkBufferCreateInfo";

    fn structure_type(&self) -> i32 {
        match self {
            Self::VkBufferUsageFlags2CreateInfo(_) => {
                VK_STRUCTURE_TYPE_BUFFER_USAGE_FLAGS_2_CREATE_INFO
            }
            Self::VkExternalMemoryBufferCreateInfo(_) => {
                VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_BUFFER_CREATE_INFO
            }
            Self::VkBufferOpaqueCaptureAddressCreateInfo(_) => {
                VK_STRUCTURE_TYPE_BUFFER_OPAQUE_CAPTURE_ADDRESS_CREATE_INFO
            }
            Self::VkBufferDeviceAddressCreateInfoEXT(_) => {
                VK_STRUCTURE_TYPE_BUFFER_DEVICE_ADDRESS_CREATE_INFO_EXT
            }
        }
    }

    fn decode_body(
        stype: i32,
        dec: &mut Decoder<'a>,
        partial: bool,
    ) -> Option<Result<Self, ProtocolError>> {
        Some(match stype {
            VK_STRUCTURE_TYPE_BUFFER_USAGE_FLAGS_2_CREATE_INFO => {
                VkBufferUsageFlags2CreateInfo::decode_body(dec, partial)
                    .map(Self::VkBufferUsageFlags2CreateInfo)
            }
            VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_BUFFER_CREATE_INFO => {
                VkExternalMemoryBufferCreateInfo::decode_body(dec, partial)
                    .map(Self::VkExternalMemoryBufferCreateInfo)
            }
            VK_STRUCTURE_TYPE_BUFFER_OPAQUE_CAPTURE_ADDRESS_CREATE_INFO => {
                VkBufferOpaqueCaptureAddressCreateInfo::decode_body(dec, partial)
                    .map(Self::VkBufferOpaqueCaptureAddressCreateInfo)
            }
            VK_STRUCTURE_TYPE_BUFFER_DEVICE_ADDRESS_CREATE_INFO_EXT => {
                VkBufferDeviceAddressCreateInfoEXT::decode_body(dec, partial)
                    .map(Self::VkBufferDeviceAddressCreateInfoEXT)
            }
            _ => return None,
        })
    }

    fn encode_body(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        match self {
            Self::VkBufferUsageFlags2CreateInfo(link) => link.encode_body(enc, partial),
            Self::VkExternalMemoryBufferCreateInfo(link) => link.encode_body(enc, partial),
            Self::VkBufferOpaqueCaptureAddressCreateInfo(link) => link.encode_body(enc, partial),
            Self::VkBufferDeviceAddressCreateInfoEXT(link) => link.encode_body(enc, partial),
        }
    }
}

/// `VkExternalMemoryBufferCreateInfo` (`VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_BUFFER_CREATE_INFO`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkExternalMemoryBufferCreateInfo {
    /// `VkExternalMemoryHandleTypeFlags handleTypes`
    pub handle_types: VkExternalMemoryHandleTypeFlags,
}

impl VkExternalMemoryBufferCreateInfo {
    // No output parameter reaches this structure, so it has no skeleton
    // form and the `partial` flag below is ignored.

    /// `VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_BUFFER_CREATE_INFO`.
    pub const STRUCTURE_TYPE: i32 = VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_BUFFER_CREATE_INFO;

    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// `decode` or `decode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        expect_structure_type(
            dec,
            "VkExternalMemoryBufferCreateInfo",
            Self::STRUCTURE_TYPE,
        )?;
        dec.empty_pnext_chain("VkExternalMemoryBufferCreateInfo")?;
        Self::decode_body(dec, partial)
    }

    /// `encode` or `encode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        enc.structure_type(Self::STRUCTURE_TYPE)?;
        enc.simple_pointer(false)?;
        self.encode_body(enc, partial)
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them
    /// (`vn_decode_VkExternalMemoryBufferCreateInfo_self_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_body(dec: &mut Decoder<'_>, _partial: bool) -> Result<Self, ProtocolError> {
        let handle_types: VkExternalMemoryHandleTypeFlags = dec.u32()?;
        Ok(Self { handle_types })
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_body(&self, enc: &mut Encoder, _partial: bool) -> Result<(), ProtocolError> {
        enc.u32(self.handle_types)?;
        Ok(())
    }
}

/// `VkBufferOpaqueCaptureAddressCreateInfo` (`VK_STRUCTURE_TYPE_BUFFER_OPAQUE_CAPTURE_ADDRESS_CREATE_INFO`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkBufferOpaqueCaptureAddressCreateInfo {
    /// `uint64_t opaqueCaptureAddress`
    pub opaque_capture_address: u64,
}

impl VkBufferOpaqueCaptureAddressCreateInfo {
    // No output parameter reaches this structure, so it has no skeleton
    // form and the `partial` flag below is ignored.

    /// `VK_STRUCTURE_TYPE_BUFFER_OPAQUE_CAPTURE_ADDRESS_CREATE_INFO`.
    pub const STRUCTURE_TYPE: i32 = VK_STRUCTURE_TYPE_BUFFER_OPAQUE_CAPTURE_ADDRESS_CREATE_INFO;

    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// `decode` or `decode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        expect_structure_type(
            dec,
            "VkBufferOpaqueCaptureAddressCreateInfo",
            Self::STRUCTURE_TYPE,
        )?;
        dec.empty_pnext_chain("VkBufferOpaqueCaptureAddressCreateInfo")?;
        Self::decode_body(dec, partial)
    }

    /// `encode` or `encode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        enc.structure_type(Self::STRUCTURE_TYPE)?;
        enc.simple_pointer(false)?;
        self.encode_body(enc, partial)
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them
    /// (`vn_decode_VkBufferOpaqueCaptureAddressCreateInfo_self_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_body(dec: &mut Decoder<'_>, _partial: bool) -> Result<Self, ProtocolError> {
        let opaque_capture_address: u64 = dec.u64()?;
        Ok(Self {
            opaque_capture_address,
        })
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_body(&self, enc: &mut Encoder, _partial: bool) -> Result<(), ProtocolError> {
        enc.u64(self.opaque_capture_address)?;
        Ok(())
    }
}

/// `VkBufferDeviceAddressCreateInfoEXT` (`VK_STRUCTURE_TYPE_BUFFER_DEVICE_ADDRESS_CREATE_INFO_EXT`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkBufferDeviceAddressCreateInfoEXT {
    /// `VkDeviceAddress deviceAddress`
    pub device_address: VkDeviceAddress,
}

impl VkBufferDeviceAddressCreateInfoEXT {
    // No output parameter reaches this structure, so it has no skeleton
    // form and the `partial` flag below is ignored.

    /// `VK_STRUCTURE_TYPE_BUFFER_DEVICE_ADDRESS_CREATE_INFO_EXT`.
    pub const STRUCTURE_TYPE: i32 = VK_STRUCTURE_TYPE_BUFFER_DEVICE_ADDRESS_CREATE_INFO_EXT;

    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// `decode` or `decode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        expect_structure_type(
            dec,
            "VkBufferDeviceAddressCreateInfoEXT",
            Self::STRUCTURE_TYPE,
        )?;
        dec.empty_pnext_chain("VkBufferDeviceAddressCreateInfoEXT")?;
        Self::decode_body(dec, partial)
    }

    /// `encode` or `encode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        enc.structure_type(Self::STRUCTURE_TYPE)?;
        enc.simple_pointer(false)?;
        self.encode_body(enc, partial)
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them
    /// (`vn_decode_VkBufferDeviceAddressCreateInfoEXT_self_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_body(dec: &mut Decoder<'_>, _partial: bool) -> Result<Self, ProtocolError> {
        let device_address: VkDeviceAddress = dec.u64()?;
        Ok(Self { device_address })
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_body(&self, enc: &mut Encoder, _partial: bool) -> Result<(), ProtocolError> {
        enc.u64(self.device_address)?;
        Ok(())
    }
}

/// `VkBindBufferMemoryInfo` (`VK_STRUCTURE_TYPE_BIND_BUFFER_MEMORY_INFO`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkBindBufferMemoryInfo {
    /// The pNext chain, in the guest's order. Admits: `VkBindBufferMemoryDeviceGroupInfo`, `VkBindMemoryStatus`.
    pub p_next: Vec<VkBindBufferMemoryInfoNext>,
    /// `VkBuffer buffer`
    pub buffer: VkBuffer,
    /// `VkDeviceMemory memory`
    pub memory: VkDeviceMemory,
    /// `VkDeviceSize memoryOffset`
    pub memory_offset: VkDeviceSize,
}

impl VkBindBufferMemoryInfo {
    // No output parameter reaches this structure, so it has no skeleton
    // form and the `partial` flag below is ignored.

    /// `VK_STRUCTURE_TYPE_BIND_BUFFER_MEMORY_INFO`.
    pub const STRUCTURE_TYPE: i32 = VK_STRUCTURE_TYPE_BIND_BUFFER_MEMORY_INFO;

    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// `decode` or `decode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        expect_structure_type(dec, "VkBindBufferMemoryInfo", Self::STRUCTURE_TYPE)?;
        let p_next = decode_chain::<VkBindBufferMemoryInfoNext>(dec, partial)?;
        let mut value = Self::decode_body(dec, partial)?;
        value.p_next = p_next;
        Ok(value)
    }

    /// `encode` or `encode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        enc.structure_type(Self::STRUCTURE_TYPE)?;
        encode_chain(enc, &self.p_next, partial)?;
        self.encode_body(enc, partial)
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them
    /// (`vn_decode_VkBindBufferMemoryInfo_self_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_body(dec: &mut Decoder<'_>, _partial: bool) -> Result<Self, ProtocolError> {
        let buffer: VkBuffer = VkBuffer(dec.handle()?);
        let memory: VkDeviceMemory = VkDeviceMemory(dec.handle()?);
        let memory_offset: VkDeviceSize = dec.u64()?;
        Ok(Self {
            p_next: Vec::new(),
            buffer,
            memory,
            memory_offset,
        })
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_body(&self, enc: &mut Encoder, _partial: bool) -> Result<(), ProtocolError> {
        enc.handle(self.buffer.0)?;
        enc.handle(self.memory.0)?;
        enc.u64(self.memory_offset)?;
        Ok(())
    }

    /// Visit every pNext link this structure carries — its own chain's and
    /// its members' — as `(parent, sType)`.
    pub fn for_each_link(&self, f: &mut dyn FnMut(&'static str, i32)) {
        for link in &self.p_next {
            f("VkBindBufferMemoryInfo", link.structure_type());
        }
    }
}

/// A link of `VkBindBufferMemoryInfo`'s pNext chain.
#[derive(Debug, Clone, PartialEq)]
pub enum VkBindBufferMemoryInfoNext {
    /// `VK_STRUCTURE_TYPE_BIND_BUFFER_MEMORY_DEVICE_GROUP_INFO`.
    VkBindBufferMemoryDeviceGroupInfo(VkBindBufferMemoryDeviceGroupInfo),
    /// `VK_STRUCTURE_TYPE_BIND_MEMORY_STATUS`.
    VkBindMemoryStatus(VkBindMemoryStatus),
}

impl<'a> ChainLink<'a> for VkBindBufferMemoryInfoNext {
    const PARENT: &'static str = "VkBindBufferMemoryInfo";

    fn structure_type(&self) -> i32 {
        match self {
            Self::VkBindBufferMemoryDeviceGroupInfo(_) => {
                VK_STRUCTURE_TYPE_BIND_BUFFER_MEMORY_DEVICE_GROUP_INFO
            }
            Self::VkBindMemoryStatus(_) => VK_STRUCTURE_TYPE_BIND_MEMORY_STATUS,
        }
    }

    fn decode_body(
        stype: i32,
        dec: &mut Decoder<'a>,
        partial: bool,
    ) -> Option<Result<Self, ProtocolError>> {
        Some(match stype {
            VK_STRUCTURE_TYPE_BIND_BUFFER_MEMORY_DEVICE_GROUP_INFO => {
                VkBindBufferMemoryDeviceGroupInfo::decode_body(dec, partial)
                    .map(Self::VkBindBufferMemoryDeviceGroupInfo)
            }
            VK_STRUCTURE_TYPE_BIND_MEMORY_STATUS => {
                VkBindMemoryStatus::decode_body(dec, partial).map(Self::VkBindMemoryStatus)
            }
            _ => return None,
        })
    }

    fn encode_body(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        match self {
            Self::VkBindBufferMemoryDeviceGroupInfo(link) => link.encode_body(enc, partial),
            Self::VkBindMemoryStatus(link) => link.encode_body(enc, partial),
        }
    }
}

/// `VkBindBufferMemoryDeviceGroupInfo` (`VK_STRUCTURE_TYPE_BIND_BUFFER_MEMORY_DEVICE_GROUP_INFO`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkBindBufferMemoryDeviceGroupInfo {
    /// `uint32_t deviceIndexCount`
    pub device_index_count: u32,
    /// `const uint32_t* pDeviceIndices`
    pub p_device_indices: Option<Vec<u32>>,
}

impl VkBindBufferMemoryDeviceGroupInfo {
    // No output parameter reaches this structure, so it has no skeleton
    // form and the `partial` flag below is ignored.

    /// `VK_STRUCTURE_TYPE_BIND_BUFFER_MEMORY_DEVICE_GROUP_INFO`.
    pub const STRUCTURE_TYPE: i32 = VK_STRUCTURE_TYPE_BIND_BUFFER_MEMORY_DEVICE_GROUP_INFO;

    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// `decode` or `decode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        expect_structure_type(
            dec,
            "VkBindBufferMemoryDeviceGroupInfo",
            Self::STRUCTURE_TYPE,
        )?;
        dec.empty_pnext_chain("VkBindBufferMemoryDeviceGroupInfo")?;
        Self::decode_body(dec, partial)
    }

    /// `encode` or `encode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        enc.structure_type(Self::STRUCTURE_TYPE)?;
        enc.simple_pointer(false)?;
        self.encode_body(enc, partial)
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them
    /// (`vn_decode_VkBindBufferMemoryDeviceGroupInfo_self_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_body(dec: &mut Decoder<'_>, _partial: bool) -> Result<Self, ProtocolError> {
        let device_index_count: u32 = dec.u32()?;
        let p_device_indices: Option<Vec<u32>> =
            match array_presence(dec, u64::from(device_index_count), NullArray::Checked)? {
                Some(n) => Some(dec.u32_array(n)?),
                None => None,
            };
        Ok(Self {
            device_index_count,
            p_device_indices,
        })
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_body(&self, enc: &mut Encoder, _partial: bool) -> Result<(), ProtocolError> {
        enc.u32(self.device_index_count)?;
        if let Some(v) = &self.p_device_indices {
            let count = u64::from(self.device_index_count);
            check_len(
                "VkBindBufferMemoryDeviceGroupInfo",
                "pDeviceIndices",
                count,
                v.len(),
            )?;
            enc.array_size(count)?;
            for e in v {
                enc.u32(*e)?;
            }
        } else {
            enc.array_size(0)?;
        }
        Ok(())
    }
}

/// `VkBufferMemoryRequirementsInfo2` (`VK_STRUCTURE_TYPE_BUFFER_MEMORY_REQUIREMENTS_INFO_2`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkBufferMemoryRequirementsInfo2 {
    /// `VkBuffer buffer`
    pub buffer: VkBuffer,
}

impl VkBufferMemoryRequirementsInfo2 {
    // No output parameter reaches this structure, so it has no skeleton
    // form and the `partial` flag below is ignored.

    /// `VK_STRUCTURE_TYPE_BUFFER_MEMORY_REQUIREMENTS_INFO_2`.
    pub const STRUCTURE_TYPE: i32 = VK_STRUCTURE_TYPE_BUFFER_MEMORY_REQUIREMENTS_INFO_2;

    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// `decode` or `decode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        expect_structure_type(dec, "VkBufferMemoryRequirementsInfo2", Self::STRUCTURE_TYPE)?;
        dec.empty_pnext_chain("VkBufferMemoryRequirementsInfo2")?;
        Self::decode_body(dec, partial)
    }

    /// `encode` or `encode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        enc.structure_type(Self::STRUCTURE_TYPE)?;
        enc.simple_pointer(false)?;
        self.encode_body(enc, partial)
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them
    /// (`vn_decode_VkBufferMemoryRequirementsInfo2_self_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_body(dec: &mut Decoder<'_>, _partial: bool) -> Result<Self, ProtocolError> {
        let buffer: VkBuffer = VkBuffer(dec.handle()?);
        Ok(Self { buffer })
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_body(&self, enc: &mut Encoder, _partial: bool) -> Result<(), ProtocolError> {
        enc.handle(self.buffer.0)?;
        Ok(())
    }
}

/// `VkDeviceBufferMemoryRequirements` (`VK_STRUCTURE_TYPE_DEVICE_BUFFER_MEMORY_REQUIREMENTS`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkDeviceBufferMemoryRequirements {
    /// `const VkBufferCreateInfo* pCreateInfo`
    pub p_create_info: Option<VkBufferCreateInfo>,
}

impl VkDeviceBufferMemoryRequirements {
    // No output parameter reaches this structure, so it has no skeleton
    // form and the `partial` flag below is ignored.

    /// `VK_STRUCTURE_TYPE_DEVICE_BUFFER_MEMORY_REQUIREMENTS`.
    pub const STRUCTURE_TYPE: i32 = VK_STRUCTURE_TYPE_DEVICE_BUFFER_MEMORY_REQUIREMENTS;

    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// `decode` or `decode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        expect_structure_type(
            dec,
            "VkDeviceBufferMemoryRequirements",
            Self::STRUCTURE_TYPE,
        )?;
        dec.empty_pnext_chain("VkDeviceBufferMemoryRequirements")?;
        Self::decode_body(dec, partial)
    }

    /// `encode` or `encode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        enc.structure_type(Self::STRUCTURE_TYPE)?;
        enc.simple_pointer(false)?;
        self.encode_body(enc, partial)
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them
    /// (`vn_decode_VkDeviceBufferMemoryRequirements_self_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_body(dec: &mut Decoder<'_>, _partial: bool) -> Result<Self, ProtocolError> {
        let p_create_info: Option<VkBufferCreateInfo> = if dec.simple_pointer()? {
            Some(VkBufferCreateInfo::decode_with(dec, false)?)
        } else {
            return Err(null_pointer(
                dec,
                "VkDeviceBufferMemoryRequirements",
                "pCreateInfo",
            ));
        };
        Ok(Self { p_create_info })
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_body(&self, enc: &mut Encoder, _partial: bool) -> Result<(), ProtocolError> {
        enc.simple_pointer(self.p_create_info.is_some())?;
        if let Some(v) = &self.p_create_info {
            v.encode_with(enc, false)?;
        }
        Ok(())
    }

    /// Visit every pNext link this structure carries — its own chain's and
    /// its members' — as `(parent, sType)`.
    pub fn for_each_link(&self, f: &mut dyn FnMut(&'static str, i32)) {
        if let Some(v) = &self.p_create_info {
            v.for_each_link(f);
        }
    }
}

/// `VkBufferDeviceAddressInfo` (`VK_STRUCTURE_TYPE_BUFFER_DEVICE_ADDRESS_INFO`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkBufferDeviceAddressInfo {
    /// `VkBuffer buffer`
    pub buffer: VkBuffer,
}

impl VkBufferDeviceAddressInfo {
    // No output parameter reaches this structure, so it has no skeleton
    // form and the `partial` flag below is ignored.

    /// `VK_STRUCTURE_TYPE_BUFFER_DEVICE_ADDRESS_INFO`.
    pub const STRUCTURE_TYPE: i32 = VK_STRUCTURE_TYPE_BUFFER_DEVICE_ADDRESS_INFO;

    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// `decode` or `decode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        expect_structure_type(dec, "VkBufferDeviceAddressInfo", Self::STRUCTURE_TYPE)?;
        dec.empty_pnext_chain("VkBufferDeviceAddressInfo")?;
        Self::decode_body(dec, partial)
    }

    /// `encode` or `encode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        enc.structure_type(Self::STRUCTURE_TYPE)?;
        enc.simple_pointer(false)?;
        self.encode_body(enc, partial)
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them
    /// (`vn_decode_VkBufferDeviceAddressInfo_self_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_body(dec: &mut Decoder<'_>, _partial: bool) -> Result<Self, ProtocolError> {
        let buffer: VkBuffer = VkBuffer(dec.handle()?);
        Ok(Self { buffer })
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_body(&self, enc: &mut Encoder, _partial: bool) -> Result<(), ProtocolError> {
        enc.handle(self.buffer.0)?;
        Ok(())
    }
}

/// The arguments of `vkGetBufferMemoryRequirements`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct GetBufferMemoryRequirementsArgs {
    /// `VkDevice device` — in.
    pub device: VkDevice,
    /// `VkBuffer buffer` — in.
    pub buffer: VkBuffer,
    /// `VkMemoryRequirements* pMemoryRequirements` — out.
    pub p_memory_requirements: Option<VkMemoryRequirements>,
}

impl GetBufferMemoryRequirementsArgs {
    /// `VK_COMMAND_TYPE_vkGetBufferMemoryRequirements_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_GET_BUFFER_MEMORY_REQUIREMENTS_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkGetBufferMemoryRequirements";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkGetBufferMemoryRequirements_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        let device: VkDevice = VkDevice(dec.handle()?);
        if device.0 == 0 {
            return Err(null_dispatch_handle(dec, "vkGetBufferMemoryRequirements"));
        }
        let buffer: VkBuffer = VkBuffer(dec.handle()?);
        let p_memory_requirements: Option<VkMemoryRequirements> = if dec.simple_pointer()? {
            Some(VkMemoryRequirements::decode_with(dec, true)?)
        } else {
            return Err(null_pointer(
                dec,
                "vkGetBufferMemoryRequirements",
                "pMemoryRequirements",
            ));
        };
        Ok(Self {
            device,
            buffer,
            p_memory_requirements,
        })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkGetBufferMemoryRequirements`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.handle(self.device.0)?;
        enc.handle(self.buffer.0)?;
        enc.simple_pointer(self.p_memory_requirements.is_some())?;
        if let Some(v) = &self.p_memory_requirements {
            v.encode_with(enc, true)?;
        }
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkGetBufferMemoryRequirements_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        enc.simple_pointer(self.p_memory_requirements.is_some())?;
        if let Some(v) = &self.p_memory_requirements {
            v.encode_with(enc, false)?;
        }
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkGetBufferMemoryRequirements_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'_>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        self.p_memory_requirements = if dec.simple_pointer()? {
            Some(VkMemoryRequirements::decode_with(dec, false)?)
        } else {
            None
        };
        Ok(())
    }
}

/// The arguments of `vkBindBufferMemory`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place and sets `ret`, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct BindBufferMemoryArgs {
    /// `VkDevice device` — in.
    pub device: VkDevice,
    /// `VkBuffer buffer` — in.
    pub buffer: VkBuffer,
    /// `VkDeviceMemory memory` — in.
    pub memory: VkDeviceMemory,
    /// `VkDeviceSize memoryOffset` — in.
    pub memory_offset: VkDeviceSize,
    /// The return value (`VkResult`), written first in the reply.
    pub ret: VkResult,
}

impl BindBufferMemoryArgs {
    /// `VK_COMMAND_TYPE_vkBindBufferMemory_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_BIND_BUFFER_MEMORY_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkBindBufferMemory";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkBindBufferMemory_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        let device: VkDevice = VkDevice(dec.handle()?);
        if device.0 == 0 {
            return Err(null_dispatch_handle(dec, "vkBindBufferMemory"));
        }
        let buffer: VkBuffer = VkBuffer(dec.handle()?);
        let memory: VkDeviceMemory = VkDeviceMemory(dec.handle()?);
        let memory_offset: VkDeviceSize = dec.u64()?;
        Ok(Self {
            device,
            buffer,
            memory,
            memory_offset,
            ret: Default::default(),
        })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkBindBufferMemory`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.handle(self.device.0)?;
        enc.handle(self.buffer.0)?;
        enc.handle(self.memory.0)?;
        enc.u64(self.memory_offset)?;
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkBindBufferMemory_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        enc.i32(self.ret)?;
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkBindBufferMemory_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'_>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        self.ret = dec.i32()?;
        Ok(())
    }
}

/// The arguments of `vkCreateBuffer`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place and sets `ret`, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct CreateBufferArgs {
    /// `VkDevice device` — in.
    pub device: VkDevice,
    /// `const VkBufferCreateInfo* pCreateInfo` — in.
    pub p_create_info: Option<VkBufferCreateInfo>,
    /// `VkBuffer* pBuffer` — out.
    pub p_buffer: Option<VkBuffer>,
    /// The return value (`VkResult`), written first in the reply.
    pub ret: VkResult,
}

impl CreateBufferArgs {
    /// `VK_COMMAND_TYPE_vkCreateBuffer_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_CREATE_BUFFER_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkCreateBuffer";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkCreateBuffer_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        let device: VkDevice = VkDevice(dec.handle()?);
        if device.0 == 0 {
            return Err(null_dispatch_handle(dec, "vkCreateBuffer"));
        }
        let p_create_info: Option<VkBufferCreateInfo> = if dec.simple_pointer()? {
            Some(VkBufferCreateInfo::decode_with(dec, false)?)
        } else {
            return Err(null_pointer(dec, "vkCreateBuffer", "pCreateInfo"));
        };
        dec.null_allocator()?;
        let p_buffer: Option<VkBuffer> = if dec.simple_pointer()? {
            Some(VkBuffer(dec.handle()?))
        } else {
            return Err(null_pointer(dec, "vkCreateBuffer", "pBuffer"));
        };
        Ok(Self {
            device,
            p_create_info,
            p_buffer,
            ret: Default::default(),
        })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkCreateBuffer`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.handle(self.device.0)?;
        enc.simple_pointer(self.p_create_info.is_some())?;
        if let Some(v) = &self.p_create_info {
            v.encode_with(enc, false)?;
        }
        enc.null_allocator()?;
        enc.simple_pointer(self.p_buffer.is_some())?;
        if let Some(v) = &self.p_buffer {
            enc.handle(v.0)?;
        }
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkCreateBuffer_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        enc.i32(self.ret)?;
        enc.simple_pointer(self.p_buffer.is_some())?;
        if let Some(v) = &self.p_buffer {
            enc.handle(v.0)?;
        }
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkCreateBuffer_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'_>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        self.ret = dec.i32()?;
        self.p_buffer = if dec.simple_pointer()? {
            Some(VkBuffer(dec.handle()?))
        } else {
            None
        };
        Ok(())
    }

    /// Visit every pNext link the arguments carry, as `(parent, sType)`.
    pub fn for_each_link(&self, f: &mut dyn FnMut(&'static str, i32)) {
        if let Some(v) = &self.p_create_info {
            v.for_each_link(f);
        }
    }
}

/// The arguments of `vkDestroyBuffer`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct DestroyBufferArgs {
    /// `VkDevice device` — in.
    pub device: VkDevice,
    /// `VkBuffer buffer` — in.
    pub buffer: VkBuffer,
}

impl DestroyBufferArgs {
    /// `VK_COMMAND_TYPE_vkDestroyBuffer_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_DESTROY_BUFFER_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkDestroyBuffer";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkDestroyBuffer_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        let device: VkDevice = VkDevice(dec.handle()?);
        if device.0 == 0 {
            return Err(null_dispatch_handle(dec, "vkDestroyBuffer"));
        }
        let buffer: VkBuffer = VkBuffer(dec.handle()?);
        dec.null_allocator()?;
        Ok(Self { device, buffer })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkDestroyBuffer`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.handle(self.device.0)?;
        enc.handle(self.buffer.0)?;
        enc.null_allocator()?;
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkDestroyBuffer_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkDestroyBuffer_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'_>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        Ok(())
    }
}

/// The arguments of `vkBindBufferMemory2`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place and sets `ret`, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct BindBufferMemory2Args {
    /// `VkDevice device` — in.
    pub device: VkDevice,
    /// `uint32_t bindInfoCount` — in.
    pub bind_info_count: u32,
    /// `const VkBindBufferMemoryInfo* pBindInfos` — in.
    pub p_bind_infos: Option<Vec<VkBindBufferMemoryInfo>>,
    /// The return value (`VkResult`), written first in the reply.
    pub ret: VkResult,
}

impl BindBufferMemory2Args {
    /// `VK_COMMAND_TYPE_vkBindBufferMemory2_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_BIND_BUFFER_MEMORY_2_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkBindBufferMemory2";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkBindBufferMemory2_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        let device: VkDevice = VkDevice(dec.handle()?);
        if device.0 == 0 {
            return Err(null_dispatch_handle(dec, "vkBindBufferMemory2"));
        }
        let bind_info_count: u32 = dec.u32()?;
        let p_bind_infos: Option<Vec<VkBindBufferMemoryInfo>> =
            match array_presence(dec, u64::from(bind_info_count), NullArray::Checked)? {
                Some(n) => Some(decode_vec(dec, n, |dec| {
                    VkBindBufferMemoryInfo::decode_with(dec, false)
                })?),
                None => None,
            };
        Ok(Self {
            device,
            bind_info_count,
            p_bind_infos,
            ret: Default::default(),
        })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkBindBufferMemory2`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.handle(self.device.0)?;
        enc.u32(self.bind_info_count)?;
        if let Some(v) = &self.p_bind_infos {
            let count = u64::from(self.bind_info_count);
            check_len("vkBindBufferMemory2", "pBindInfos", count, v.len())?;
            enc.array_size(count)?;
            for e in v {
                e.encode_with(enc, false)?;
            }
        } else {
            enc.array_size(0)?;
        }
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkBindBufferMemory2_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        enc.i32(self.ret)?;
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkBindBufferMemory2_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'_>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        self.ret = dec.i32()?;
        Ok(())
    }

    /// Visit every pNext link the arguments carry, as `(parent, sType)`.
    pub fn for_each_link(&self, f: &mut dyn FnMut(&'static str, i32)) {
        for e in self.p_bind_infos.iter().flatten() {
            e.for_each_link(f);
        }
    }
}

/// The arguments of `vkGetBufferMemoryRequirements2`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct GetBufferMemoryRequirements2Args {
    /// `VkDevice device` — in.
    pub device: VkDevice,
    /// `const VkBufferMemoryRequirementsInfo2* pInfo` — in.
    pub p_info: Option<VkBufferMemoryRequirementsInfo2>,
    /// `VkMemoryRequirements2* pMemoryRequirements` — out.
    pub p_memory_requirements: Option<VkMemoryRequirements2>,
}

impl GetBufferMemoryRequirements2Args {
    /// `VK_COMMAND_TYPE_vkGetBufferMemoryRequirements2_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_GET_BUFFER_MEMORY_REQUIREMENTS_2_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkGetBufferMemoryRequirements2";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkGetBufferMemoryRequirements2_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        let device: VkDevice = VkDevice(dec.handle()?);
        if device.0 == 0 {
            return Err(null_dispatch_handle(dec, "vkGetBufferMemoryRequirements2"));
        }
        let p_info: Option<VkBufferMemoryRequirementsInfo2> = if dec.simple_pointer()? {
            Some(VkBufferMemoryRequirementsInfo2::decode_with(dec, false)?)
        } else {
            return Err(null_pointer(dec, "vkGetBufferMemoryRequirements2", "pInfo"));
        };
        let p_memory_requirements: Option<VkMemoryRequirements2> = if dec.simple_pointer()? {
            Some(VkMemoryRequirements2::decode_with(dec, true)?)
        } else {
            return Err(null_pointer(
                dec,
                "vkGetBufferMemoryRequirements2",
                "pMemoryRequirements",
            ));
        };
        Ok(Self {
            device,
            p_info,
            p_memory_requirements,
        })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkGetBufferMemoryRequirements2`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.handle(self.device.0)?;
        enc.simple_pointer(self.p_info.is_some())?;
        if let Some(v) = &self.p_info {
            v.encode_with(enc, false)?;
        }
        enc.simple_pointer(self.p_memory_requirements.is_some())?;
        if let Some(v) = &self.p_memory_requirements {
            v.encode_with(enc, true)?;
        }
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkGetBufferMemoryRequirements2_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        enc.simple_pointer(self.p_memory_requirements.is_some())?;
        if let Some(v) = &self.p_memory_requirements {
            v.encode_with(enc, false)?;
        }
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkGetBufferMemoryRequirements2_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'_>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        self.p_memory_requirements = if dec.simple_pointer()? {
            Some(VkMemoryRequirements2::decode_with(dec, false)?)
        } else {
            None
        };
        Ok(())
    }

    /// Visit every pNext link the arguments carry, as `(parent, sType)`.
    pub fn for_each_link(&self, f: &mut dyn FnMut(&'static str, i32)) {
        if let Some(v) = &self.p_memory_requirements {
            v.for_each_link(f);
        }
    }
}

/// The arguments of `vkGetDeviceBufferMemoryRequirements`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct GetDeviceBufferMemoryRequirementsArgs {
    /// `VkDevice device` — in.
    pub device: VkDevice,
    /// `const VkDeviceBufferMemoryRequirements* pInfo` — in.
    pub p_info: Option<VkDeviceBufferMemoryRequirements>,
    /// `VkMemoryRequirements2* pMemoryRequirements` — out.
    pub p_memory_requirements: Option<VkMemoryRequirements2>,
}

impl GetDeviceBufferMemoryRequirementsArgs {
    /// `VK_COMMAND_TYPE_vkGetDeviceBufferMemoryRequirements_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_GET_DEVICE_BUFFER_MEMORY_REQUIREMENTS_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkGetDeviceBufferMemoryRequirements";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkGetDeviceBufferMemoryRequirements_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        let device: VkDevice = VkDevice(dec.handle()?);
        if device.0 == 0 {
            return Err(null_dispatch_handle(
                dec,
                "vkGetDeviceBufferMemoryRequirements",
            ));
        }
        let p_info: Option<VkDeviceBufferMemoryRequirements> = if dec.simple_pointer()? {
            Some(VkDeviceBufferMemoryRequirements::decode_with(dec, false)?)
        } else {
            return Err(null_pointer(
                dec,
                "vkGetDeviceBufferMemoryRequirements",
                "pInfo",
            ));
        };
        let p_memory_requirements: Option<VkMemoryRequirements2> = if dec.simple_pointer()? {
            Some(VkMemoryRequirements2::decode_with(dec, true)?)
        } else {
            return Err(null_pointer(
                dec,
                "vkGetDeviceBufferMemoryRequirements",
                "pMemoryRequirements",
            ));
        };
        Ok(Self {
            device,
            p_info,
            p_memory_requirements,
        })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkGetDeviceBufferMemoryRequirements`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.handle(self.device.0)?;
        enc.simple_pointer(self.p_info.is_some())?;
        if let Some(v) = &self.p_info {
            v.encode_with(enc, false)?;
        }
        enc.simple_pointer(self.p_memory_requirements.is_some())?;
        if let Some(v) = &self.p_memory_requirements {
            v.encode_with(enc, true)?;
        }
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkGetDeviceBufferMemoryRequirements_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        enc.simple_pointer(self.p_memory_requirements.is_some())?;
        if let Some(v) = &self.p_memory_requirements {
            v.encode_with(enc, false)?;
        }
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkGetDeviceBufferMemoryRequirements_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'_>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        self.p_memory_requirements = if dec.simple_pointer()? {
            Some(VkMemoryRequirements2::decode_with(dec, false)?)
        } else {
            None
        };
        Ok(())
    }

    /// Visit every pNext link the arguments carry, as `(parent, sType)`.
    pub fn for_each_link(&self, f: &mut dyn FnMut(&'static str, i32)) {
        if let Some(v) = &self.p_info {
            v.for_each_link(f);
        }
        if let Some(v) = &self.p_memory_requirements {
            v.for_each_link(f);
        }
    }
}

/// The arguments of `vkGetBufferOpaqueCaptureAddress`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place and sets `ret`, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct GetBufferOpaqueCaptureAddressArgs {
    /// `VkDevice device` — in.
    pub device: VkDevice,
    /// `const VkBufferDeviceAddressInfo* pInfo` — in.
    pub p_info: Option<VkBufferDeviceAddressInfo>,
    /// The return value (`uint64_t`), written first in the reply.
    pub ret: u64,
}

impl GetBufferOpaqueCaptureAddressArgs {
    /// `VK_COMMAND_TYPE_vkGetBufferOpaqueCaptureAddress_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_GET_BUFFER_OPAQUE_CAPTURE_ADDRESS_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkGetBufferOpaqueCaptureAddress";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkGetBufferOpaqueCaptureAddress_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        let device: VkDevice = VkDevice(dec.handle()?);
        if device.0 == 0 {
            return Err(null_dispatch_handle(dec, "vkGetBufferOpaqueCaptureAddress"));
        }
        let p_info: Option<VkBufferDeviceAddressInfo> = if dec.simple_pointer()? {
            Some(VkBufferDeviceAddressInfo::decode_with(dec, false)?)
        } else {
            return Err(null_pointer(
                dec,
                "vkGetBufferOpaqueCaptureAddress",
                "pInfo",
            ));
        };
        Ok(Self {
            device,
            p_info,
            ret: Default::default(),
        })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkGetBufferOpaqueCaptureAddress`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.handle(self.device.0)?;
        enc.simple_pointer(self.p_info.is_some())?;
        if let Some(v) = &self.p_info {
            v.encode_with(enc, false)?;
        }
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkGetBufferOpaqueCaptureAddress_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        enc.u64(self.ret)?;
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkGetBufferOpaqueCaptureAddress_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'_>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        self.ret = dec.u64()?;
        Ok(())
    }
}

/// The arguments of `vkGetBufferDeviceAddress`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place and sets `ret`, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct GetBufferDeviceAddressArgs {
    /// `VkDevice device` — in.
    pub device: VkDevice,
    /// `const VkBufferDeviceAddressInfo* pInfo` — in.
    pub p_info: Option<VkBufferDeviceAddressInfo>,
    /// The return value (`VkDeviceAddress`), written first in the reply.
    pub ret: VkDeviceAddress,
}

impl GetBufferDeviceAddressArgs {
    /// `VK_COMMAND_TYPE_vkGetBufferDeviceAddress_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_GET_BUFFER_DEVICE_ADDRESS_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkGetBufferDeviceAddress";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkGetBufferDeviceAddress_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        let device: VkDevice = VkDevice(dec.handle()?);
        if device.0 == 0 {
            return Err(null_dispatch_handle(dec, "vkGetBufferDeviceAddress"));
        }
        let p_info: Option<VkBufferDeviceAddressInfo> = if dec.simple_pointer()? {
            Some(VkBufferDeviceAddressInfo::decode_with(dec, false)?)
        } else {
            return Err(null_pointer(dec, "vkGetBufferDeviceAddress", "pInfo"));
        };
        Ok(Self {
            device,
            p_info,
            ret: Default::default(),
        })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkGetBufferDeviceAddress`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.handle(self.device.0)?;
        enc.simple_pointer(self.p_info.is_some())?;
        if let Some(v) = &self.p_info {
            v.encode_with(enc, false)?;
        }
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkGetBufferDeviceAddress_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        enc.u64(self.ret)?;
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkGetBufferDeviceAddress_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'_>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        self.ret = dec.u64()?;
        Ok(())
    }
}
