// @generated by tools/venus-protocol/rust_protocol.py (templates/rust_group.rs)
// from venus-protocol git-70991d4c. DO NOT EDIT: regenerate with
//     python scripts/venus-gen.py

//! The `buffer_view` group: its commands and the structures only they reach.

#![allow(unused_imports)]

use super::*;
use crate::venus::wire::{CommandHeader, Decoder, Encoder};

/// `VkBufferViewCreateInfo` (`VK_STRUCTURE_TYPE_BUFFER_VIEW_CREATE_INFO`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkBufferViewCreateInfo {
    /// The pNext chain, in the guest's order. Admits: `VkBufferUsageFlags2CreateInfo`.
    pub p_next: Vec<VkBufferViewCreateInfoNext>,
    /// `VkBufferViewCreateFlags flags`
    pub flags: VkBufferViewCreateFlags,
    /// `VkBuffer buffer`
    pub buffer: VkBuffer,
    /// `VkFormat format`
    pub format: VkFormat,
    /// `VkDeviceSize offset`
    pub offset: VkDeviceSize,
    /// `VkDeviceSize range`
    pub range: VkDeviceSize,
}

impl VkBufferViewCreateInfo {
    // No output parameter reaches this structure, so it has no skeleton
    // form and the `partial` flag below is ignored.

    /// `VK_STRUCTURE_TYPE_BUFFER_VIEW_CREATE_INFO`.
    pub const STRUCTURE_TYPE: i32 = VK_STRUCTURE_TYPE_BUFFER_VIEW_CREATE_INFO;

    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// `decode` or `decode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        expect_structure_type(dec, "VkBufferViewCreateInfo", Self::STRUCTURE_TYPE)?;
        let p_next = decode_chain::<VkBufferViewCreateInfoNext>(dec, partial)?;
        let mut value = Self::decode_body(dec, partial)?;
        value.p_next = p_next;
        Ok(value)
    }

    /// `encode` or `encode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        enc.structure_type(Self::STRUCTURE_TYPE)?;
        encode_chain(enc, &self.p_next, partial)?;
        self.encode_body(enc, partial)
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them
    /// (`vn_decode_VkBufferViewCreateInfo_self_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_body(dec: &mut Decoder<'_>, _partial: bool) -> Result<Self, ProtocolError> {
        let flags: VkBufferViewCreateFlags = dec.u32()?;
        let buffer: VkBuffer = VkBuffer(dec.handle()?);
        let format: VkFormat = dec.i32()?;
        let offset: VkDeviceSize = dec.u64()?;
        let range: VkDeviceSize = dec.u64()?;
        Ok(Self {
            p_next: Vec::new(),
            flags,
            buffer,
            format,
            offset,
            range,
        })
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_body(&self, enc: &mut Encoder, _partial: bool) -> Result<(), ProtocolError> {
        enc.u32(self.flags)?;
        enc.handle(self.buffer.0)?;
        enc.i32(self.format)?;
        enc.u64(self.offset)?;
        enc.u64(self.range)?;
        Ok(())
    }

    /// Visit every pNext link this structure carries — its own chain's and
    /// its members' — as `(parent, sType)`.
    pub fn for_each_link(&self, f: &mut dyn FnMut(&'static str, i32)) {
        for link in &self.p_next {
            f("VkBufferViewCreateInfo", link.structure_type());
        }
    }
}

/// A link of `VkBufferViewCreateInfo`'s pNext chain.
#[derive(Debug, Clone, PartialEq)]
pub enum VkBufferViewCreateInfoNext {
    /// `VK_STRUCTURE_TYPE_BUFFER_USAGE_FLAGS_2_CREATE_INFO`.
    VkBufferUsageFlags2CreateInfo(VkBufferUsageFlags2CreateInfo),
}

impl<'a> ChainLink<'a> for VkBufferViewCreateInfoNext {
    const PARENT: &'static str = "VkBufferViewCreateInfo";

    fn structure_type(&self) -> i32 {
        match self {
            Self::VkBufferUsageFlags2CreateInfo(_) => {
                VK_STRUCTURE_TYPE_BUFFER_USAGE_FLAGS_2_CREATE_INFO
            }
        }
    }

    fn decode_body(
        stype: i32,
        dec: &mut Decoder<'a>,
        partial: bool,
    ) -> Option<Result<Self, ProtocolError>> {
        Some(match stype {
            VK_STRUCTURE_TYPE_BUFFER_USAGE_FLAGS_2_CREATE_INFO => {
                VkBufferUsageFlags2CreateInfo::decode_body(dec, partial)
                    .map(Self::VkBufferUsageFlags2CreateInfo)
            }
            _ => return None,
        })
    }

    fn encode_body(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        match self {
            Self::VkBufferUsageFlags2CreateInfo(link) => link.encode_body(enc, partial),
        }
    }
}

/// The arguments of `vkCreateBufferView`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place and sets `ret`, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct CreateBufferViewArgs {
    /// `VkDevice device` — in.
    pub device: VkDevice,
    /// `const VkBufferViewCreateInfo* pCreateInfo` — in.
    pub p_create_info: Option<VkBufferViewCreateInfo>,
    /// `VkBufferView* pView` — out.
    pub p_view: Option<VkBufferView>,
    /// The return value (`VkResult`), written first in the reply.
    pub ret: VkResult,
}

impl CreateBufferViewArgs {
    /// `VK_COMMAND_TYPE_vkCreateBufferView_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_CREATE_BUFFER_VIEW_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkCreateBufferView";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkCreateBufferView_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        let device: VkDevice = VkDevice(dec.handle()?);
        if device.0 == 0 {
            return Err(null_dispatch_handle(dec, "vkCreateBufferView"));
        }
        let p_create_info: Option<VkBufferViewCreateInfo> = if dec.simple_pointer()? {
            Some(VkBufferViewCreateInfo::decode_with(dec, false)?)
        } else {
            return Err(null_pointer(dec, "vkCreateBufferView", "pCreateInfo"));
        };
        dec.null_allocator()?;
        let p_view: Option<VkBufferView> = if dec.simple_pointer()? {
            Some(VkBufferView(dec.handle()?))
        } else {
            return Err(null_pointer(dec, "vkCreateBufferView", "pView"));
        };
        Ok(Self {
            device,
            p_create_info,
            p_view,
            ret: Default::default(),
        })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkCreateBufferView`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.handle(self.device.0)?;
        enc.simple_pointer(self.p_create_info.is_some())?;
        if let Some(v) = &self.p_create_info {
            v.encode_with(enc, false)?;
        }
        enc.null_allocator()?;
        enc.simple_pointer(self.p_view.is_some())?;
        if let Some(v) = &self.p_view {
            enc.handle(v.0)?;
        }
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkCreateBufferView_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        enc.i32(self.ret)?;
        enc.simple_pointer(self.p_view.is_some())?;
        if let Some(v) = &self.p_view {
            enc.handle(v.0)?;
        }
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkCreateBufferView_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'_>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        self.ret = dec.i32()?;
        self.p_view = if dec.simple_pointer()? {
            Some(VkBufferView(dec.handle()?))
        } else {
            None
        };
        Ok(())
    }

    /// Visit every pNext link the arguments carry, as `(parent, sType)`.
    pub fn for_each_link(&self, f: &mut dyn FnMut(&'static str, i32)) {
        if let Some(v) = &self.p_create_info {
            v.for_each_link(f);
        }
    }
}

/// The arguments of `vkDestroyBufferView`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct DestroyBufferViewArgs {
    /// `VkDevice device` — in.
    pub device: VkDevice,
    /// `VkBufferView bufferView` — in.
    pub buffer_view: VkBufferView,
}

impl DestroyBufferViewArgs {
    /// `VK_COMMAND_TYPE_vkDestroyBufferView_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_DESTROY_BUFFER_VIEW_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkDestroyBufferView";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkDestroyBufferView_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        let device: VkDevice = VkDevice(dec.handle()?);
        if device.0 == 0 {
            return Err(null_dispatch_handle(dec, "vkDestroyBufferView"));
        }
        let buffer_view: VkBufferView = VkBufferView(dec.handle()?);
        dec.null_allocator()?;
        Ok(Self {
            device,
            buffer_view,
        })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkDestroyBufferView`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.handle(self.device.0)?;
        enc.handle(self.buffer_view.0)?;
        enc.null_allocator()?;
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkDestroyBufferView_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkDestroyBufferView_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'_>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        Ok(())
    }
}
