// @generated by tools/venus-protocol/rust_protocol.py (templates/rust_group.rs)
// from venus-protocol git-70991d4c. DO NOT EDIT: regenerate with
//     python scripts/venus-gen.py

//! The `descriptor_set_layout` group: its commands and the structures only they reach.

#![allow(unused_imports)]

use super::*;
use crate::venus::wire::{CommandHeader, Decoder, Encoder};

/// `VkDescriptorSetLayoutBinding`.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkDescriptorSetLayoutBinding {
    /// `uint32_t binding`
    pub binding: u32,
    /// `VkDescriptorType descriptorType`
    pub descriptor_type: VkDescriptorType,
    /// `uint32_t descriptorCount`
    pub descriptor_count: u32,
    /// `VkShaderStageFlags stageFlags`
    pub stage_flags: VkShaderStageFlags,
    /// `const VkSampler* pImmutableSamplers`
    pub p_immutable_samplers: Option<Vec<VkSampler>>,
}

impl VkDescriptorSetLayoutBinding {
    // No output parameter reaches this structure, so it has no skeleton
    // form and the `partial` flag below is ignored.

    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// `decode` or `decode_partial`.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'_>, _partial: bool) -> Result<Self, ProtocolError> {
        let binding: u32 = dec.u32()?;
        let descriptor_type: VkDescriptorType = dec.i32()?;
        let descriptor_count: u32 = dec.u32()?;
        let stage_flags: VkShaderStageFlags = dec.u32()?;
        let p_immutable_samplers: Option<Vec<VkSampler>> =
            match array_presence(dec, u64::from(descriptor_count), NullArray::Unchecked)? {
                Some(n) => Some(decode_vec(dec, n, |dec| {
                    dec.handle().map(VkSampler).map_err(ProtocolError::from)
                })?),
                None => None,
            };
        Ok(Self {
            binding,
            descriptor_type,
            descriptor_count,
            stage_flags,
            p_immutable_samplers,
        })
    }

    /// `encode` or `encode_partial`.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, _partial: bool) -> Result<(), ProtocolError> {
        enc.u32(self.binding)?;
        enc.i32(self.descriptor_type)?;
        enc.u32(self.descriptor_count)?;
        enc.u32(self.stage_flags)?;
        if let Some(v) = &self.p_immutable_samplers {
            let count = u64::from(self.descriptor_count);
            check_len(
                "VkDescriptorSetLayoutBinding",
                "pImmutableSamplers",
                count,
                v.len(),
            )?;
            enc.array_size(count)?;
            for e in v {
                enc.handle(e.0)?;
            }
        } else {
            enc.array_size(0)?;
        }
        Ok(())
    }
}

/// `VkDescriptorSetLayoutCreateInfo` (`VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkDescriptorSetLayoutCreateInfo {
    /// The pNext chain, in the guest's order. Admits: `VkDescriptorSetLayoutBindingFlagsCreateInfo`, `VkMutableDescriptorTypeCreateInfoEXT`.
    pub p_next: Vec<VkDescriptorSetLayoutCreateInfoNext>,
    /// `VkDescriptorSetLayoutCreateFlags flags`
    pub flags: VkDescriptorSetLayoutCreateFlags,
    /// `uint32_t bindingCount`
    pub binding_count: u32,
    /// `const VkDescriptorSetLayoutBinding* pBindings`
    pub p_bindings: Option<Vec<VkDescriptorSetLayoutBinding>>,
}

impl VkDescriptorSetLayoutCreateInfo {
    // No output parameter reaches this structure, so it has no skeleton
    // form and the `partial` flag below is ignored.

    /// `VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO`.
    pub const STRUCTURE_TYPE: i32 = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO;

    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// `decode` or `decode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        expect_structure_type(dec, "VkDescriptorSetLayoutCreateInfo", Self::STRUCTURE_TYPE)?;
        let p_next = decode_chain::<VkDescriptorSetLayoutCreateInfoNext>(dec, partial)?;
        let mut value = Self::decode_body(dec, partial)?;
        value.p_next = p_next;
        Ok(value)
    }

    /// `encode` or `encode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        enc.structure_type(Self::STRUCTURE_TYPE)?;
        encode_chain(enc, &self.p_next, partial)?;
        self.encode_body(enc, partial)
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them
    /// (`vn_decode_VkDescriptorSetLayoutCreateInfo_self_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_body(dec: &mut Decoder<'_>, _partial: bool) -> Result<Self, ProtocolError> {
        let flags: VkDescriptorSetLayoutCreateFlags = dec.u32()?;
        let binding_count: u32 = dec.u32()?;
        let p_bindings: Option<Vec<VkDescriptorSetLayoutBinding>> =
            match array_presence(dec, u64::from(binding_count), NullArray::Checked)? {
                Some(n) => Some(decode_vec(dec, n, |dec| {
                    VkDescriptorSetLayoutBinding::decode_with(dec, false)
                })?),
                None => None,
            };
        Ok(Self {
            p_next: Vec::new(),
            flags,
            binding_count,
            p_bindings,
        })
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_body(&self, enc: &mut Encoder, _partial: bool) -> Result<(), ProtocolError> {
        enc.u32(self.flags)?;
        enc.u32(self.binding_count)?;
        if let Some(v) = &self.p_bindings {
            let count = u64::from(self.binding_count);
            check_len(
                "VkDescriptorSetLayoutCreateInfo",
                "pBindings",
                count,
                v.len(),
            )?;
            enc.array_size(count)?;
            for e in v {
                e.encode_with(enc, false)?;
            }
        } else {
            enc.array_size(0)?;
        }
        Ok(())
    }

    /// Visit every pNext link this structure carries — its own chain's and
    /// its members' — as `(parent, sType)`.
    pub fn for_each_link(&self, f: &mut dyn FnMut(&'static str, i32)) {
        for link in &self.p_next {
            f("VkDescriptorSetLayoutCreateInfo", link.structure_type());
        }
    }
}

/// A link of `VkDescriptorSetLayoutCreateInfo`'s pNext chain.
#[derive(Debug, Clone, PartialEq)]
pub enum VkDescriptorSetLayoutCreateInfoNext {
    /// `VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_BINDING_FLAGS_CREATE_INFO`.
    VkDescriptorSetLayoutBindingFlagsCreateInfo(VkDescriptorSetLayoutBindingFlagsCreateInfo),
    /// `VK_STRUCTURE_TYPE_MUTABLE_DESCRIPTOR_TYPE_CREATE_INFO_EXT`.
    VkMutableDescriptorTypeCreateInfoEXT(VkMutableDescriptorTypeCreateInfoEXT),
}

impl<'a> ChainLink<'a> for VkDescriptorSetLayoutCreateInfoNext {
    const PARENT: &'static str = "VkDescriptorSetLayoutCreateInfo";

    fn structure_type(&self) -> i32 {
        match self {
            Self::VkDescriptorSetLayoutBindingFlagsCreateInfo(_) => {
                VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_BINDING_FLAGS_CREATE_INFO
            }
            Self::VkMutableDescriptorTypeCreateInfoEXT(_) => {
                VK_STRUCTURE_TYPE_MUTABLE_DESCRIPTOR_TYPE_CREATE_INFO_EXT
            }
        }
    }

    fn decode_body(
        stype: i32,
        dec: &mut Decoder<'a>,
        partial: bool,
    ) -> Option<Result<Self, ProtocolError>> {
        Some(match stype {
            VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_BINDING_FLAGS_CREATE_INFO => {
                VkDescriptorSetLayoutBindingFlagsCreateInfo::decode_body(dec, partial)
                    .map(Self::VkDescriptorSetLayoutBindingFlagsCreateInfo)
            }
            VK_STRUCTURE_TYPE_MUTABLE_DESCRIPTOR_TYPE_CREATE_INFO_EXT => {
                VkMutableDescriptorTypeCreateInfoEXT::decode_body(dec, partial)
                    .map(Self::VkMutableDescriptorTypeCreateInfoEXT)
            }
            _ => return None,
        })
    }

    fn encode_body(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        match self {
            Self::VkDescriptorSetLayoutBindingFlagsCreateInfo(link) => {
                link.encode_body(enc, partial)
            }
            Self::VkMutableDescriptorTypeCreateInfoEXT(link) => link.encode_body(enc, partial),
        }
    }
}

/// `VkDescriptorSetLayoutBindingFlagsCreateInfo` (`VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_BINDING_FLAGS_CREATE_INFO`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkDescriptorSetLayoutBindingFlagsCreateInfo {
    /// `uint32_t bindingCount`
    pub binding_count: u32,
    /// `const VkDescriptorBindingFlags* pBindingFlags`
    pub p_binding_flags: Option<Vec<VkDescriptorBindingFlags>>,
}

impl VkDescriptorSetLayoutBindingFlagsCreateInfo {
    // No output parameter reaches this structure, so it has no skeleton
    // form and the `partial` flag below is ignored.

    /// `VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_BINDING_FLAGS_CREATE_INFO`.
    pub const STRUCTURE_TYPE: i32 =
        VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_BINDING_FLAGS_CREATE_INFO;

    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// `decode` or `decode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        expect_structure_type(
            dec,
            "VkDescriptorSetLayoutBindingFlagsCreateInfo",
            Self::STRUCTURE_TYPE,
        )?;
        dec.empty_pnext_chain("VkDescriptorSetLayoutBindingFlagsCreateInfo")?;
        Self::decode_body(dec, partial)
    }

    /// `encode` or `encode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        enc.structure_type(Self::STRUCTURE_TYPE)?;
        enc.simple_pointer(false)?;
        self.encode_body(enc, partial)
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them
    /// (`vn_decode_VkDescriptorSetLayoutBindingFlagsCreateInfo_self_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_body(dec: &mut Decoder<'_>, _partial: bool) -> Result<Self, ProtocolError> {
        let binding_count: u32 = dec.u32()?;
        let p_binding_flags: Option<Vec<VkDescriptorBindingFlags>> =
            match array_presence(dec, u64::from(binding_count), NullArray::Checked)? {
                Some(n) => Some(dec.u32_array(n)?),
                None => None,
            };
        Ok(Self {
            binding_count,
            p_binding_flags,
        })
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_body(&self, enc: &mut Encoder, _partial: bool) -> Result<(), ProtocolError> {
        enc.u32(self.binding_count)?;
        if let Some(v) = &self.p_binding_flags {
            let count = u64::from(self.binding_count);
            check_len(
                "VkDescriptorSetLayoutBindingFlagsCreateInfo",
                "pBindingFlags",
                count,
                v.len(),
            )?;
            enc.array_size(count)?;
            for e in v {
                enc.u32(*e)?;
            }
        } else {
            enc.array_size(0)?;
        }
        Ok(())
    }
}

/// `VkDescriptorSetLayoutSupport` (`VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_SUPPORT`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkDescriptorSetLayoutSupport {
    /// The pNext chain, in the guest's order. Admits: `VkDescriptorSetVariableDescriptorCountLayoutSupport`.
    pub p_next: Vec<VkDescriptorSetLayoutSupportNext>,
    /// `VkBool32 supported`
    pub supported: VkBool32,
}

impl VkDescriptorSetLayoutSupport {
    /// `VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_SUPPORT`.
    pub const STRUCTURE_TYPE: i32 = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_SUPPORT;

    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Decode the skeleton an output structure is sent as inside a command
    /// (`vn_decode_VkDescriptorSetLayoutSupport_partial_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_partial(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, true)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// Encode the skeleton form (`vn_encode_VkDescriptorSetLayoutSupport_partial`).
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_partial(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, true)
    }

    /// `decode` or `decode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        expect_structure_type(dec, "VkDescriptorSetLayoutSupport", Self::STRUCTURE_TYPE)?;
        let p_next = decode_chain::<VkDescriptorSetLayoutSupportNext>(dec, partial)?;
        let mut value = Self::decode_body(dec, partial)?;
        value.p_next = p_next;
        Ok(value)
    }

    /// `encode` or `encode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        enc.structure_type(Self::STRUCTURE_TYPE)?;
        encode_chain(enc, &self.p_next, partial)?;
        self.encode_body(enc, partial)
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them
    /// (`vn_decode_VkDescriptorSetLayoutSupport_self_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_body(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        let supported: VkBool32 = if partial {
            Default::default()
        } else {
            dec.u32()?
        };
        Ok(Self {
            p_next: Vec::new(),
            supported,
        })
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_body(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        if !partial {
            enc.u32(self.supported)?;
        }
        Ok(())
    }

    /// Visit every pNext link this structure carries — its own chain's and
    /// its members' — as `(parent, sType)`.
    pub fn for_each_link(&self, f: &mut dyn FnMut(&'static str, i32)) {
        for link in &self.p_next {
            f("VkDescriptorSetLayoutSupport", link.structure_type());
        }
    }
}

/// A link of `VkDescriptorSetLayoutSupport`'s pNext chain.
#[derive(Debug, Clone, PartialEq)]
pub enum VkDescriptorSetLayoutSupportNext {
    /// `VK_STRUCTURE_TYPE_DESCRIPTOR_SET_VARIABLE_DESCRIPTOR_COUNT_LAYOUT_SUPPORT`.
    VkDescriptorSetVariableDescriptorCountLayoutSupport(
        VkDescriptorSetVariableDescriptorCountLayoutSupport,
    ),
}

impl<'a> ChainLink<'a> for VkDescriptorSetLayoutSupportNext {
    const PARENT: &'static str = "VkDescriptorSetLayoutSupport";

    fn structure_type(&self) -> i32 {
        match self {
            Self::VkDescriptorSetVariableDescriptorCountLayoutSupport(_) => {
                VK_STRUCTURE_TYPE_DESCRIPTOR_SET_VARIABLE_DESCRIPTOR_COUNT_LAYOUT_SUPPORT
            }
        }
    }

    fn decode_body(
        stype: i32,
        dec: &mut Decoder<'a>,
        partial: bool,
    ) -> Option<Result<Self, ProtocolError>> {
        Some(match stype {
            VK_STRUCTURE_TYPE_DESCRIPTOR_SET_VARIABLE_DESCRIPTOR_COUNT_LAYOUT_SUPPORT => {
                VkDescriptorSetVariableDescriptorCountLayoutSupport::decode_body(dec, partial)
                    .map(Self::VkDescriptorSetVariableDescriptorCountLayoutSupport)
            }
            _ => return None,
        })
    }

    fn encode_body(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        match self {
            Self::VkDescriptorSetVariableDescriptorCountLayoutSupport(link) => {
                link.encode_body(enc, partial)
            }
        }
    }
}

/// `VkDescriptorSetVariableDescriptorCountLayoutSupport` (`VK_STRUCTURE_TYPE_DESCRIPTOR_SET_VARIABLE_DESCRIPTOR_COUNT_LAYOUT_SUPPORT`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkDescriptorSetVariableDescriptorCountLayoutSupport {
    /// `uint32_t maxVariableDescriptorCount`
    pub max_variable_descriptor_count: u32,
}

impl VkDescriptorSetVariableDescriptorCountLayoutSupport {
    /// `VK_STRUCTURE_TYPE_DESCRIPTOR_SET_VARIABLE_DESCRIPTOR_COUNT_LAYOUT_SUPPORT`.
    pub const STRUCTURE_TYPE: i32 =
        VK_STRUCTURE_TYPE_DESCRIPTOR_SET_VARIABLE_DESCRIPTOR_COUNT_LAYOUT_SUPPORT;

    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Decode the skeleton an output structure is sent as inside a command
    /// (`vn_decode_VkDescriptorSetVariableDescriptorCountLayoutSupport_partial_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_partial(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, true)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// Encode the skeleton form (`vn_encode_VkDescriptorSetVariableDescriptorCountLayoutSupport_partial`).
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_partial(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, true)
    }

    /// `decode` or `decode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        expect_structure_type(
            dec,
            "VkDescriptorSetVariableDescriptorCountLayoutSupport",
            Self::STRUCTURE_TYPE,
        )?;
        dec.empty_pnext_chain("VkDescriptorSetVariableDescriptorCountLayoutSupport")?;
        Self::decode_body(dec, partial)
    }

    /// `encode` or `encode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        enc.structure_type(Self::STRUCTURE_TYPE)?;
        enc.simple_pointer(false)?;
        self.encode_body(enc, partial)
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them
    /// (`vn_decode_VkDescriptorSetVariableDescriptorCountLayoutSupport_self_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_body(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        let max_variable_descriptor_count: u32 = if partial {
            Default::default()
        } else {
            dec.u32()?
        };
        Ok(Self {
            max_variable_descriptor_count,
        })
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_body(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        if !partial {
            enc.u32(self.max_variable_descriptor_count)?;
        }
        Ok(())
    }
}

/// The arguments of `vkCreateDescriptorSetLayout`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place and sets `ret`, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct CreateDescriptorSetLayoutArgs {
    /// `VkDevice device` — in.
    pub device: VkDevice,
    /// `const VkDescriptorSetLayoutCreateInfo* pCreateInfo` — in.
    pub p_create_info: Option<VkDescriptorSetLayoutCreateInfo>,
    /// `VkDescriptorSetLayout* pSetLayout` — out.
    pub p_set_layout: Option<VkDescriptorSetLayout>,
    /// The return value (`VkResult`), written first in the reply.
    pub ret: VkResult,
}

impl CreateDescriptorSetLayoutArgs {
    /// `VK_COMMAND_TYPE_vkCreateDescriptorSetLayout_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_CREATE_DESCRIPTOR_SET_LAYOUT_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkCreateDescriptorSetLayout";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkCreateDescriptorSetLayout_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        let device: VkDevice = VkDevice(dec.handle()?);
        if device.0 == 0 {
            return Err(null_dispatch_handle(dec, "vkCreateDescriptorSetLayout"));
        }
        let p_create_info: Option<VkDescriptorSetLayoutCreateInfo> = if dec.simple_pointer()? {
            Some(VkDescriptorSetLayoutCreateInfo::decode_with(dec, false)?)
        } else {
            return Err(null_pointer(
                dec,
                "vkCreateDescriptorSetLayout",
                "pCreateInfo",
            ));
        };
        dec.null_allocator()?;
        let p_set_layout: Option<VkDescriptorSetLayout> = if dec.simple_pointer()? {
            Some(VkDescriptorSetLayout(dec.handle()?))
        } else {
            return Err(null_pointer(
                dec,
                "vkCreateDescriptorSetLayout",
                "pSetLayout",
            ));
        };
        Ok(Self {
            device,
            p_create_info,
            p_set_layout,
            ret: Default::default(),
        })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkCreateDescriptorSetLayout`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.handle(self.device.0)?;
        enc.simple_pointer(self.p_create_info.is_some())?;
        if let Some(v) = &self.p_create_info {
            v.encode_with(enc, false)?;
        }
        enc.null_allocator()?;
        enc.simple_pointer(self.p_set_layout.is_some())?;
        if let Some(v) = &self.p_set_layout {
            enc.handle(v.0)?;
        }
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkCreateDescriptorSetLayout_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        enc.i32(self.ret)?;
        enc.simple_pointer(self.p_set_layout.is_some())?;
        if let Some(v) = &self.p_set_layout {
            enc.handle(v.0)?;
        }
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkCreateDescriptorSetLayout_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'_>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        self.ret = dec.i32()?;
        self.p_set_layout = if dec.simple_pointer()? {
            Some(VkDescriptorSetLayout(dec.handle()?))
        } else {
            None
        };
        Ok(())
    }

    /// Visit every pNext link the arguments carry, as `(parent, sType)`.
    pub fn for_each_link(&self, f: &mut dyn FnMut(&'static str, i32)) {
        if let Some(v) = &self.p_create_info {
            v.for_each_link(f);
        }
    }
}

/// The arguments of `vkDestroyDescriptorSetLayout`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct DestroyDescriptorSetLayoutArgs {
    /// `VkDevice device` — in.
    pub device: VkDevice,
    /// `VkDescriptorSetLayout descriptorSetLayout` — in.
    pub descriptor_set_layout: VkDescriptorSetLayout,
}

impl DestroyDescriptorSetLayoutArgs {
    /// `VK_COMMAND_TYPE_vkDestroyDescriptorSetLayout_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_DESTROY_DESCRIPTOR_SET_LAYOUT_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkDestroyDescriptorSetLayout";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkDestroyDescriptorSetLayout_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        let device: VkDevice = VkDevice(dec.handle()?);
        if device.0 == 0 {
            return Err(null_dispatch_handle(dec, "vkDestroyDescriptorSetLayout"));
        }
        let descriptor_set_layout: VkDescriptorSetLayout = VkDescriptorSetLayout(dec.handle()?);
        dec.null_allocator()?;
        Ok(Self {
            device,
            descriptor_set_layout,
        })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkDestroyDescriptorSetLayout`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.handle(self.device.0)?;
        enc.handle(self.descriptor_set_layout.0)?;
        enc.null_allocator()?;
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkDestroyDescriptorSetLayout_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkDestroyDescriptorSetLayout_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'_>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        Ok(())
    }
}

/// The arguments of `vkGetDescriptorSetLayoutSupport`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct GetDescriptorSetLayoutSupportArgs {
    /// `VkDevice device` — in.
    pub device: VkDevice,
    /// `const VkDescriptorSetLayoutCreateInfo* pCreateInfo` — in.
    pub p_create_info: Option<VkDescriptorSetLayoutCreateInfo>,
    /// `VkDescriptorSetLayoutSupport* pSupport` — out.
    pub p_support: Option<VkDescriptorSetLayoutSupport>,
}

impl GetDescriptorSetLayoutSupportArgs {
    /// `VK_COMMAND_TYPE_vkGetDescriptorSetLayoutSupport_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_GET_DESCRIPTOR_SET_LAYOUT_SUPPORT_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkGetDescriptorSetLayoutSupport";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkGetDescriptorSetLayoutSupport_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        let device: VkDevice = VkDevice(dec.handle()?);
        if device.0 == 0 {
            return Err(null_dispatch_handle(dec, "vkGetDescriptorSetLayoutSupport"));
        }
        let p_create_info: Option<VkDescriptorSetLayoutCreateInfo> = if dec.simple_pointer()? {
            Some(VkDescriptorSetLayoutCreateInfo::decode_with(dec, false)?)
        } else {
            return Err(null_pointer(
                dec,
                "vkGetDescriptorSetLayoutSupport",
                "pCreateInfo",
            ));
        };
        let p_support: Option<VkDescriptorSetLayoutSupport> = if dec.simple_pointer()? {
            Some(VkDescriptorSetLayoutSupport::decode_with(dec, true)?)
        } else {
            return Err(null_pointer(
                dec,
                "vkGetDescriptorSetLayoutSupport",
                "pSupport",
            ));
        };
        Ok(Self {
            device,
            p_create_info,
            p_support,
        })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkGetDescriptorSetLayoutSupport`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.handle(self.device.0)?;
        enc.simple_pointer(self.p_create_info.is_some())?;
        if let Some(v) = &self.p_create_info {
            v.encode_with(enc, false)?;
        }
        enc.simple_pointer(self.p_support.is_some())?;
        if let Some(v) = &self.p_support {
            v.encode_with(enc, true)?;
        }
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkGetDescriptorSetLayoutSupport_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        enc.simple_pointer(self.p_support.is_some())?;
        if let Some(v) = &self.p_support {
            v.encode_with(enc, false)?;
        }
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkGetDescriptorSetLayoutSupport_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'_>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        self.p_support = if dec.simple_pointer()? {
            Some(VkDescriptorSetLayoutSupport::decode_with(dec, false)?)
        } else {
            None
        };
        Ok(())
    }

    /// Visit every pNext link the arguments carry, as `(parent, sType)`.
    pub fn for_each_link(&self, f: &mut dyn FnMut(&'static str, i32)) {
        if let Some(v) = &self.p_create_info {
            v.for_each_link(f);
        }
        if let Some(v) = &self.p_support {
            v.for_each_link(f);
        }
    }
}
