// @generated by tools/venus-protocol/rust_protocol.py (templates/rust_group.rs)
// from venus-protocol git-70991d4c. DO NOT EDIT: regenerate with
//     python scripts/venus-gen.py

//! The `descriptor_pool` group: its commands and the structures only they reach.

#![allow(unused_imports)]

use super::*;
use crate::venus::wire::{CommandHeader, Decoder, Encoder};

/// `VkDescriptorPoolSize`.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkDescriptorPoolSize {
    /// `VkDescriptorType type`
    pub type_: VkDescriptorType,
    /// `uint32_t descriptorCount`
    pub descriptor_count: u32,
}

impl VkDescriptorPoolSize {
    // No output parameter reaches this structure, so it has no skeleton
    // form and the `partial` flag below is ignored.

    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// `decode` or `decode_partial`.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'_>, _partial: bool) -> Result<Self, ProtocolError> {
        let type_: VkDescriptorType = dec.i32()?;
        let descriptor_count: u32 = dec.u32()?;
        Ok(Self {
            type_,
            descriptor_count,
        })
    }

    /// `encode` or `encode_partial`.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, _partial: bool) -> Result<(), ProtocolError> {
        enc.i32(self.type_)?;
        enc.u32(self.descriptor_count)?;
        Ok(())
    }
}

/// `VkDescriptorPoolCreateInfo` (`VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkDescriptorPoolCreateInfo {
    /// The pNext chain, in the guest's order. Admits: `VkDescriptorPoolInlineUniformBlockCreateInfo`, `VkMutableDescriptorTypeCreateInfoEXT`.
    pub p_next: Vec<VkDescriptorPoolCreateInfoNext>,
    /// `VkDescriptorPoolCreateFlags flags`
    pub flags: VkDescriptorPoolCreateFlags,
    /// `uint32_t maxSets`
    pub max_sets: u32,
    /// `uint32_t poolSizeCount`
    pub pool_size_count: u32,
    /// `const VkDescriptorPoolSize* pPoolSizes`
    pub p_pool_sizes: Option<Vec<VkDescriptorPoolSize>>,
}

impl VkDescriptorPoolCreateInfo {
    // No output parameter reaches this structure, so it has no skeleton
    // form and the `partial` flag below is ignored.

    /// `VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO`.
    pub const STRUCTURE_TYPE: i32 = VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO;

    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// `decode` or `decode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        expect_structure_type(dec, "VkDescriptorPoolCreateInfo", Self::STRUCTURE_TYPE)?;
        let p_next = decode_chain::<VkDescriptorPoolCreateInfoNext>(dec, partial)?;
        let mut value = Self::decode_body(dec, partial)?;
        value.p_next = p_next;
        Ok(value)
    }

    /// `encode` or `encode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        enc.structure_type(Self::STRUCTURE_TYPE)?;
        encode_chain(enc, &self.p_next, partial)?;
        self.encode_body(enc, partial)
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them
    /// (`vn_decode_VkDescriptorPoolCreateInfo_self_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_body(dec: &mut Decoder<'_>, _partial: bool) -> Result<Self, ProtocolError> {
        let flags: VkDescriptorPoolCreateFlags = dec.u32()?;
        let max_sets: u32 = dec.u32()?;
        let pool_size_count: u32 = dec.u32()?;
        let p_pool_sizes: Option<Vec<VkDescriptorPoolSize>> =
            match array_presence(dec, u64::from(pool_size_count), NullArray::Checked)? {
                Some(n) => Some(decode_vec(dec, n, |dec| {
                    VkDescriptorPoolSize::decode_with(dec, false)
                })?),
                None => None,
            };
        Ok(Self {
            p_next: Vec::new(),
            flags,
            max_sets,
            pool_size_count,
            p_pool_sizes,
        })
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_body(&self, enc: &mut Encoder, _partial: bool) -> Result<(), ProtocolError> {
        enc.u32(self.flags)?;
        enc.u32(self.max_sets)?;
        enc.u32(self.pool_size_count)?;
        if let Some(v) = &self.p_pool_sizes {
            let count = u64::from(self.pool_size_count);
            check_len("VkDescriptorPoolCreateInfo", "pPoolSizes", count, v.len())?;
            enc.array_size(count)?;
            for e in v {
                e.encode_with(enc, false)?;
            }
        } else {
            enc.array_size(0)?;
        }
        Ok(())
    }

    /// Visit every pNext link this structure carries — its own chain's and
    /// its members' — as `(parent, sType)`.
    pub fn for_each_link(&self, f: &mut dyn FnMut(&'static str, i32)) {
        for link in &self.p_next {
            f("VkDescriptorPoolCreateInfo", link.structure_type());
        }
    }
}

/// A link of `VkDescriptorPoolCreateInfo`'s pNext chain.
#[derive(Debug, Clone, PartialEq)]
pub enum VkDescriptorPoolCreateInfoNext {
    /// `VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_INLINE_UNIFORM_BLOCK_CREATE_INFO`.
    VkDescriptorPoolInlineUniformBlockCreateInfo(VkDescriptorPoolInlineUniformBlockCreateInfo),
    /// `VK_STRUCTURE_TYPE_MUTABLE_DESCRIPTOR_TYPE_CREATE_INFO_EXT`.
    VkMutableDescriptorTypeCreateInfoEXT(VkMutableDescriptorTypeCreateInfoEXT),
}

impl<'a> ChainLink<'a> for VkDescriptorPoolCreateInfoNext {
    const PARENT: &'static str = "VkDescriptorPoolCreateInfo";

    fn structure_type(&self) -> i32 {
        match self {
            Self::VkDescriptorPoolInlineUniformBlockCreateInfo(_) => {
                VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_INLINE_UNIFORM_BLOCK_CREATE_INFO
            }
            Self::VkMutableDescriptorTypeCreateInfoEXT(_) => {
                VK_STRUCTURE_TYPE_MUTABLE_DESCRIPTOR_TYPE_CREATE_INFO_EXT
            }
        }
    }

    fn decode_body(
        stype: i32,
        dec: &mut Decoder<'a>,
        partial: bool,
    ) -> Option<Result<Self, ProtocolError>> {
        Some(match stype {
            VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_INLINE_UNIFORM_BLOCK_CREATE_INFO => {
                VkDescriptorPoolInlineUniformBlockCreateInfo::decode_body(dec, partial)
                    .map(Self::VkDescriptorPoolInlineUniformBlockCreateInfo)
            }
            VK_STRUCTURE_TYPE_MUTABLE_DESCRIPTOR_TYPE_CREATE_INFO_EXT => {
                VkMutableDescriptorTypeCreateInfoEXT::decode_body(dec, partial)
                    .map(Self::VkMutableDescriptorTypeCreateInfoEXT)
            }
            _ => return None,
        })
    }

    fn encode_body(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        match self {
            Self::VkDescriptorPoolInlineUniformBlockCreateInfo(link) => {
                link.encode_body(enc, partial)
            }
            Self::VkMutableDescriptorTypeCreateInfoEXT(link) => link.encode_body(enc, partial),
        }
    }
}

/// `VkDescriptorPoolInlineUniformBlockCreateInfo` (`VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_INLINE_UNIFORM_BLOCK_CREATE_INFO`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkDescriptorPoolInlineUniformBlockCreateInfo {
    /// `uint32_t maxInlineUniformBlockBindings`
    pub max_inline_uniform_block_bindings: u32,
}

impl VkDescriptorPoolInlineUniformBlockCreateInfo {
    // No output parameter reaches this structure, so it has no skeleton
    // form and the `partial` flag below is ignored.

    /// `VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_INLINE_UNIFORM_BLOCK_CREATE_INFO`.
    pub const STRUCTURE_TYPE: i32 =
        VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_INLINE_UNIFORM_BLOCK_CREATE_INFO;

    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// `decode` or `decode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        expect_structure_type(
            dec,
            "VkDescriptorPoolInlineUniformBlockCreateInfo",
            Self::STRUCTURE_TYPE,
        )?;
        dec.empty_pnext_chain("VkDescriptorPoolInlineUniformBlockCreateInfo")?;
        Self::decode_body(dec, partial)
    }

    /// `encode` or `encode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        enc.structure_type(Self::STRUCTURE_TYPE)?;
        enc.simple_pointer(false)?;
        self.encode_body(enc, partial)
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them
    /// (`vn_decode_VkDescriptorPoolInlineUniformBlockCreateInfo_self_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_body(dec: &mut Decoder<'_>, _partial: bool) -> Result<Self, ProtocolError> {
        let max_inline_uniform_block_bindings: u32 = dec.u32()?;
        Ok(Self {
            max_inline_uniform_block_bindings,
        })
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_body(&self, enc: &mut Encoder, _partial: bool) -> Result<(), ProtocolError> {
        enc.u32(self.max_inline_uniform_block_bindings)?;
        Ok(())
    }
}

/// The arguments of `vkCreateDescriptorPool`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place and sets `ret`, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct CreateDescriptorPoolArgs {
    /// `VkDevice device` — in.
    pub device: VkDevice,
    /// `const VkDescriptorPoolCreateInfo* pCreateInfo` — in.
    pub p_create_info: Option<VkDescriptorPoolCreateInfo>,
    /// `VkDescriptorPool* pDescriptorPool` — out.
    pub p_descriptor_pool: Option<VkDescriptorPool>,
    /// The return value (`VkResult`), written first in the reply.
    pub ret: VkResult,
}

impl CreateDescriptorPoolArgs {
    /// `VK_COMMAND_TYPE_vkCreateDescriptorPool_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_CREATE_DESCRIPTOR_POOL_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkCreateDescriptorPool";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkCreateDescriptorPool_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        let device: VkDevice = VkDevice(dec.handle()?);
        if device.0 == 0 {
            return Err(null_dispatch_handle(dec, "vkCreateDescriptorPool"));
        }
        let p_create_info: Option<VkDescriptorPoolCreateInfo> = if dec.simple_pointer()? {
            Some(VkDescriptorPoolCreateInfo::decode_with(dec, false)?)
        } else {
            return Err(null_pointer(dec, "vkCreateDescriptorPool", "pCreateInfo"));
        };
        dec.null_allocator()?;
        let p_descriptor_pool: Option<VkDescriptorPool> = if dec.simple_pointer()? {
            Some(VkDescriptorPool(dec.handle()?))
        } else {
            return Err(null_pointer(
                dec,
                "vkCreateDescriptorPool",
                "pDescriptorPool",
            ));
        };
        Ok(Self {
            device,
            p_create_info,
            p_descriptor_pool,
            ret: Default::default(),
        })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkCreateDescriptorPool`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.handle(self.device.0)?;
        enc.simple_pointer(self.p_create_info.is_some())?;
        if let Some(v) = &self.p_create_info {
            v.encode_with(enc, false)?;
        }
        enc.null_allocator()?;
        enc.simple_pointer(self.p_descriptor_pool.is_some())?;
        if let Some(v) = &self.p_descriptor_pool {
            enc.handle(v.0)?;
        }
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkCreateDescriptorPool_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        enc.i32(self.ret)?;
        enc.simple_pointer(self.p_descriptor_pool.is_some())?;
        if let Some(v) = &self.p_descriptor_pool {
            enc.handle(v.0)?;
        }
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkCreateDescriptorPool_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'_>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        self.ret = dec.i32()?;
        self.p_descriptor_pool = if dec.simple_pointer()? {
            Some(VkDescriptorPool(dec.handle()?))
        } else {
            None
        };
        Ok(())
    }

    /// Visit every pNext link the arguments carry, as `(parent, sType)`.
    pub fn for_each_link(&self, f: &mut dyn FnMut(&'static str, i32)) {
        if let Some(v) = &self.p_create_info {
            v.for_each_link(f);
        }
    }
}

/// The arguments of `vkDestroyDescriptorPool`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct DestroyDescriptorPoolArgs {
    /// `VkDevice device` — in.
    pub device: VkDevice,
    /// `VkDescriptorPool descriptorPool` — in.
    pub descriptor_pool: VkDescriptorPool,
}

impl DestroyDescriptorPoolArgs {
    /// `VK_COMMAND_TYPE_vkDestroyDescriptorPool_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_DESTROY_DESCRIPTOR_POOL_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkDestroyDescriptorPool";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkDestroyDescriptorPool_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        let device: VkDevice = VkDevice(dec.handle()?);
        if device.0 == 0 {
            return Err(null_dispatch_handle(dec, "vkDestroyDescriptorPool"));
        }
        let descriptor_pool: VkDescriptorPool = VkDescriptorPool(dec.handle()?);
        dec.null_allocator()?;
        Ok(Self {
            device,
            descriptor_pool,
        })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkDestroyDescriptorPool`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.handle(self.device.0)?;
        enc.handle(self.descriptor_pool.0)?;
        enc.null_allocator()?;
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkDestroyDescriptorPool_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkDestroyDescriptorPool_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'_>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        Ok(())
    }
}

/// The arguments of `vkResetDescriptorPool`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place and sets `ret`, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct ResetDescriptorPoolArgs {
    /// `VkDevice device` — in.
    pub device: VkDevice,
    /// `VkDescriptorPool descriptorPool` — in.
    pub descriptor_pool: VkDescriptorPool,
    /// `VkDescriptorPoolResetFlags flags` — in.
    pub flags: VkDescriptorPoolResetFlags,
    /// The return value (`VkResult`), written first in the reply.
    pub ret: VkResult,
}

impl ResetDescriptorPoolArgs {
    /// `VK_COMMAND_TYPE_vkResetDescriptorPool_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_RESET_DESCRIPTOR_POOL_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkResetDescriptorPool";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkResetDescriptorPool_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        let device: VkDevice = VkDevice(dec.handle()?);
        if device.0 == 0 {
            return Err(null_dispatch_handle(dec, "vkResetDescriptorPool"));
        }
        let descriptor_pool: VkDescriptorPool = VkDescriptorPool(dec.handle()?);
        let flags: VkDescriptorPoolResetFlags = dec.u32()?;
        Ok(Self {
            device,
            descriptor_pool,
            flags,
            ret: Default::default(),
        })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkResetDescriptorPool`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.handle(self.device.0)?;
        enc.handle(self.descriptor_pool.0)?;
        enc.u32(self.flags)?;
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkResetDescriptorPool_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        enc.i32(self.ret)?;
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkResetDescriptorPool_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'_>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        self.ret = dec.i32()?;
        Ok(())
    }
}
