// @generated by tools/venus-protocol/rust_protocol.py (templates/rust_group.rs)
// from venus-protocol git-70991d4c. DO NOT EDIT: regenerate with
//     python scripts/venus-gen.py

//! The `descriptor_heap` group: its commands and the structures only they reach.

#![allow(unused_imports)]

use super::*;
use crate::venus::wire::{CommandHeader, Decoder, Encoder};

/// `VkHostAddressRangeEXT`.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkHostAddressRangeEXT {
    /// `size_t size`
    pub size: u64,
    /// `void* address`
    pub address: Option<Vec<u8>>,
}

impl VkHostAddressRangeEXT {
    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Decode the skeleton an output structure is sent as inside a command
    /// (`vn_decode_VkHostAddressRangeEXT_partial_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_partial(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, true)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// Encode the skeleton form (`vn_encode_VkHostAddressRangeEXT_partial`).
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_partial(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, true)
    }

    /// `decode` or `decode_partial`.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        let size: u64 = dec.size()?;
        let address: Option<Vec<u8>> = if partial {
            array_presence(dec, size, NullArray::Checked)?.map(|_| Vec::new())
        } else {
            match array_presence(dec, size, NullArray::Checked)? {
                Some(n) => Some(decode_owned_blob(dec, n)?),
                None => None,
            }
        };
        Ok(Self { size, address })
    }

    /// `encode` or `encode_partial`.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        enc.size(self.size)?;
        if partial {
            enc.array_size(if self.address.is_some() { self.size } else { 0 })?;
        } else {
            if let Some(v) = &self.address {
                let count = self.size;
                check_len("VkHostAddressRangeEXT", "address", count, v.len())?;
                enc.array_size(count)?;
                enc.blob(v)?;
            } else {
                enc.array_size(0)?;
            }
        }
        Ok(())
    }
}

/// `VkImageDescriptorInfoEXT` (`VK_STRUCTURE_TYPE_IMAGE_DESCRIPTOR_INFO_EXT`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkImageDescriptorInfoEXT {
    /// `const VkImageViewCreateInfo* pView`
    pub p_view: Option<VkImageViewCreateInfo>,
    /// `VkImageLayout layout`
    pub layout: VkImageLayout,
}

impl VkImageDescriptorInfoEXT {
    // No output parameter reaches this structure, so it has no skeleton
    // form and the `partial` flag below is ignored.

    /// `VK_STRUCTURE_TYPE_IMAGE_DESCRIPTOR_INFO_EXT`.
    pub const STRUCTURE_TYPE: i32 = VK_STRUCTURE_TYPE_IMAGE_DESCRIPTOR_INFO_EXT;

    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// `decode` or `decode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        expect_structure_type(dec, "VkImageDescriptorInfoEXT", Self::STRUCTURE_TYPE)?;
        dec.empty_pnext_chain("VkImageDescriptorInfoEXT")?;
        Self::decode_body(dec, partial)
    }

    /// `encode` or `encode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        enc.structure_type(Self::STRUCTURE_TYPE)?;
        enc.simple_pointer(false)?;
        self.encode_body(enc, partial)
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them
    /// (`vn_decode_VkImageDescriptorInfoEXT_self_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_body(dec: &mut Decoder<'_>, _partial: bool) -> Result<Self, ProtocolError> {
        let p_view: Option<VkImageViewCreateInfo> = if dec.simple_pointer()? {
            Some(VkImageViewCreateInfo::decode_with(dec, false)?)
        } else {
            return Err(null_pointer(dec, "VkImageDescriptorInfoEXT", "pView"));
        };
        let layout: VkImageLayout = dec.i32()?;
        Ok(Self { p_view, layout })
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_body(&self, enc: &mut Encoder, _partial: bool) -> Result<(), ProtocolError> {
        enc.simple_pointer(self.p_view.is_some())?;
        if let Some(v) = &self.p_view {
            v.encode_with(enc, false)?;
        }
        enc.i32(self.layout)?;
        Ok(())
    }

    /// Visit every pNext link this structure carries — its own chain's and
    /// its members' — as `(parent, sType)`.
    pub fn for_each_link(&self, f: &mut dyn FnMut(&'static str, i32)) {
        if let Some(v) = &self.p_view {
            v.for_each_link(f);
        }
    }
}

/// `VkTexelBufferDescriptorInfoEXT` (`VK_STRUCTURE_TYPE_TEXEL_BUFFER_DESCRIPTOR_INFO_EXT`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkTexelBufferDescriptorInfoEXT {
    /// `VkFormat format`
    pub format: VkFormat,
    /// `VkDeviceAddressRangeEXT addressRange`
    pub address_range: VkDeviceAddressRangeEXT,
}

impl VkTexelBufferDescriptorInfoEXT {
    // No output parameter reaches this structure, so it has no skeleton
    // form and the `partial` flag below is ignored.

    /// `VK_STRUCTURE_TYPE_TEXEL_BUFFER_DESCRIPTOR_INFO_EXT`.
    pub const STRUCTURE_TYPE: i32 = VK_STRUCTURE_TYPE_TEXEL_BUFFER_DESCRIPTOR_INFO_EXT;

    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// `decode` or `decode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        expect_structure_type(dec, "VkTexelBufferDescriptorInfoEXT", Self::STRUCTURE_TYPE)?;
        dec.empty_pnext_chain("VkTexelBufferDescriptorInfoEXT")?;
        Self::decode_body(dec, partial)
    }

    /// `encode` or `encode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        enc.structure_type(Self::STRUCTURE_TYPE)?;
        enc.simple_pointer(false)?;
        self.encode_body(enc, partial)
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them
    /// (`vn_decode_VkTexelBufferDescriptorInfoEXT_self_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_body(dec: &mut Decoder<'_>, _partial: bool) -> Result<Self, ProtocolError> {
        let format: VkFormat = dec.i32()?;
        let address_range: VkDeviceAddressRangeEXT =
            VkDeviceAddressRangeEXT::decode_with(dec, false)?;
        Ok(Self {
            format,
            address_range,
        })
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_body(&self, enc: &mut Encoder, _partial: bool) -> Result<(), ProtocolError> {
        enc.i32(self.format)?;
        self.address_range.encode_with(enc, false)?;
        Ok(())
    }
}

/// `VkTensorViewCreateInfoARM` (`VK_STRUCTURE_TYPE_TENSOR_VIEW_CREATE_INFO_ARM`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkTensorViewCreateInfoARM {
    /// `VkTensorViewCreateFlagsARM flags`
    pub flags: VkTensorViewCreateFlagsARM,
    /// `VkTensorARM tensor`
    pub tensor: VkTensorARM,
    /// `VkFormat format`
    pub format: VkFormat,
}

impl VkTensorViewCreateInfoARM {
    // No output parameter reaches this structure, so it has no skeleton
    // form and the `partial` flag below is ignored.

    /// `VK_STRUCTURE_TYPE_TENSOR_VIEW_CREATE_INFO_ARM`.
    pub const STRUCTURE_TYPE: i32 = VK_STRUCTURE_TYPE_TENSOR_VIEW_CREATE_INFO_ARM;

    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// `decode` or `decode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        expect_structure_type(dec, "VkTensorViewCreateInfoARM", Self::STRUCTURE_TYPE)?;
        dec.empty_pnext_chain("VkTensorViewCreateInfoARM")?;
        Self::decode_body(dec, partial)
    }

    /// `encode` or `encode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        enc.structure_type(Self::STRUCTURE_TYPE)?;
        enc.simple_pointer(false)?;
        self.encode_body(enc, partial)
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them
    /// (`vn_decode_VkTensorViewCreateInfoARM_self_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_body(dec: &mut Decoder<'_>, _partial: bool) -> Result<Self, ProtocolError> {
        let flags: VkTensorViewCreateFlagsARM = dec.u64()?;
        let tensor: VkTensorARM = VkTensorARM(dec.handle()?);
        let format: VkFormat = dec.i32()?;
        Ok(Self {
            flags,
            tensor,
            format,
        })
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_body(&self, enc: &mut Encoder, _partial: bool) -> Result<(), ProtocolError> {
        enc.u64(self.flags)?;
        enc.handle(self.tensor.0)?;
        enc.i32(self.format)?;
        Ok(())
    }
}

/// `union VkResourceDescriptorDataEXT`, selected by a `VkDescriptorType` its holder carries.
///
/// One variant per member. On the wire: the tag, then the member it selects.
#[derive(Debug, Clone, PartialEq)]
pub enum VkResourceDescriptorDataEXT {
    /// `const VkImageDescriptorInfoEXT* pImage`, tag VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE, VK_DESCRIPTOR_TYPE_STORAGE_IMAGE, VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT, VK_DESCRIPTOR_TYPE_BLOCK_MATCH_IMAGE_QCOM, VK_DESCRIPTOR_TYPE_SAMPLE_WEIGHT_IMAGE_QCOM.
    PImage(Option<VkImageDescriptorInfoEXT>),
    /// `const VkTexelBufferDescriptorInfoEXT* pTexelBuffer`, tag VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER, VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER.
    PTexelBuffer(Option<VkTexelBufferDescriptorInfoEXT>),
    /// `const VkDeviceAddressRangeEXT* pAddressRange`, tag VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_KHR, VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER.
    PAddressRange(Option<VkDeviceAddressRangeEXT>),
    /// `const VkTensorViewCreateInfoARM* pTensorARM`, tag VK_DESCRIPTOR_TYPE_TENSOR_ARM.
    PTensorARM(Option<VkTensorViewCreateInfoARM>),
}

impl Default for VkResourceDescriptorDataEXT {
    fn default() -> Self {
        Self::PImage(Default::default())
    }
}

impl VkResourceDescriptorDataEXT {
    /// Decode the tag and the member it selects
    /// (`vn_decode_VkResourceDescriptorDataEXT_temp`). The tag is returned beside the value:
    /// the structure holding the union checks it against its selector.
    ///
    /// # Errors
    /// [`ProtocolError::UnknownUnionTag`], or whatever the member refused.
    pub fn decode_tagged(dec: &mut Decoder<'_>) -> Result<(VkDescriptorType, Self), ProtocolError> {
        let tag = dec.i32()?;
        let value = match tag {
            VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE
            | VK_DESCRIPTOR_TYPE_STORAGE_IMAGE
            | VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT
            | VK_DESCRIPTOR_TYPE_BLOCK_MATCH_IMAGE_QCOM
            | VK_DESCRIPTOR_TYPE_SAMPLE_WEIGHT_IMAGE_QCOM => {
                Self::PImage(if dec.simple_pointer()? {
                    Some(VkImageDescriptorInfoEXT::decode_with(dec, false)?)
                } else {
                    None
                })
            }
            VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER | VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER => {
                Self::PTexelBuffer(if dec.simple_pointer()? {
                    Some(VkTexelBufferDescriptorInfoEXT::decode_with(dec, false)?)
                } else {
                    None
                })
            }
            VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_KHR
            | VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER
            | VK_DESCRIPTOR_TYPE_STORAGE_BUFFER => Self::PAddressRange(if dec.simple_pointer()? {
                Some(VkDeviceAddressRangeEXT::decode_with(dec, false)?)
            } else {
                None
            }),
            VK_DESCRIPTOR_TYPE_TENSOR_ARM => Self::PTensorARM(if dec.simple_pointer()? {
                Some(VkTensorViewCreateInfoARM::decode_with(dec, false)?)
            } else {
                None
            }),
            _ => {
                return Err(unknown_union_tag(
                    dec,
                    "VkResourceDescriptorDataEXT",
                    i64::from(tag),
                ))
            }
        };
        Ok((tag, value))
    }

    /// Encode `tag` — the holder's selector — and the member it selects
    /// (`vn_encode_VkResourceDescriptorDataEXT(enc, val, tag)`).
    ///
    /// # Errors
    /// [`ProtocolError::UnionTagMismatch`] when `tag` selects a member this
    /// value does not hold, or whatever the encoder refused.
    pub fn encode_tagged(
        &self,
        enc: &mut Encoder,
        tag: VkDescriptorType,
    ) -> Result<(), ProtocolError> {
        match (tag, self) {
            (
                VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE
                | VK_DESCRIPTOR_TYPE_STORAGE_IMAGE
                | VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT
                | VK_DESCRIPTOR_TYPE_BLOCK_MATCH_IMAGE_QCOM
                | VK_DESCRIPTOR_TYPE_SAMPLE_WEIGHT_IMAGE_QCOM,
                Self::PImage(value),
            ) => {
                enc.i32(tag)?;
                enc.simple_pointer(value.is_some())?;
                if let Some(v) = value {
                    v.encode_with(enc, false)?;
                }
            }
            (
                VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER | VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER,
                Self::PTexelBuffer(value),
            ) => {
                enc.i32(tag)?;
                enc.simple_pointer(value.is_some())?;
                if let Some(v) = value {
                    v.encode_with(enc, false)?;
                }
            }
            (
                VK_DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_KHR
                | VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER
                | VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
                Self::PAddressRange(value),
            ) => {
                enc.i32(tag)?;
                enc.simple_pointer(value.is_some())?;
                if let Some(v) = value {
                    v.encode_with(enc, false)?;
                }
            }
            (VK_DESCRIPTOR_TYPE_TENSOR_ARM, Self::PTensorARM(value)) => {
                enc.i32(tag)?;
                enc.simple_pointer(value.is_some())?;
                if let Some(v) = value {
                    v.encode_with(enc, false)?;
                }
            }
            _ => {
                return Err(ProtocolError::UnionTagMismatch {
                    union: "VkResourceDescriptorDataEXT",
                    tag: i64::from(tag),
                })
            }
        }
        Ok(())
    }

    /// Visit every pNext link the member held carries, as `(parent, sType)`.
    pub fn for_each_link(&self, f: &mut dyn FnMut(&'static str, i32)) {
        if let Self::PImage(Some(value)) = self {
            value.for_each_link(f);
        }
    }
}

/// `VkResourceDescriptorInfoEXT` (`VK_STRUCTURE_TYPE_RESOURCE_DESCRIPTOR_INFO_EXT`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkResourceDescriptorInfoEXT {
    /// `VkDescriptorType type`
    pub type_: VkDescriptorType,
    /// `VkResourceDescriptorDataEXT data`
    pub data: VkResourceDescriptorDataEXT,
}

impl VkResourceDescriptorInfoEXT {
    // No output parameter reaches this structure, so it has no skeleton
    // form and the `partial` flag below is ignored.

    /// `VK_STRUCTURE_TYPE_RESOURCE_DESCRIPTOR_INFO_EXT`.
    pub const STRUCTURE_TYPE: i32 = VK_STRUCTURE_TYPE_RESOURCE_DESCRIPTOR_INFO_EXT;

    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// `decode` or `decode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        expect_structure_type(dec, "VkResourceDescriptorInfoEXT", Self::STRUCTURE_TYPE)?;
        dec.empty_pnext_chain("VkResourceDescriptorInfoEXT")?;
        Self::decode_body(dec, partial)
    }

    /// `encode` or `encode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        enc.structure_type(Self::STRUCTURE_TYPE)?;
        enc.simple_pointer(false)?;
        self.encode_body(enc, partial)
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them
    /// (`vn_decode_VkResourceDescriptorInfoEXT_self_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_body(dec: &mut Decoder<'_>, _partial: bool) -> Result<Self, ProtocolError> {
        let type_: VkDescriptorType = dec.i32()?;
        let (data_tag, data): (VkDescriptorType, VkResourceDescriptorDataEXT) =
            VkResourceDescriptorDataEXT::decode_tagged(dec)?;
        check_union_tag(
            dec,
            "VkResourceDescriptorInfoEXT",
            "data",
            i64::from(data_tag),
            i64::from(type_),
        )?;
        Ok(Self { type_, data })
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_body(&self, enc: &mut Encoder, _partial: bool) -> Result<(), ProtocolError> {
        enc.i32(self.type_)?;
        self.data.encode_tagged(enc, self.type_)?;
        Ok(())
    }

    /// Visit every pNext link this structure carries — its own chain's and
    /// its members' — as `(parent, sType)`.
    pub fn for_each_link(&self, f: &mut dyn FnMut(&'static str, i32)) {
        self.data.for_each_link(f);
    }
}

/// The arguments of `vkRegisterCustomBorderColorEXT`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place and sets `ret`, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct RegisterCustomBorderColorEXTArgs {
    /// `VkDevice device` — in.
    pub device: VkDevice,
    /// `const VkSamplerCustomBorderColorCreateInfoEXT* pBorderColor` — in.
    pub p_border_color: Option<VkSamplerCustomBorderColorCreateInfoEXT>,
    /// `VkBool32 requestIndex` — in.
    pub request_index: VkBool32,
    /// `uint32_t* pIndex` — in/out.
    pub p_index: Option<u32>,
    /// The return value (`VkResult`), written first in the reply.
    pub ret: VkResult,
}

impl RegisterCustomBorderColorEXTArgs {
    /// `VK_COMMAND_TYPE_vkRegisterCustomBorderColorEXT_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_REGISTER_CUSTOM_BORDER_COLOR_EXT_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkRegisterCustomBorderColorEXT";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkRegisterCustomBorderColorEXT_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        let device: VkDevice = VkDevice(dec.handle()?);
        if device.0 == 0 {
            return Err(null_dispatch_handle(dec, "vkRegisterCustomBorderColorEXT"));
        }
        let p_border_color: Option<VkSamplerCustomBorderColorCreateInfoEXT> =
            if dec.simple_pointer()? {
                Some(VkSamplerCustomBorderColorCreateInfoEXT::decode_with(
                    dec, false,
                )?)
            } else {
                return Err(null_pointer(
                    dec,
                    "vkRegisterCustomBorderColorEXT",
                    "pBorderColor",
                ));
            };
        let request_index: VkBool32 = dec.u32()?;
        let p_index: Option<u32> = if dec.simple_pointer()? {
            Some(dec.u32()?)
        } else {
            return Err(null_pointer(
                dec,
                "vkRegisterCustomBorderColorEXT",
                "pIndex",
            ));
        };
        Ok(Self {
            device,
            p_border_color,
            request_index,
            p_index,
            ret: Default::default(),
        })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkRegisterCustomBorderColorEXT`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.handle(self.device.0)?;
        enc.simple_pointer(self.p_border_color.is_some())?;
        if let Some(v) = &self.p_border_color {
            v.encode_with(enc, false)?;
        }
        enc.u32(self.request_index)?;
        enc.simple_pointer(self.p_index.is_some())?;
        if let Some(v) = &self.p_index {
            enc.u32(*v)?;
        }
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkRegisterCustomBorderColorEXT_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        enc.i32(self.ret)?;
        enc.simple_pointer(self.p_index.is_some())?;
        if let Some(v) = &self.p_index {
            enc.u32(*v)?;
        }
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkRegisterCustomBorderColorEXT_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'_>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        self.ret = dec.i32()?;
        self.p_index = if dec.simple_pointer()? {
            Some(dec.u32()?)
        } else {
            None
        };
        Ok(())
    }
}

/// The arguments of `vkUnregisterCustomBorderColorEXT`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct UnregisterCustomBorderColorEXTArgs {
    /// `VkDevice device` — in.
    pub device: VkDevice,
    /// `uint32_t index` — in.
    pub index: u32,
}

impl UnregisterCustomBorderColorEXTArgs {
    /// `VK_COMMAND_TYPE_vkUnregisterCustomBorderColorEXT_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_UNREGISTER_CUSTOM_BORDER_COLOR_EXT_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkUnregisterCustomBorderColorEXT";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkUnregisterCustomBorderColorEXT_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        let device: VkDevice = VkDevice(dec.handle()?);
        if device.0 == 0 {
            return Err(null_dispatch_handle(
                dec,
                "vkUnregisterCustomBorderColorEXT",
            ));
        }
        let index: u32 = dec.u32()?;
        Ok(Self { device, index })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkUnregisterCustomBorderColorEXT`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.handle(self.device.0)?;
        enc.u32(self.index)?;
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkUnregisterCustomBorderColorEXT_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkUnregisterCustomBorderColorEXT_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'_>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        Ok(())
    }
}

/// The arguments of `vkGetImageOpaqueCaptureDataEXT`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place and sets `ret`, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct GetImageOpaqueCaptureDataEXTArgs {
    /// `VkDevice device` — in.
    pub device: VkDevice,
    /// `uint32_t imageCount` — in.
    pub image_count: u32,
    /// `const VkImage* pImages` — in.
    pub p_images: Option<Vec<VkImage>>,
    /// `VkHostAddressRangeEXT* pDatas` — out.
    pub p_datas: Option<Vec<VkHostAddressRangeEXT>>,
    /// The return value (`VkResult`), written first in the reply.
    pub ret: VkResult,
}

impl GetImageOpaqueCaptureDataEXTArgs {
    /// `VK_COMMAND_TYPE_vkGetImageOpaqueCaptureDataEXT_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_GET_IMAGE_OPAQUE_CAPTURE_DATA_EXT_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkGetImageOpaqueCaptureDataEXT";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkGetImageOpaqueCaptureDataEXT_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        let device: VkDevice = VkDevice(dec.handle()?);
        if device.0 == 0 {
            return Err(null_dispatch_handle(dec, "vkGetImageOpaqueCaptureDataEXT"));
        }
        let image_count: u32 = dec.u32()?;
        let p_images: Option<Vec<VkImage>> =
            match array_presence(dec, u64::from(image_count), NullArray::Checked)? {
                Some(n) => Some(decode_vec(dec, n, |dec| {
                    dec.handle().map(VkImage).map_err(ProtocolError::from)
                })?),
                None => None,
            };
        let p_datas: Option<Vec<VkHostAddressRangeEXT>> =
            match array_presence(dec, u64::from(image_count), NullArray::Checked)? {
                Some(n) => Some(decode_vec(dec, n, |dec| {
                    VkHostAddressRangeEXT::decode_with(dec, true)
                })?),
                None => None,
            };
        Ok(Self {
            device,
            image_count,
            p_images,
            p_datas,
            ret: Default::default(),
        })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkGetImageOpaqueCaptureDataEXT`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.handle(self.device.0)?;
        enc.u32(self.image_count)?;
        if let Some(v) = &self.p_images {
            let count = u64::from(self.image_count);
            check_len("vkGetImageOpaqueCaptureDataEXT", "pImages", count, v.len())?;
            enc.array_size(count)?;
            for e in v {
                enc.handle(e.0)?;
            }
        } else {
            enc.array_size(0)?;
        }
        if let Some(v) = &self.p_datas {
            let count = u64::from(self.image_count);
            check_len("vkGetImageOpaqueCaptureDataEXT", "pDatas", count, v.len())?;
            enc.array_size(count)?;
            for e in v {
                e.encode_with(enc, true)?;
            }
        } else {
            enc.array_size(0)?;
        }
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkGetImageOpaqueCaptureDataEXT_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        enc.i32(self.ret)?;
        if let Some(v) = &self.p_datas {
            let count = u64::from(self.image_count);
            check_len("vkGetImageOpaqueCaptureDataEXT", "pDatas", count, v.len())?;
            enc.array_size(count)?;
            for e in v {
                e.encode_with(enc, false)?;
            }
        } else {
            enc.array_size(0)?;
        }
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkGetImageOpaqueCaptureDataEXT_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'_>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        self.ret = dec.i32()?;
        self.p_datas = match array_presence(dec, u64::from(self.image_count), NullArray::Unchecked)?
        {
            Some(n) => Some(decode_vec(dec, n, |dec| {
                VkHostAddressRangeEXT::decode_with(dec, false)
            })?),
            None => None,
        };
        Ok(())
    }
}

/// The arguments of `vkWriteSamplerDescriptorMESA`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place and sets `ret`, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct WriteSamplerDescriptorMESAArgs {
    /// `VkDevice device` — in.
    pub device: VkDevice,
    /// `const VkSamplerCreateInfo* pSampler` — in.
    pub p_sampler: Option<VkSamplerCreateInfo>,
    /// `size_t dataSize` — in.
    pub data_size: u64,
    /// `void* pData` — out.
    pub p_data: Option<Vec<u8>>,
    /// The return value (`VkResult`), written first in the reply.
    pub ret: VkResult,
}

impl WriteSamplerDescriptorMESAArgs {
    /// `VK_COMMAND_TYPE_vkWriteSamplerDescriptorMESA_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_WRITE_SAMPLER_DESCRIPTOR_MESA_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkWriteSamplerDescriptorMESA";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkWriteSamplerDescriptorMESA_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        let device: VkDevice = VkDevice(dec.handle()?);
        if device.0 == 0 {
            return Err(null_dispatch_handle(dec, "vkWriteSamplerDescriptorMESA"));
        }
        let p_sampler: Option<VkSamplerCreateInfo> = if dec.simple_pointer()? {
            Some(VkSamplerCreateInfo::decode_with(dec, false)?)
        } else {
            return Err(null_pointer(
                dec,
                "vkWriteSamplerDescriptorMESA",
                "pSampler",
            ));
        };
        let data_size: u64 = dec.size()?;
        let p_data: Option<Vec<u8>> =
            array_presence(dec, data_size, NullArray::Checked)?.map(|_| Vec::new());
        Ok(Self {
            device,
            p_sampler,
            data_size,
            p_data,
            ret: Default::default(),
        })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkWriteSamplerDescriptorMESA`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.handle(self.device.0)?;
        enc.simple_pointer(self.p_sampler.is_some())?;
        if let Some(v) = &self.p_sampler {
            v.encode_with(enc, false)?;
        }
        enc.size(self.data_size)?;
        enc.array_size(if self.p_data.is_some() {
            self.data_size
        } else {
            0
        })?;
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkWriteSamplerDescriptorMESA_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        enc.i32(self.ret)?;
        if let Some(v) = &self.p_data {
            let count = self.data_size;
            check_len("vkWriteSamplerDescriptorMESA", "pData", count, v.len())?;
            enc.array_size(count)?;
            enc.blob(v)?;
        } else {
            enc.array_size(0)?;
        }
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkWriteSamplerDescriptorMESA_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'_>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        self.ret = dec.i32()?;
        self.p_data = match array_presence(dec, self.data_size, NullArray::Unchecked)? {
            Some(n) => Some(decode_owned_blob(dec, n)?),
            None => None,
        };
        Ok(())
    }

    /// Visit every pNext link the arguments carry, as `(parent, sType)`.
    pub fn for_each_link(&self, f: &mut dyn FnMut(&'static str, i32)) {
        if let Some(v) = &self.p_sampler {
            v.for_each_link(f);
        }
    }
}

/// The arguments of `vkWriteResourceDescriptorMESA`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place and sets `ret`, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct WriteResourceDescriptorMESAArgs {
    /// `VkDevice device` — in.
    pub device: VkDevice,
    /// `const VkResourceDescriptorInfoEXT* pResource` — in.
    pub p_resource: Option<VkResourceDescriptorInfoEXT>,
    /// `size_t dataSize` — in.
    pub data_size: u64,
    /// `void* pData` — out.
    pub p_data: Option<Vec<u8>>,
    /// The return value (`VkResult`), written first in the reply.
    pub ret: VkResult,
}

impl WriteResourceDescriptorMESAArgs {
    /// `VK_COMMAND_TYPE_vkWriteResourceDescriptorMESA_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_WRITE_RESOURCE_DESCRIPTOR_MESA_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkWriteResourceDescriptorMESA";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkWriteResourceDescriptorMESA_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        let device: VkDevice = VkDevice(dec.handle()?);
        if device.0 == 0 {
            return Err(null_dispatch_handle(dec, "vkWriteResourceDescriptorMESA"));
        }
        let p_resource: Option<VkResourceDescriptorInfoEXT> = if dec.simple_pointer()? {
            Some(VkResourceDescriptorInfoEXT::decode_with(dec, false)?)
        } else {
            return Err(null_pointer(
                dec,
                "vkWriteResourceDescriptorMESA",
                "pResource",
            ));
        };
        let data_size: u64 = dec.size()?;
        let p_data: Option<Vec<u8>> =
            array_presence(dec, data_size, NullArray::Checked)?.map(|_| Vec::new());
        Ok(Self {
            device,
            p_resource,
            data_size,
            p_data,
            ret: Default::default(),
        })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkWriteResourceDescriptorMESA`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.handle(self.device.0)?;
        enc.simple_pointer(self.p_resource.is_some())?;
        if let Some(v) = &self.p_resource {
            v.encode_with(enc, false)?;
        }
        enc.size(self.data_size)?;
        enc.array_size(if self.p_data.is_some() {
            self.data_size
        } else {
            0
        })?;
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkWriteResourceDescriptorMESA_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        enc.i32(self.ret)?;
        if let Some(v) = &self.p_data {
            let count = self.data_size;
            check_len("vkWriteResourceDescriptorMESA", "pData", count, v.len())?;
            enc.array_size(count)?;
            enc.blob(v)?;
        } else {
            enc.array_size(0)?;
        }
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkWriteResourceDescriptorMESA_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'_>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        self.ret = dec.i32()?;
        self.p_data = match array_presence(dec, self.data_size, NullArray::Unchecked)? {
            Some(n) => Some(decode_owned_blob(dec, n)?),
            None => None,
        };
        Ok(())
    }

    /// Visit every pNext link the arguments carry, as `(parent, sType)`.
    pub fn for_each_link(&self, f: &mut dyn FnMut(&'static str, i32)) {
        if let Some(v) = &self.p_resource {
            v.for_each_link(f);
        }
    }
}
