// @generated by tools/venus-protocol/rust_protocol.py (templates/rust_group.rs)
// from venus-protocol git-70991d4c. DO NOT EDIT: regenerate with
//     python scripts/venus-gen.py

//! The `descriptor_update_template` group: its commands and the structures only they reach.

#![allow(unused_imports)]

use super::*;
use crate::venus::wire::{CommandHeader, Decoder, Encoder};

/// `VkDescriptorUpdateTemplateEntry`.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkDescriptorUpdateTemplateEntry {
    /// `uint32_t dstBinding`
    pub dst_binding: u32,
    /// `uint32_t dstArrayElement`
    pub dst_array_element: u32,
    /// `uint32_t descriptorCount`
    pub descriptor_count: u32,
    /// `VkDescriptorType descriptorType`
    pub descriptor_type: VkDescriptorType,
    /// `size_t offset`
    pub offset: u64,
    /// `size_t stride`
    pub stride: u64,
}

impl VkDescriptorUpdateTemplateEntry {
    // No output parameter reaches this structure, so it has no skeleton
    // form and the `partial` flag below is ignored.

    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// `decode` or `decode_partial`.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'_>, _partial: bool) -> Result<Self, ProtocolError> {
        let dst_binding: u32 = dec.u32()?;
        let dst_array_element: u32 = dec.u32()?;
        let descriptor_count: u32 = dec.u32()?;
        let descriptor_type: VkDescriptorType = dec.i32()?;
        let offset: u64 = dec.size()?;
        let stride: u64 = dec.size()?;
        Ok(Self {
            dst_binding,
            dst_array_element,
            descriptor_count,
            descriptor_type,
            offset,
            stride,
        })
    }

    /// `encode` or `encode_partial`.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, _partial: bool) -> Result<(), ProtocolError> {
        enc.u32(self.dst_binding)?;
        enc.u32(self.dst_array_element)?;
        enc.u32(self.descriptor_count)?;
        enc.i32(self.descriptor_type)?;
        enc.size(self.offset)?;
        enc.size(self.stride)?;
        Ok(())
    }
}

/// `VkDescriptorUpdateTemplateCreateInfo` (`VK_STRUCTURE_TYPE_DESCRIPTOR_UPDATE_TEMPLATE_CREATE_INFO`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkDescriptorUpdateTemplateCreateInfo {
    /// `VkDescriptorUpdateTemplateCreateFlags flags`
    pub flags: VkDescriptorUpdateTemplateCreateFlags,
    /// `uint32_t descriptorUpdateEntryCount`
    pub descriptor_update_entry_count: u32,
    /// `const VkDescriptorUpdateTemplateEntry* pDescriptorUpdateEntries`
    pub p_descriptor_update_entries: Option<Vec<VkDescriptorUpdateTemplateEntry>>,
    /// `VkDescriptorUpdateTemplateType templateType`
    pub template_type: VkDescriptorUpdateTemplateType,
    /// `VkDescriptorSetLayout descriptorSetLayout`
    pub descriptor_set_layout: VkDescriptorSetLayout,
    /// `VkPipelineBindPoint pipelineBindPoint`
    pub pipeline_bind_point: VkPipelineBindPoint,
    /// `VkPipelineLayout pipelineLayout`
    pub pipeline_layout: VkPipelineLayout,
    /// `uint32_t set`
    pub set: u32,
}

impl VkDescriptorUpdateTemplateCreateInfo {
    // No output parameter reaches this structure, so it has no skeleton
    // form and the `partial` flag below is ignored.

    /// `VK_STRUCTURE_TYPE_DESCRIPTOR_UPDATE_TEMPLATE_CREATE_INFO`.
    pub const STRUCTURE_TYPE: i32 = VK_STRUCTURE_TYPE_DESCRIPTOR_UPDATE_TEMPLATE_CREATE_INFO;

    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// `decode` or `decode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        expect_structure_type(
            dec,
            "VkDescriptorUpdateTemplateCreateInfo",
            Self::STRUCTURE_TYPE,
        )?;
        dec.empty_pnext_chain("VkDescriptorUpdateTemplateCreateInfo")?;
        Self::decode_body(dec, partial)
    }

    /// `encode` or `encode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        enc.structure_type(Self::STRUCTURE_TYPE)?;
        enc.simple_pointer(false)?;
        self.encode_body(enc, partial)
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them
    /// (`vn_decode_VkDescriptorUpdateTemplateCreateInfo_self_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_body(dec: &mut Decoder<'_>, _partial: bool) -> Result<Self, ProtocolError> {
        let flags: VkDescriptorUpdateTemplateCreateFlags = dec.u32()?;
        let descriptor_update_entry_count: u32 = dec.u32()?;
        let p_descriptor_update_entries: Option<Vec<VkDescriptorUpdateTemplateEntry>> =
            match array_presence(
                dec,
                u64::from(descriptor_update_entry_count),
                NullArray::Checked,
            )? {
                Some(n) => Some(decode_vec(dec, n, |dec| {
                    VkDescriptorUpdateTemplateEntry::decode_with(dec, false)
                })?),
                None => None,
            };
        let template_type: VkDescriptorUpdateTemplateType = dec.i32()?;
        let descriptor_set_layout: VkDescriptorSetLayout = VkDescriptorSetLayout(dec.handle()?);
        let pipeline_bind_point: VkPipelineBindPoint = dec.i32()?;
        let pipeline_layout: VkPipelineLayout = VkPipelineLayout(dec.handle()?);
        let set: u32 = dec.u32()?;
        Ok(Self {
            flags,
            descriptor_update_entry_count,
            p_descriptor_update_entries,
            template_type,
            descriptor_set_layout,
            pipeline_bind_point,
            pipeline_layout,
            set,
        })
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_body(&self, enc: &mut Encoder, _partial: bool) -> Result<(), ProtocolError> {
        enc.u32(self.flags)?;
        enc.u32(self.descriptor_update_entry_count)?;
        if let Some(v) = &self.p_descriptor_update_entries {
            let count = u64::from(self.descriptor_update_entry_count);
            check_len(
                "VkDescriptorUpdateTemplateCreateInfo",
                "pDescriptorUpdateEntries",
                count,
                v.len(),
            )?;
            enc.array_size(count)?;
            for e in v {
                e.encode_with(enc, false)?;
            }
        } else {
            enc.array_size(0)?;
        }
        enc.i32(self.template_type)?;
        enc.handle(self.descriptor_set_layout.0)?;
        enc.i32(self.pipeline_bind_point)?;
        enc.handle(self.pipeline_layout.0)?;
        enc.u32(self.set)?;
        Ok(())
    }
}

/// The arguments of `vkCreateDescriptorUpdateTemplate`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place and sets `ret`, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct CreateDescriptorUpdateTemplateArgs {
    /// `VkDevice device` — in.
    pub device: VkDevice,
    /// `const VkDescriptorUpdateTemplateCreateInfo* pCreateInfo` — in.
    pub p_create_info: Option<VkDescriptorUpdateTemplateCreateInfo>,
    /// `VkDescriptorUpdateTemplate* pDescriptorUpdateTemplate` — out.
    pub p_descriptor_update_template: Option<VkDescriptorUpdateTemplate>,
    /// The return value (`VkResult`), written first in the reply.
    pub ret: VkResult,
}

impl CreateDescriptorUpdateTemplateArgs {
    /// `VK_COMMAND_TYPE_vkCreateDescriptorUpdateTemplate_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_CREATE_DESCRIPTOR_UPDATE_TEMPLATE_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkCreateDescriptorUpdateTemplate";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkCreateDescriptorUpdateTemplate_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        let device: VkDevice = VkDevice(dec.handle()?);
        if device.0 == 0 {
            return Err(null_dispatch_handle(
                dec,
                "vkCreateDescriptorUpdateTemplate",
            ));
        }
        let p_create_info: Option<VkDescriptorUpdateTemplateCreateInfo> = if dec.simple_pointer()? {
            Some(VkDescriptorUpdateTemplateCreateInfo::decode_with(
                dec, false,
            )?)
        } else {
            return Err(null_pointer(
                dec,
                "vkCreateDescriptorUpdateTemplate",
                "pCreateInfo",
            ));
        };
        dec.null_allocator()?;
        let p_descriptor_update_template: Option<VkDescriptorUpdateTemplate> =
            if dec.simple_pointer()? {
                Some(VkDescriptorUpdateTemplate(dec.handle()?))
            } else {
                return Err(null_pointer(
                    dec,
                    "vkCreateDescriptorUpdateTemplate",
                    "pDescriptorUpdateTemplate",
                ));
            };
        Ok(Self {
            device,
            p_create_info,
            p_descriptor_update_template,
            ret: Default::default(),
        })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkCreateDescriptorUpdateTemplate`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.handle(self.device.0)?;
        enc.simple_pointer(self.p_create_info.is_some())?;
        if let Some(v) = &self.p_create_info {
            v.encode_with(enc, false)?;
        }
        enc.null_allocator()?;
        enc.simple_pointer(self.p_descriptor_update_template.is_some())?;
        if let Some(v) = &self.p_descriptor_update_template {
            enc.handle(v.0)?;
        }
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkCreateDescriptorUpdateTemplate_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        enc.i32(self.ret)?;
        enc.simple_pointer(self.p_descriptor_update_template.is_some())?;
        if let Some(v) = &self.p_descriptor_update_template {
            enc.handle(v.0)?;
        }
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkCreateDescriptorUpdateTemplate_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'_>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        self.ret = dec.i32()?;
        self.p_descriptor_update_template = if dec.simple_pointer()? {
            Some(VkDescriptorUpdateTemplate(dec.handle()?))
        } else {
            None
        };
        Ok(())
    }
}

/// The arguments of `vkDestroyDescriptorUpdateTemplate`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct DestroyDescriptorUpdateTemplateArgs {
    /// `VkDevice device` — in.
    pub device: VkDevice,
    /// `VkDescriptorUpdateTemplate descriptorUpdateTemplate` — in.
    pub descriptor_update_template: VkDescriptorUpdateTemplate,
}

impl DestroyDescriptorUpdateTemplateArgs {
    /// `VK_COMMAND_TYPE_vkDestroyDescriptorUpdateTemplate_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_DESTROY_DESCRIPTOR_UPDATE_TEMPLATE_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkDestroyDescriptorUpdateTemplate";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkDestroyDescriptorUpdateTemplate_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        let device: VkDevice = VkDevice(dec.handle()?);
        if device.0 == 0 {
            return Err(null_dispatch_handle(
                dec,
                "vkDestroyDescriptorUpdateTemplate",
            ));
        }
        let descriptor_update_template: VkDescriptorUpdateTemplate =
            VkDescriptorUpdateTemplate(dec.handle()?);
        dec.null_allocator()?;
        Ok(Self {
            device,
            descriptor_update_template,
        })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkDestroyDescriptorUpdateTemplate`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.handle(self.device.0)?;
        enc.handle(self.descriptor_update_template.0)?;
        enc.null_allocator()?;
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkDestroyDescriptorUpdateTemplate_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkDestroyDescriptorUpdateTemplate_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'_>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        Ok(())
    }
}
