// @generated by tools/venus-protocol/rust_protocol.py (templates/rust_group.rs)
// from venus-protocol git-70991d4c. DO NOT EDIT: regenerate with
//     python scripts/venus-gen.py

//! The `framebuffer` group: its commands and the structures only they reach.

#![allow(unused_imports)]

use super::*;
use crate::venus::wire::{CommandHeader, Decoder, Encoder};

/// `VkFramebufferCreateInfo` (`VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkFramebufferCreateInfo {
    /// The pNext chain, in the guest's order. Admits: `VkFramebufferAttachmentsCreateInfo`.
    pub p_next: Vec<VkFramebufferCreateInfoNext>,
    /// `VkFramebufferCreateFlags flags`
    pub flags: VkFramebufferCreateFlags,
    /// `VkRenderPass renderPass`
    pub render_pass: VkRenderPass,
    /// `uint32_t attachmentCount`
    pub attachment_count: u32,
    /// `const VkImageView* pAttachments`
    pub p_attachments: Option<Vec<VkImageView>>,
    /// `uint32_t width`
    pub width: u32,
    /// `uint32_t height`
    pub height: u32,
    /// `uint32_t layers`
    pub layers: u32,
}

impl VkFramebufferCreateInfo {
    // No output parameter reaches this structure, so it has no skeleton
    // form and the `partial` flag below is ignored.

    /// `VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO`.
    pub const STRUCTURE_TYPE: i32 = VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO;

    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// `decode` or `decode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        expect_structure_type(dec, "VkFramebufferCreateInfo", Self::STRUCTURE_TYPE)?;
        let p_next = decode_chain::<VkFramebufferCreateInfoNext>(dec, partial)?;
        let mut value = Self::decode_body(dec, partial)?;
        value.p_next = p_next;
        Ok(value)
    }

    /// `encode` or `encode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        enc.structure_type(Self::STRUCTURE_TYPE)?;
        encode_chain(enc, &self.p_next, partial)?;
        self.encode_body(enc, partial)
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them
    /// (`vn_decode_VkFramebufferCreateInfo_self_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_body(dec: &mut Decoder<'_>, _partial: bool) -> Result<Self, ProtocolError> {
        let flags: VkFramebufferCreateFlags = dec.u32()?;
        let render_pass: VkRenderPass = VkRenderPass(dec.handle()?);
        let attachment_count: u32 = dec.u32()?;
        let p_attachments: Option<Vec<VkImageView>> =
            match array_presence(dec, u64::from(attachment_count), NullArray::Unchecked)? {
                Some(n) => Some(decode_vec(dec, n, |dec| {
                    dec.handle().map(VkImageView).map_err(ProtocolError::from)
                })?),
                None => None,
            };
        let width: u32 = dec.u32()?;
        let height: u32 = dec.u32()?;
        let layers: u32 = dec.u32()?;
        Ok(Self {
            p_next: Vec::new(),
            flags,
            render_pass,
            attachment_count,
            p_attachments,
            width,
            height,
            layers,
        })
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_body(&self, enc: &mut Encoder, _partial: bool) -> Result<(), ProtocolError> {
        enc.u32(self.flags)?;
        enc.handle(self.render_pass.0)?;
        enc.u32(self.attachment_count)?;
        if self.flags & VK_FRAMEBUFFER_CREATE_IMAGELESS_BIT == 0 {
            let v = self.p_attachments.as_deref().unwrap_or_default();
            let count = u64::from(self.attachment_count);
            check_len("VkFramebufferCreateInfo", "pAttachments", count, v.len())?;
            enc.array_size(count)?;
            for e in v {
                enc.handle(e.0)?;
            }
        } else {
            enc.array_size(0)?;
        }
        enc.u32(self.width)?;
        enc.u32(self.height)?;
        enc.u32(self.layers)?;
        Ok(())
    }

    /// Visit every pNext link this structure carries — its own chain's and
    /// its members' — as `(parent, sType)`.
    pub fn for_each_link(&self, f: &mut dyn FnMut(&'static str, i32)) {
        for link in &self.p_next {
            f("VkFramebufferCreateInfo", link.structure_type());
        }
    }
}

/// A link of `VkFramebufferCreateInfo`'s pNext chain.
#[derive(Debug, Clone, PartialEq)]
pub enum VkFramebufferCreateInfoNext {
    /// `VK_STRUCTURE_TYPE_FRAMEBUFFER_ATTACHMENTS_CREATE_INFO`.
    VkFramebufferAttachmentsCreateInfo(VkFramebufferAttachmentsCreateInfo),
}

impl<'a> ChainLink<'a> for VkFramebufferCreateInfoNext {
    const PARENT: &'static str = "VkFramebufferCreateInfo";

    fn structure_type(&self) -> i32 {
        match self {
            Self::VkFramebufferAttachmentsCreateInfo(_) => {
                VK_STRUCTURE_TYPE_FRAMEBUFFER_ATTACHMENTS_CREATE_INFO
            }
        }
    }

    fn decode_body(
        stype: i32,
        dec: &mut Decoder<'a>,
        partial: bool,
    ) -> Option<Result<Self, ProtocolError>> {
        Some(match stype {
            VK_STRUCTURE_TYPE_FRAMEBUFFER_ATTACHMENTS_CREATE_INFO => {
                VkFramebufferAttachmentsCreateInfo::decode_body(dec, partial)
                    .map(Self::VkFramebufferAttachmentsCreateInfo)
            }
            _ => return None,
        })
    }

    fn encode_body(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        match self {
            Self::VkFramebufferAttachmentsCreateInfo(link) => link.encode_body(enc, partial),
        }
    }
}

/// `VkFramebufferAttachmentImageInfo` (`VK_STRUCTURE_TYPE_FRAMEBUFFER_ATTACHMENT_IMAGE_INFO`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkFramebufferAttachmentImageInfo {
    /// `VkImageCreateFlags flags`
    pub flags: VkImageCreateFlags,
    /// `VkImageUsageFlags usage`
    pub usage: VkImageUsageFlags,
    /// `uint32_t width`
    pub width: u32,
    /// `uint32_t height`
    pub height: u32,
    /// `uint32_t layerCount`
    pub layer_count: u32,
    /// `uint32_t viewFormatCount`
    pub view_format_count: u32,
    /// `const VkFormat* pViewFormats`
    pub p_view_formats: Option<Vec<VkFormat>>,
}

impl VkFramebufferAttachmentImageInfo {
    // No output parameter reaches this structure, so it has no skeleton
    // form and the `partial` flag below is ignored.

    /// `VK_STRUCTURE_TYPE_FRAMEBUFFER_ATTACHMENT_IMAGE_INFO`.
    pub const STRUCTURE_TYPE: i32 = VK_STRUCTURE_TYPE_FRAMEBUFFER_ATTACHMENT_IMAGE_INFO;

    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// `decode` or `decode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        expect_structure_type(
            dec,
            "VkFramebufferAttachmentImageInfo",
            Self::STRUCTURE_TYPE,
        )?;
        dec.empty_pnext_chain("VkFramebufferAttachmentImageInfo")?;
        Self::decode_body(dec, partial)
    }

    /// `encode` or `encode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        enc.structure_type(Self::STRUCTURE_TYPE)?;
        enc.simple_pointer(false)?;
        self.encode_body(enc, partial)
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them
    /// (`vn_decode_VkFramebufferAttachmentImageInfo_self_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_body(dec: &mut Decoder<'_>, _partial: bool) -> Result<Self, ProtocolError> {
        let flags: VkImageCreateFlags = dec.u32()?;
        let usage: VkImageUsageFlags = dec.u32()?;
        let width: u32 = dec.u32()?;
        let height: u32 = dec.u32()?;
        let layer_count: u32 = dec.u32()?;
        let view_format_count: u32 = dec.u32()?;
        let p_view_formats: Option<Vec<VkFormat>> =
            match array_presence(dec, u64::from(view_format_count), NullArray::Checked)? {
                Some(n) => Some(decode_vec(dec, n, |dec| {
                    dec.i32().map_err(ProtocolError::from)
                })?),
                None => None,
            };
        Ok(Self {
            flags,
            usage,
            width,
            height,
            layer_count,
            view_format_count,
            p_view_formats,
        })
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_body(&self, enc: &mut Encoder, _partial: bool) -> Result<(), ProtocolError> {
        enc.u32(self.flags)?;
        enc.u32(self.usage)?;
        enc.u32(self.width)?;
        enc.u32(self.height)?;
        enc.u32(self.layer_count)?;
        enc.u32(self.view_format_count)?;
        if let Some(v) = &self.p_view_formats {
            let count = u64::from(self.view_format_count);
            check_len(
                "VkFramebufferAttachmentImageInfo",
                "pViewFormats",
                count,
                v.len(),
            )?;
            enc.array_size(count)?;
            for e in v {
                enc.i32(*e)?;
            }
        } else {
            enc.array_size(0)?;
        }
        Ok(())
    }
}

/// `VkFramebufferAttachmentsCreateInfo` (`VK_STRUCTURE_TYPE_FRAMEBUFFER_ATTACHMENTS_CREATE_INFO`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkFramebufferAttachmentsCreateInfo {
    /// `uint32_t attachmentImageInfoCount`
    pub attachment_image_info_count: u32,
    /// `const VkFramebufferAttachmentImageInfo* pAttachmentImageInfos`
    pub p_attachment_image_infos: Option<Vec<VkFramebufferAttachmentImageInfo>>,
}

impl VkFramebufferAttachmentsCreateInfo {
    // No output parameter reaches this structure, so it has no skeleton
    // form and the `partial` flag below is ignored.

    /// `VK_STRUCTURE_TYPE_FRAMEBUFFER_ATTACHMENTS_CREATE_INFO`.
    pub const STRUCTURE_TYPE: i32 = VK_STRUCTURE_TYPE_FRAMEBUFFER_ATTACHMENTS_CREATE_INFO;

    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// `decode` or `decode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        expect_structure_type(
            dec,
            "VkFramebufferAttachmentsCreateInfo",
            Self::STRUCTURE_TYPE,
        )?;
        dec.empty_pnext_chain("VkFramebufferAttachmentsCreateInfo")?;
        Self::decode_body(dec, partial)
    }

    /// `encode` or `encode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        enc.structure_type(Self::STRUCTURE_TYPE)?;
        enc.simple_pointer(false)?;
        self.encode_body(enc, partial)
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them
    /// (`vn_decode_VkFramebufferAttachmentsCreateInfo_self_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_body(dec: &mut Decoder<'_>, _partial: bool) -> Result<Self, ProtocolError> {
        let attachment_image_info_count: u32 = dec.u32()?;
        let p_attachment_image_infos: Option<Vec<VkFramebufferAttachmentImageInfo>> =
            match array_presence(
                dec,
                u64::from(attachment_image_info_count),
                NullArray::Checked,
            )? {
                Some(n) => Some(decode_vec(dec, n, |dec| {
                    VkFramebufferAttachmentImageInfo::decode_with(dec, false)
                })?),
                None => None,
            };
        Ok(Self {
            attachment_image_info_count,
            p_attachment_image_infos,
        })
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_body(&self, enc: &mut Encoder, _partial: bool) -> Result<(), ProtocolError> {
        enc.u32(self.attachment_image_info_count)?;
        if let Some(v) = &self.p_attachment_image_infos {
            let count = u64::from(self.attachment_image_info_count);
            check_len(
                "VkFramebufferAttachmentsCreateInfo",
                "pAttachmentImageInfos",
                count,
                v.len(),
            )?;
            enc.array_size(count)?;
            for e in v {
                e.encode_with(enc, false)?;
            }
        } else {
            enc.array_size(0)?;
        }
        Ok(())
    }
}

/// The arguments of `vkCreateFramebuffer`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place and sets `ret`, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct CreateFramebufferArgs {
    /// `VkDevice device` — in.
    pub device: VkDevice,
    /// `const VkFramebufferCreateInfo* pCreateInfo` — in.
    pub p_create_info: Option<VkFramebufferCreateInfo>,
    /// `VkFramebuffer* pFramebuffer` — out.
    pub p_framebuffer: Option<VkFramebuffer>,
    /// The return value (`VkResult`), written first in the reply.
    pub ret: VkResult,
}

impl CreateFramebufferArgs {
    /// `VK_COMMAND_TYPE_vkCreateFramebuffer_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_CREATE_FRAMEBUFFER_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkCreateFramebuffer";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkCreateFramebuffer_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        let device: VkDevice = VkDevice(dec.handle()?);
        if device.0 == 0 {
            return Err(null_dispatch_handle(dec, "vkCreateFramebuffer"));
        }
        let p_create_info: Option<VkFramebufferCreateInfo> = if dec.simple_pointer()? {
            Some(VkFramebufferCreateInfo::decode_with(dec, false)?)
        } else {
            return Err(null_pointer(dec, "vkCreateFramebuffer", "pCreateInfo"));
        };
        dec.null_allocator()?;
        let p_framebuffer: Option<VkFramebuffer> = if dec.simple_pointer()? {
            Some(VkFramebuffer(dec.handle()?))
        } else {
            return Err(null_pointer(dec, "vkCreateFramebuffer", "pFramebuffer"));
        };
        Ok(Self {
            device,
            p_create_info,
            p_framebuffer,
            ret: Default::default(),
        })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkCreateFramebuffer`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.handle(self.device.0)?;
        enc.simple_pointer(self.p_create_info.is_some())?;
        if let Some(v) = &self.p_create_info {
            v.encode_with(enc, false)?;
        }
        enc.null_allocator()?;
        enc.simple_pointer(self.p_framebuffer.is_some())?;
        if let Some(v) = &self.p_framebuffer {
            enc.handle(v.0)?;
        }
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkCreateFramebuffer_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        enc.i32(self.ret)?;
        enc.simple_pointer(self.p_framebuffer.is_some())?;
        if let Some(v) = &self.p_framebuffer {
            enc.handle(v.0)?;
        }
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkCreateFramebuffer_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'_>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        self.ret = dec.i32()?;
        self.p_framebuffer = if dec.simple_pointer()? {
            Some(VkFramebuffer(dec.handle()?))
        } else {
            None
        };
        Ok(())
    }

    /// Visit every pNext link the arguments carry, as `(parent, sType)`.
    pub fn for_each_link(&self, f: &mut dyn FnMut(&'static str, i32)) {
        if let Some(v) = &self.p_create_info {
            v.for_each_link(f);
        }
    }
}

/// The arguments of `vkDestroyFramebuffer`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct DestroyFramebufferArgs {
    /// `VkDevice device` — in.
    pub device: VkDevice,
    /// `VkFramebuffer framebuffer` — in.
    pub framebuffer: VkFramebuffer,
}

impl DestroyFramebufferArgs {
    /// `VK_COMMAND_TYPE_vkDestroyFramebuffer_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_DESTROY_FRAMEBUFFER_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkDestroyFramebuffer";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkDestroyFramebuffer_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        let device: VkDevice = VkDevice(dec.handle()?);
        if device.0 == 0 {
            return Err(null_dispatch_handle(dec, "vkDestroyFramebuffer"));
        }
        let framebuffer: VkFramebuffer = VkFramebuffer(dec.handle()?);
        dec.null_allocator()?;
        Ok(Self {
            device,
            framebuffer,
        })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkDestroyFramebuffer`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.handle(self.device.0)?;
        enc.handle(self.framebuffer.0)?;
        enc.null_allocator()?;
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkDestroyFramebuffer_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkDestroyFramebuffer_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'_>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        Ok(())
    }
}
