// @generated by tools/venus-protocol/rust_protocol.py (templates/rust_group.rs)
// from venus-protocol git-70991d4c. DO NOT EDIT: regenerate with
//     python scripts/venus-gen.py

//! The `image` group: its commands and the structures only they reach.

#![allow(unused_imports)]

use super::*;
use crate::venus::wire::{CommandHeader, Decoder, Encoder};

/// `VkImageCreateInfo` (`VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkImageCreateInfo {
    /// The pNext chain, in the guest's order. Admits: `VkExternalMemoryImageCreateInfo`, `VkImageFormatListCreateInfo`, `VkImageStencilUsageCreateInfo`.
    pub p_next: Vec<VkImageCreateInfoNext>,
    /// `VkImageCreateFlags flags`
    pub flags: VkImageCreateFlags,
    /// `VkImageType imageType`
    pub image_type: VkImageType,
    /// `VkFormat format`
    pub format: VkFormat,
    /// `VkExtent3D extent`
    pub extent: VkExtent3D,
    /// `uint32_t mipLevels`
    pub mip_levels: u32,
    /// `uint32_t arrayLayers`
    pub array_layers: u32,
    /// `VkSampleCountFlagBits samples`
    pub samples: VkSampleCountFlagBits,
    /// `VkImageTiling tiling`
    pub tiling: VkImageTiling,
    /// `VkImageUsageFlags usage`
    pub usage: VkImageUsageFlags,
    /// `VkSharingMode sharingMode`
    pub sharing_mode: VkSharingMode,
    /// `uint32_t queueFamilyIndexCount`
    pub queue_family_index_count: u32,
    /// `const uint32_t* pQueueFamilyIndices`
    pub p_queue_family_indices: Option<Vec<u32>>,
    /// `VkImageLayout initialLayout`
    pub initial_layout: VkImageLayout,
}

impl VkImageCreateInfo {
    // No output parameter reaches this structure, so it has no skeleton
    // form and the `partial` flag below is ignored.

    /// `VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO`.
    pub const STRUCTURE_TYPE: i32 = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO;

    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// `decode` or `decode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        expect_structure_type(dec, "VkImageCreateInfo", Self::STRUCTURE_TYPE)?;
        let p_next = decode_chain::<VkImageCreateInfoNext>(dec, partial)?;
        let mut value = Self::decode_body(dec, partial)?;
        value.p_next = p_next;
        Ok(value)
    }

    /// `encode` or `encode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        enc.structure_type(Self::STRUCTURE_TYPE)?;
        encode_chain(enc, &self.p_next, partial)?;
        self.encode_body(enc, partial)
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them
    /// (`vn_decode_VkImageCreateInfo_self_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_body(dec: &mut Decoder<'_>, _partial: bool) -> Result<Self, ProtocolError> {
        let flags: VkImageCreateFlags = dec.u32()?;
        let image_type: VkImageType = dec.i32()?;
        let format: VkFormat = dec.i32()?;
        let extent: VkExtent3D = VkExtent3D::decode_with(dec, false)?;
        let mip_levels: u32 = dec.u32()?;
        let array_layers: u32 = dec.u32()?;
        let samples: VkSampleCountFlagBits = dec.i32()?;
        let tiling: VkImageTiling = dec.i32()?;
        let usage: VkImageUsageFlags = dec.u32()?;
        let sharing_mode: VkSharingMode = dec.i32()?;
        let queue_family_index_count: u32 = dec.u32()?;
        let p_queue_family_indices: Option<Vec<u32>> = match array_presence(
            dec,
            u64::from(queue_family_index_count),
            NullArray::Unchecked,
        )? {
            Some(n) => Some(dec.u32_array(n)?),
            None => None,
        };
        let initial_layout: VkImageLayout = dec.i32()?;
        Ok(Self {
            p_next: Vec::new(),
            flags,
            image_type,
            format,
            extent,
            mip_levels,
            array_layers,
            samples,
            tiling,
            usage,
            sharing_mode,
            queue_family_index_count,
            p_queue_family_indices,
            initial_layout,
        })
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_body(&self, enc: &mut Encoder, _partial: bool) -> Result<(), ProtocolError> {
        enc.u32(self.flags)?;
        enc.i32(self.image_type)?;
        enc.i32(self.format)?;
        self.extent.encode_with(enc, false)?;
        enc.u32(self.mip_levels)?;
        enc.u32(self.array_layers)?;
        enc.i32(self.samples)?;
        enc.i32(self.tiling)?;
        enc.u32(self.usage)?;
        enc.i32(self.sharing_mode)?;
        enc.u32(self.queue_family_index_count)?;
        if self.sharing_mode == VK_SHARING_MODE_CONCURRENT {
            let v = self.p_queue_family_indices.as_deref().unwrap_or_default();
            let count = u64::from(self.queue_family_index_count);
            check_len("VkImageCreateInfo", "pQueueFamilyIndices", count, v.len())?;
            enc.array_size(count)?;
            for e in v {
                enc.u32(*e)?;
            }
        } else {
            enc.array_size(0)?;
        }
        enc.i32(self.initial_layout)?;
        Ok(())
    }
}

/// A link of `VkImageCreateInfo`'s pNext chain.
#[derive(Debug, Clone, PartialEq)]
pub enum VkImageCreateInfoNext {
    /// `VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_IMAGE_CREATE_INFO`.
    VkExternalMemoryImageCreateInfo(VkExternalMemoryImageCreateInfo),
    /// `VK_STRUCTURE_TYPE_IMAGE_FORMAT_LIST_CREATE_INFO`.
    VkImageFormatListCreateInfo(VkImageFormatListCreateInfo),
    /// `VK_STRUCTURE_TYPE_IMAGE_STENCIL_USAGE_CREATE_INFO`.
    VkImageStencilUsageCreateInfo(VkImageStencilUsageCreateInfo),
}

impl<'a> ChainLink<'a> for VkImageCreateInfoNext {
    const PARENT: &'static str = "VkImageCreateInfo";

    fn structure_type(&self) -> i32 {
        match self {
            Self::VkExternalMemoryImageCreateInfo(_) => {
                VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_IMAGE_CREATE_INFO
            }
            Self::VkImageFormatListCreateInfo(_) => VK_STRUCTURE_TYPE_IMAGE_FORMAT_LIST_CREATE_INFO,
            Self::VkImageStencilUsageCreateInfo(_) => {
                VK_STRUCTURE_TYPE_IMAGE_STENCIL_USAGE_CREATE_INFO
            }
        }
    }

    fn decode_body(
        stype: i32,
        dec: &mut Decoder<'a>,
        partial: bool,
    ) -> Option<Result<Self, ProtocolError>> {
        Some(match stype {
            VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_IMAGE_CREATE_INFO => {
                VkExternalMemoryImageCreateInfo::decode_body(dec, partial)
                    .map(Self::VkExternalMemoryImageCreateInfo)
            }
            VK_STRUCTURE_TYPE_IMAGE_FORMAT_LIST_CREATE_INFO => {
                VkImageFormatListCreateInfo::decode_body(dec, partial)
                    .map(Self::VkImageFormatListCreateInfo)
            }
            VK_STRUCTURE_TYPE_IMAGE_STENCIL_USAGE_CREATE_INFO => {
                VkImageStencilUsageCreateInfo::decode_body(dec, partial)
                    .map(Self::VkImageStencilUsageCreateInfo)
            }
            _ => return None,
        })
    }

    fn encode_body(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        match self {
            Self::VkExternalMemoryImageCreateInfo(link) => link.encode_body(enc, partial),
            Self::VkImageFormatListCreateInfo(link) => link.encode_body(enc, partial),
            Self::VkImageStencilUsageCreateInfo(link) => link.encode_body(enc, partial),
        }
    }
}

/// `VkExternalMemoryImageCreateInfo` (`VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_IMAGE_CREATE_INFO`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkExternalMemoryImageCreateInfo {
    /// `VkExternalMemoryHandleTypeFlags handleTypes`
    pub handle_types: VkExternalMemoryHandleTypeFlags,
}

impl VkExternalMemoryImageCreateInfo {
    // No output parameter reaches this structure, so it has no skeleton
    // form and the `partial` flag below is ignored.

    /// `VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_IMAGE_CREATE_INFO`.
    pub const STRUCTURE_TYPE: i32 = VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_IMAGE_CREATE_INFO;

    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// `decode` or `decode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        expect_structure_type(dec, "VkExternalMemoryImageCreateInfo", Self::STRUCTURE_TYPE)?;
        dec.empty_pnext_chain("VkExternalMemoryImageCreateInfo")?;
        Self::decode_body(dec, partial)
    }

    /// `encode` or `encode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        enc.structure_type(Self::STRUCTURE_TYPE)?;
        enc.simple_pointer(false)?;
        self.encode_body(enc, partial)
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them
    /// (`vn_decode_VkExternalMemoryImageCreateInfo_self_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_body(dec: &mut Decoder<'_>, _partial: bool) -> Result<Self, ProtocolError> {
        let handle_types: VkExternalMemoryHandleTypeFlags = dec.u32()?;
        Ok(Self { handle_types })
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_body(&self, enc: &mut Encoder, _partial: bool) -> Result<(), ProtocolError> {
        enc.u32(self.handle_types)?;
        Ok(())
    }
}

/// `VkImageMemoryRequirementsInfo2` (`VK_STRUCTURE_TYPE_IMAGE_MEMORY_REQUIREMENTS_INFO_2`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkImageMemoryRequirementsInfo2 {
    /// The pNext chain, in the guest's order. Admits: `VkImagePlaneMemoryRequirementsInfo`.
    pub p_next: Vec<VkImageMemoryRequirementsInfo2Next>,
    /// `VkImage image`
    pub image: VkImage,
}

impl VkImageMemoryRequirementsInfo2 {
    // No output parameter reaches this structure, so it has no skeleton
    // form and the `partial` flag below is ignored.

    /// `VK_STRUCTURE_TYPE_IMAGE_MEMORY_REQUIREMENTS_INFO_2`.
    pub const STRUCTURE_TYPE: i32 = VK_STRUCTURE_TYPE_IMAGE_MEMORY_REQUIREMENTS_INFO_2;

    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// `decode` or `decode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        expect_structure_type(dec, "VkImageMemoryRequirementsInfo2", Self::STRUCTURE_TYPE)?;
        let p_next = decode_chain::<VkImageMemoryRequirementsInfo2Next>(dec, partial)?;
        let mut value = Self::decode_body(dec, partial)?;
        value.p_next = p_next;
        Ok(value)
    }

    /// `encode` or `encode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        enc.structure_type(Self::STRUCTURE_TYPE)?;
        encode_chain(enc, &self.p_next, partial)?;
        self.encode_body(enc, partial)
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them
    /// (`vn_decode_VkImageMemoryRequirementsInfo2_self_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_body(dec: &mut Decoder<'_>, _partial: bool) -> Result<Self, ProtocolError> {
        let image: VkImage = VkImage(dec.handle()?);
        Ok(Self {
            p_next: Vec::new(),
            image,
        })
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_body(&self, enc: &mut Encoder, _partial: bool) -> Result<(), ProtocolError> {
        enc.handle(self.image.0)?;
        Ok(())
    }
}

/// A link of `VkImageMemoryRequirementsInfo2`'s pNext chain.
#[derive(Debug, Clone, PartialEq)]
pub enum VkImageMemoryRequirementsInfo2Next {
    /// `VK_STRUCTURE_TYPE_IMAGE_PLANE_MEMORY_REQUIREMENTS_INFO`.
    VkImagePlaneMemoryRequirementsInfo(VkImagePlaneMemoryRequirementsInfo),
}

impl<'a> ChainLink<'a> for VkImageMemoryRequirementsInfo2Next {
    const PARENT: &'static str = "VkImageMemoryRequirementsInfo2";

    fn structure_type(&self) -> i32 {
        match self {
            Self::VkImagePlaneMemoryRequirementsInfo(_) => {
                VK_STRUCTURE_TYPE_IMAGE_PLANE_MEMORY_REQUIREMENTS_INFO
            }
        }
    }

    fn decode_body(
        stype: i32,
        dec: &mut Decoder<'a>,
        partial: bool,
    ) -> Option<Result<Self, ProtocolError>> {
        Some(match stype {
            VK_STRUCTURE_TYPE_IMAGE_PLANE_MEMORY_REQUIREMENTS_INFO => {
                VkImagePlaneMemoryRequirementsInfo::decode_body(dec, partial)
                    .map(Self::VkImagePlaneMemoryRequirementsInfo)
            }
            _ => return None,
        })
    }

    fn encode_body(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        match self {
            Self::VkImagePlaneMemoryRequirementsInfo(link) => link.encode_body(enc, partial),
        }
    }
}

/// `VkImagePlaneMemoryRequirementsInfo` (`VK_STRUCTURE_TYPE_IMAGE_PLANE_MEMORY_REQUIREMENTS_INFO`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkImagePlaneMemoryRequirementsInfo {
    /// `VkImageAspectFlagBits planeAspect`
    pub plane_aspect: VkImageAspectFlagBits,
}

impl VkImagePlaneMemoryRequirementsInfo {
    // No output parameter reaches this structure, so it has no skeleton
    // form and the `partial` flag below is ignored.

    /// `VK_STRUCTURE_TYPE_IMAGE_PLANE_MEMORY_REQUIREMENTS_INFO`.
    pub const STRUCTURE_TYPE: i32 = VK_STRUCTURE_TYPE_IMAGE_PLANE_MEMORY_REQUIREMENTS_INFO;

    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// `decode` or `decode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        expect_structure_type(
            dec,
            "VkImagePlaneMemoryRequirementsInfo",
            Self::STRUCTURE_TYPE,
        )?;
        dec.empty_pnext_chain("VkImagePlaneMemoryRequirementsInfo")?;
        Self::decode_body(dec, partial)
    }

    /// `encode` or `encode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        enc.structure_type(Self::STRUCTURE_TYPE)?;
        enc.simple_pointer(false)?;
        self.encode_body(enc, partial)
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them
    /// (`vn_decode_VkImagePlaneMemoryRequirementsInfo_self_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_body(dec: &mut Decoder<'_>, _partial: bool) -> Result<Self, ProtocolError> {
        let plane_aspect: VkImageAspectFlagBits = dec.i32()?;
        Ok(Self { plane_aspect })
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_body(&self, enc: &mut Encoder, _partial: bool) -> Result<(), ProtocolError> {
        enc.i32(self.plane_aspect)?;
        Ok(())
    }
}

/// `VkMemoryRequirements`.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkMemoryRequirements {
    /// `VkDeviceSize size`
    pub size: VkDeviceSize,
    /// `VkDeviceSize alignment`
    pub alignment: VkDeviceSize,
    /// `uint32_t memoryTypeBits`
    pub memory_type_bits: u32,
}

impl VkMemoryRequirements {
    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Decode the skeleton an output structure is sent as inside a command
    /// (`vn_decode_VkMemoryRequirements_partial_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_partial(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, true)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// Encode the skeleton form (`vn_encode_VkMemoryRequirements_partial`).
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_partial(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, true)
    }

    /// `decode` or `decode_partial`.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        let size: VkDeviceSize = if partial {
            Default::default()
        } else {
            dec.u64()?
        };
        let alignment: VkDeviceSize = if partial {
            Default::default()
        } else {
            dec.u64()?
        };
        let memory_type_bits: u32 = if partial {
            Default::default()
        } else {
            dec.u32()?
        };
        Ok(Self {
            size,
            alignment,
            memory_type_bits,
        })
    }

    /// `encode` or `encode_partial`.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        if !partial {
            enc.u64(self.size)?;
        }
        if !partial {
            enc.u64(self.alignment)?;
        }
        if !partial {
            enc.u32(self.memory_type_bits)?;
        }
        Ok(())
    }
}

/// `VkMemoryRequirements2` (`VK_STRUCTURE_TYPE_MEMORY_REQUIREMENTS_2`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkMemoryRequirements2 {
    /// The pNext chain, in the guest's order. Admits: `VkMemoryDedicatedRequirements`.
    pub p_next: Vec<VkMemoryRequirements2Next>,
    /// `VkMemoryRequirements memoryRequirements`
    pub memory_requirements: VkMemoryRequirements,
}

impl VkMemoryRequirements2 {
    /// `VK_STRUCTURE_TYPE_MEMORY_REQUIREMENTS_2`.
    pub const STRUCTURE_TYPE: i32 = VK_STRUCTURE_TYPE_MEMORY_REQUIREMENTS_2;

    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Decode the skeleton an output structure is sent as inside a command
    /// (`vn_decode_VkMemoryRequirements2_partial_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_partial(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, true)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// Encode the skeleton form (`vn_encode_VkMemoryRequirements2_partial`).
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_partial(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, true)
    }

    /// `decode` or `decode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        expect_structure_type(dec, "VkMemoryRequirements2", Self::STRUCTURE_TYPE)?;
        let p_next = decode_chain::<VkMemoryRequirements2Next>(dec, partial)?;
        let mut value = Self::decode_body(dec, partial)?;
        value.p_next = p_next;
        Ok(value)
    }

    /// `encode` or `encode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        enc.structure_type(Self::STRUCTURE_TYPE)?;
        encode_chain(enc, &self.p_next, partial)?;
        self.encode_body(enc, partial)
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them
    /// (`vn_decode_VkMemoryRequirements2_self_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_body(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        let memory_requirements: VkMemoryRequirements =
            VkMemoryRequirements::decode_with(dec, partial)?;
        Ok(Self {
            p_next: Vec::new(),
            memory_requirements,
        })
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_body(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        self.memory_requirements.encode_with(enc, partial)?;
        Ok(())
    }
}

/// A link of `VkMemoryRequirements2`'s pNext chain.
#[derive(Debug, Clone, PartialEq)]
pub enum VkMemoryRequirements2Next {
    /// `VK_STRUCTURE_TYPE_MEMORY_DEDICATED_REQUIREMENTS`.
    VkMemoryDedicatedRequirements(VkMemoryDedicatedRequirements),
}

impl<'a> ChainLink<'a> for VkMemoryRequirements2Next {
    const PARENT: &'static str = "VkMemoryRequirements2";

    fn structure_type(&self) -> i32 {
        match self {
            Self::VkMemoryDedicatedRequirements(_) => {
                VK_STRUCTURE_TYPE_MEMORY_DEDICATED_REQUIREMENTS
            }
        }
    }

    fn decode_body(
        stype: i32,
        dec: &mut Decoder<'a>,
        partial: bool,
    ) -> Option<Result<Self, ProtocolError>> {
        Some(match stype {
            VK_STRUCTURE_TYPE_MEMORY_DEDICATED_REQUIREMENTS => {
                VkMemoryDedicatedRequirements::decode_body(dec, partial)
                    .map(Self::VkMemoryDedicatedRequirements)
            }
            _ => return None,
        })
    }

    fn encode_body(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        match self {
            Self::VkMemoryDedicatedRequirements(link) => link.encode_body(enc, partial),
        }
    }
}

/// `VkMemoryDedicatedRequirements` (`VK_STRUCTURE_TYPE_MEMORY_DEDICATED_REQUIREMENTS`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkMemoryDedicatedRequirements {
    /// `VkBool32 prefersDedicatedAllocation`
    pub prefers_dedicated_allocation: VkBool32,
    /// `VkBool32 requiresDedicatedAllocation`
    pub requires_dedicated_allocation: VkBool32,
}

impl VkMemoryDedicatedRequirements {
    /// `VK_STRUCTURE_TYPE_MEMORY_DEDICATED_REQUIREMENTS`.
    pub const STRUCTURE_TYPE: i32 = VK_STRUCTURE_TYPE_MEMORY_DEDICATED_REQUIREMENTS;

    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Decode the skeleton an output structure is sent as inside a command
    /// (`vn_decode_VkMemoryDedicatedRequirements_partial_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_partial(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, true)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// Encode the skeleton form (`vn_encode_VkMemoryDedicatedRequirements_partial`).
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_partial(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, true)
    }

    /// `decode` or `decode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        expect_structure_type(dec, "VkMemoryDedicatedRequirements", Self::STRUCTURE_TYPE)?;
        dec.empty_pnext_chain("VkMemoryDedicatedRequirements")?;
        Self::decode_body(dec, partial)
    }

    /// `encode` or `encode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        enc.structure_type(Self::STRUCTURE_TYPE)?;
        enc.simple_pointer(false)?;
        self.encode_body(enc, partial)
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them
    /// (`vn_decode_VkMemoryDedicatedRequirements_self_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_body(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        let prefers_dedicated_allocation: VkBool32 = if partial {
            Default::default()
        } else {
            dec.u32()?
        };
        let requires_dedicated_allocation: VkBool32 = if partial {
            Default::default()
        } else {
            dec.u32()?
        };
        Ok(Self {
            prefers_dedicated_allocation,
            requires_dedicated_allocation,
        })
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_body(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        if !partial {
            enc.u32(self.prefers_dedicated_allocation)?;
        }
        if !partial {
            enc.u32(self.requires_dedicated_allocation)?;
        }
        Ok(())
    }
}

/// The arguments of `vkCreateImage`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place and sets `ret`, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct CreateImageArgs {
    /// `VkDevice device` — in.
    pub device: VkDevice,
    /// `const VkImageCreateInfo* pCreateInfo` — in.
    pub p_create_info: Option<VkImageCreateInfo>,
    /// `VkImage* pImage` — out.
    pub p_image: Option<VkImage>,
    /// The return value (`VkResult`), written first in the reply.
    pub ret: VkResult,
}

impl CreateImageArgs {
    /// `VK_COMMAND_TYPE_vkCreateImage_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_CREATE_IMAGE_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkCreateImage";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkCreateImage_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        let device: VkDevice = VkDevice(dec.handle()?);
        if device.0 == 0 {
            return Err(null_dispatch_handle(dec, "vkCreateImage"));
        }
        let p_create_info: Option<VkImageCreateInfo> = if dec.simple_pointer()? {
            Some(VkImageCreateInfo::decode_with(dec, false)?)
        } else {
            return Err(null_pointer(dec, "vkCreateImage", "pCreateInfo"));
        };
        dec.null_allocator()?;
        let p_image: Option<VkImage> = if dec.simple_pointer()? {
            Some(VkImage(dec.handle()?))
        } else {
            return Err(null_pointer(dec, "vkCreateImage", "pImage"));
        };
        Ok(Self {
            device,
            p_create_info,
            p_image,
            ret: Default::default(),
        })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkCreateImage`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.handle(self.device.0)?;
        enc.simple_pointer(self.p_create_info.is_some())?;
        if let Some(v) = &self.p_create_info {
            v.encode_with(enc, false)?;
        }
        enc.null_allocator()?;
        enc.simple_pointer(self.p_image.is_some())?;
        if let Some(v) = &self.p_image {
            enc.handle(v.0)?;
        }
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkCreateImage_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        enc.i32(self.ret)?;
        enc.simple_pointer(self.p_image.is_some())?;
        if let Some(v) = &self.p_image {
            enc.handle(v.0)?;
        }
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkCreateImage_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'_>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        self.ret = dec.i32()?;
        self.p_image = if dec.simple_pointer()? {
            Some(VkImage(dec.handle()?))
        } else {
            None
        };
        Ok(())
    }
}

/// The arguments of `vkDestroyImage`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct DestroyImageArgs {
    /// `VkDevice device` — in.
    pub device: VkDevice,
    /// `VkImage image` — in.
    pub image: VkImage,
}

impl DestroyImageArgs {
    /// `VK_COMMAND_TYPE_vkDestroyImage_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_DESTROY_IMAGE_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkDestroyImage";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkDestroyImage_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        let device: VkDevice = VkDevice(dec.handle()?);
        if device.0 == 0 {
            return Err(null_dispatch_handle(dec, "vkDestroyImage"));
        }
        let image: VkImage = VkImage(dec.handle()?);
        dec.null_allocator()?;
        Ok(Self { device, image })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkDestroyImage`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.handle(self.device.0)?;
        enc.handle(self.image.0)?;
        enc.null_allocator()?;
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkDestroyImage_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkDestroyImage_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'_>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        Ok(())
    }
}

/// The arguments of `vkGetImageMemoryRequirements2`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct GetImageMemoryRequirements2Args {
    /// `VkDevice device` — in.
    pub device: VkDevice,
    /// `const VkImageMemoryRequirementsInfo2* pInfo` — in.
    pub p_info: Option<VkImageMemoryRequirementsInfo2>,
    /// `VkMemoryRequirements2* pMemoryRequirements` — out.
    pub p_memory_requirements: Option<VkMemoryRequirements2>,
}

impl GetImageMemoryRequirements2Args {
    /// `VK_COMMAND_TYPE_vkGetImageMemoryRequirements2_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_GET_IMAGE_MEMORY_REQUIREMENTS_2_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkGetImageMemoryRequirements2";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkGetImageMemoryRequirements2_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        let device: VkDevice = VkDevice(dec.handle()?);
        if device.0 == 0 {
            return Err(null_dispatch_handle(dec, "vkGetImageMemoryRequirements2"));
        }
        let p_info: Option<VkImageMemoryRequirementsInfo2> = if dec.simple_pointer()? {
            Some(VkImageMemoryRequirementsInfo2::decode_with(dec, false)?)
        } else {
            return Err(null_pointer(dec, "vkGetImageMemoryRequirements2", "pInfo"));
        };
        let p_memory_requirements: Option<VkMemoryRequirements2> = if dec.simple_pointer()? {
            Some(VkMemoryRequirements2::decode_with(dec, true)?)
        } else {
            return Err(null_pointer(
                dec,
                "vkGetImageMemoryRequirements2",
                "pMemoryRequirements",
            ));
        };
        Ok(Self {
            device,
            p_info,
            p_memory_requirements,
        })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkGetImageMemoryRequirements2`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.handle(self.device.0)?;
        enc.simple_pointer(self.p_info.is_some())?;
        if let Some(v) = &self.p_info {
            v.encode_with(enc, false)?;
        }
        enc.simple_pointer(self.p_memory_requirements.is_some())?;
        if let Some(v) = &self.p_memory_requirements {
            v.encode_with(enc, true)?;
        }
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkGetImageMemoryRequirements2_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        enc.simple_pointer(self.p_memory_requirements.is_some())?;
        if let Some(v) = &self.p_memory_requirements {
            v.encode_with(enc, false)?;
        }
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkGetImageMemoryRequirements2_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'_>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        self.p_memory_requirements = if dec.simple_pointer()? {
            Some(VkMemoryRequirements2::decode_with(dec, false)?)
        } else {
            None
        };
        Ok(())
    }
}
