// @generated by tools/venus-protocol/rust_protocol.py (templates/rust_group.rs)
// from venus-protocol git-70991d4c. DO NOT EDIT: regenerate with
//     python scripts/venus-gen.py

//! The `image_view` group: its commands and the structures only they reach.

#![allow(unused_imports)]

use super::*;
use crate::venus::wire::{CommandHeader, Decoder, Encoder};

/// The arguments of `vkCreateImageView`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place and sets `ret`, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct CreateImageViewArgs {
    /// `VkDevice device` — in.
    pub device: VkDevice,
    /// `const VkImageViewCreateInfo* pCreateInfo` — in.
    pub p_create_info: Option<VkImageViewCreateInfo>,
    /// `VkImageView* pView` — out.
    pub p_view: Option<VkImageView>,
    /// The return value (`VkResult`), written first in the reply.
    pub ret: VkResult,
}

impl CreateImageViewArgs {
    /// `VK_COMMAND_TYPE_vkCreateImageView_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_CREATE_IMAGE_VIEW_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkCreateImageView";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkCreateImageView_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        let device: VkDevice = VkDevice(dec.handle()?);
        if device.0 == 0 {
            return Err(null_dispatch_handle(dec, "vkCreateImageView"));
        }
        let p_create_info: Option<VkImageViewCreateInfo> = if dec.simple_pointer()? {
            Some(VkImageViewCreateInfo::decode_with(dec, false)?)
        } else {
            return Err(null_pointer(dec, "vkCreateImageView", "pCreateInfo"));
        };
        dec.null_allocator()?;
        let p_view: Option<VkImageView> = if dec.simple_pointer()? {
            Some(VkImageView(dec.handle()?))
        } else {
            return Err(null_pointer(dec, "vkCreateImageView", "pView"));
        };
        Ok(Self {
            device,
            p_create_info,
            p_view,
            ret: Default::default(),
        })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkCreateImageView`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.handle(self.device.0)?;
        enc.simple_pointer(self.p_create_info.is_some())?;
        if let Some(v) = &self.p_create_info {
            v.encode_with(enc, false)?;
        }
        enc.null_allocator()?;
        enc.simple_pointer(self.p_view.is_some())?;
        if let Some(v) = &self.p_view {
            enc.handle(v.0)?;
        }
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkCreateImageView_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        enc.i32(self.ret)?;
        enc.simple_pointer(self.p_view.is_some())?;
        if let Some(v) = &self.p_view {
            enc.handle(v.0)?;
        }
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkCreateImageView_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'_>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        self.ret = dec.i32()?;
        self.p_view = if dec.simple_pointer()? {
            Some(VkImageView(dec.handle()?))
        } else {
            None
        };
        Ok(())
    }

    /// Visit every pNext link the arguments carry, as `(parent, sType)`.
    pub fn for_each_link(&self, f: &mut dyn FnMut(&'static str, i32)) {
        if let Some(v) = &self.p_create_info {
            v.for_each_link(f);
        }
    }
}

/// The arguments of `vkDestroyImageView`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct DestroyImageViewArgs {
    /// `VkDevice device` — in.
    pub device: VkDevice,
    /// `VkImageView imageView` — in.
    pub image_view: VkImageView,
}

impl DestroyImageViewArgs {
    /// `VK_COMMAND_TYPE_vkDestroyImageView_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_DESTROY_IMAGE_VIEW_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkDestroyImageView";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkDestroyImageView_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        let device: VkDevice = VkDevice(dec.handle()?);
        if device.0 == 0 {
            return Err(null_dispatch_handle(dec, "vkDestroyImageView"));
        }
        let image_view: VkImageView = VkImageView(dec.handle()?);
        dec.null_allocator()?;
        Ok(Self { device, image_view })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkDestroyImageView`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.handle(self.device.0)?;
        enc.handle(self.image_view.0)?;
        enc.null_allocator()?;
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkDestroyImageView_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkDestroyImageView_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'_>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        Ok(())
    }
}
