// @generated by tools/venus-protocol/rust_protocol.py (templates/rust_info.rs)
// from venus-protocol git-70991d4c. DO NOT EDIT: regenerate with
//     python scripts/venus-gen.py

//! What the protocol revision knows, and what this crate decodes of it.
//!
//! The extension table is `vn_protocol_renderer_info.h`'s: every extension in
//! venus-protocol's `VK_XML_EXTENSION_LIST`, sorted by name, with its registry
//! number and spec version. `decodable` marks the ones whose structures the
//! selection file (`[extensions]`) had generated. The capset's
//! `vk_extension_mask1` should advertise [`DECODABLE_EXTENSION_MASK`] and
//! nothing wider: the guest's encoder drops a chained structure whose
//! extension is not in the mask, and any structure it does send that this
//! crate did not generate is fatal on arrival (spec §6; virglrenderer sets
//! the sentinel and enumerates its own list, `vkr_renderer.c:40-48`).

/// `VN_WIRE_FORMAT_VERSION`: must equal the guest's exactly, or Mesa stubs
/// the instance out.
pub const WIRE_FORMAT_VERSION: u32 = 1;

/// The `vk.xml` the protocol was generated from,
/// `VK_MAKE_API_VERSION(0, 1, 4, 343)`.
pub const VK_XML_VERSION: u32 = 0x404157;

/// The newest core version whose structures pNext chains may carry here
/// (`[api]` in the selection file), `VK_MAKE_API_VERSION(0, 1, 3, 0)`.
/// A capset `vk_xml_version` at or below this keeps the guest from chaining
/// a newer core structure.
pub const CHAIN_API_VERSION: u32 = 0x403000;

/// One entry of the protocol's extension table.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ExtensionInfo {
    /// `VK_KHR_...`.
    pub name: &'static str,
    /// The registry's extension number: its bit in the capset mask.
    pub number: u32,
    /// `*_SPEC_VERSION` in the registry the protocol was generated from.
    pub spec_version: u32,
    /// Whether every structure it adds to a pNext chain was generated.
    pub decodable: bool,
}

/// Every extension the protocol revision knows, sorted by name.
pub const EXTENSIONS: &[ExtensionInfo] = &[
    ExtensionInfo {
        name: "VK_ARM_rasterization_order_attachment_access",
        number: 343,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_4444_formats",
        number: 341,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_attachment_feedback_loop_dynamic_state",
        number: 525,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_attachment_feedback_loop_layout",
        number: 340,
        spec_version: 2,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_blend_operation_advanced",
        number: 149,
        spec_version: 2,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_border_color_swizzle",
        number: 412,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_buffer_device_address",
        number: 245,
        spec_version: 2,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_calibrated_timestamps",
        number: 185,
        spec_version: 2,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_color_write_enable",
        number: 382,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_command_serialization",
        number: 384,
        spec_version: 1,
        decodable: true,
    },
    ExtensionInfo {
        name: "VK_EXT_conditional_rendering",
        number: 82,
        spec_version: 2,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_conservative_rasterization",
        number: 102,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_custom_border_color",
        number: 288,
        spec_version: 12,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_depth_bias_control",
        number: 284,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_depth_clamp_control",
        number: 583,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_depth_clamp_zero_one",
        number: 422,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_depth_clip_control",
        number: 356,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_depth_clip_enable",
        number: 103,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_depth_range_unrestricted",
        number: 14,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_descriptor_heap",
        number: 136,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_descriptor_indexing",
        number: 162,
        spec_version: 2,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_dynamic_rendering_unused_attachments",
        number: 500,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_extended_dynamic_state",
        number: 268,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_extended_dynamic_state2",
        number: 378,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_extended_dynamic_state3",
        number: 456,
        spec_version: 2,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_external_memory_acquire_unmodified",
        number: 454,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_external_memory_dma_buf",
        number: 126,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_filter_cubic",
        number: 171,
        spec_version: 3,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_fragment_shader_interlock",
        number: 252,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_global_priority",
        number: 175,
        spec_version: 2,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_global_priority_query",
        number: 389,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_graphics_pipeline_library",
        number: 321,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_host_image_copy",
        number: 271,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_host_query_reset",
        number: 262,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_image_2d_view_of_3d",
        number: 394,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_image_drm_format_modifier",
        number: 159,
        spec_version: 2,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_image_robustness",
        number: 336,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_image_sliced_view_of_3d",
        number: 419,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_image_view_min_lod",
        number: 392,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_index_type_uint8",
        number: 266,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_inline_uniform_block",
        number: 139,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_legacy_dithering",
        number: 466,
        spec_version: 2,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_legacy_vertex_attributes",
        number: 496,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_line_rasterization",
        number: 260,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_load_store_op_none",
        number: 401,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_memory_budget",
        number: 238,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_mesh_shader",
        number: 329,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_multi_draw",
        number: 393,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_multisampled_render_to_single_sampled",
        number: 377,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_mutable_descriptor_type",
        number: 495,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_nested_command_buffer",
        number: 452,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_non_seamless_cube_map",
        number: 423,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_pci_bus_info",
        number: 213,
        spec_version: 2,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_pipeline_creation_cache_control",
        number: 298,
        spec_version: 3,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_pipeline_creation_feedback",
        number: 193,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_pipeline_library_group_handles",
        number: 499,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_pipeline_protected_access",
        number: 467,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_pipeline_robustness",
        number: 69,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_post_depth_coverage",
        number: 156,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_primitive_topology_list_restart",
        number: 357,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_primitives_generated_query",
        number: 383,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_private_data",
        number: 296,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_provoking_vertex",
        number: 255,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_queue_family_foreign",
        number: 127,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_rasterization_order_attachment_access",
        number: 464,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_robustness2",
        number: 287,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_sample_locations",
        number: 144,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_sampler_filter_minmax",
        number: 131,
        spec_version: 2,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_scalar_block_layout",
        number: 222,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_separate_stencil_usage",
        number: 247,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_shader_atomic_float",
        number: 261,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_shader_atomic_float2",
        number: 274,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_shader_demote_to_helper_invocation",
        number: 277,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_shader_float8",
        number: 568,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_shader_image_atomic_int64",
        number: 235,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_shader_replicated_composites",
        number: 565,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_shader_stencil_export",
        number: 141,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_shader_subgroup_ballot",
        number: 65,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_shader_subgroup_vote",
        number: 66,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_shader_uniform_buffer_unsized_array",
        number: 643,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_shader_viewport_index_layer",
        number: 163,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_subgroup_size_control",
        number: 226,
        spec_version: 2,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_texel_buffer_alignment",
        number: 282,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_texture_compression_astc_hdr",
        number: 67,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_tooling_info",
        number: 246,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_transform_feedback",
        number: 29,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_vertex_attribute_divisor",
        number: 191,
        spec_version: 3,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_vertex_input_dynamic_state",
        number: 353,
        spec_version: 2,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_ycbcr_2plane_444_formats",
        number: 331,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_EXT_ycbcr_image_arrays",
        number: 253,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_GOOGLE_decorate_string",
        number: 225,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_GOOGLE_hlsl_functionality1",
        number: 224,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_GOOGLE_user_type",
        number: 290,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_IMG_filter_cubic",
        number: 16,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_16bit_storage",
        number: 84,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_8bit_storage",
        number: 178,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_acceleration_structure",
        number: 151,
        spec_version: 13,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_bind_memory2",
        number: 158,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_buffer_device_address",
        number: 258,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_calibrated_timestamps",
        number: 544,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_compute_shader_derivatives",
        number: 512,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_cooperative_matrix",
        number: 507,
        spec_version: 2,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_copy_commands2",
        number: 338,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_create_renderpass2",
        number: 110,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_dedicated_allocation",
        number: 128,
        spec_version: 3,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_deferred_host_operations",
        number: 269,
        spec_version: 4,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_depth_clamp_zero_one",
        number: 605,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_depth_stencil_resolve",
        number: 200,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_descriptor_update_template",
        number: 86,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_device_group",
        number: 61,
        spec_version: 4,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_device_group_creation",
        number: 71,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_draw_indirect_count",
        number: 170,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_driver_properties",
        number: 197,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_dynamic_rendering",
        number: 45,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_dynamic_rendering_local_read",
        number: 233,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_external_fence",
        number: 114,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_external_fence_capabilities",
        number: 113,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_external_fence_fd",
        number: 116,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_external_memory",
        number: 73,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_external_memory_capabilities",
        number: 72,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_external_memory_fd",
        number: 75,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_external_semaphore",
        number: 78,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_external_semaphore_capabilities",
        number: 77,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_external_semaphore_fd",
        number: 80,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_format_feature_flags2",
        number: 361,
        spec_version: 2,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_fragment_shader_barycentric",
        number: 323,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_fragment_shading_rate",
        number: 227,
        spec_version: 2,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_get_memory_requirements2",
        number: 147,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_get_physical_device_properties2",
        number: 60,
        spec_version: 2,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_global_priority",
        number: 189,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_image_format_list",
        number: 148,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_imageless_framebuffer",
        number: 109,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_index_type_uint8",
        number: 534,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_line_rasterization",
        number: 535,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_load_store_op_none",
        number: 527,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_maintenance1",
        number: 70,
        spec_version: 2,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_maintenance2",
        number: 118,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_maintenance3",
        number: 169,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_maintenance4",
        number: 414,
        spec_version: 2,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_maintenance5",
        number: 471,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_maintenance6",
        number: 546,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_maintenance7",
        number: 563,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_map_memory2",
        number: 272,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_multiview",
        number: 54,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_pipeline_library",
        number: 291,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_push_descriptor",
        number: 81,
        spec_version: 2,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_ray_query",
        number: 349,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_ray_tracing_maintenance1",
        number: 387,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_ray_tracing_pipeline",
        number: 348,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_ray_tracing_position_fetch",
        number: 482,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_relaxed_block_layout",
        number: 145,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_robustness2",
        number: 613,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_sampler_mirror_clamp_to_edge",
        number: 15,
        spec_version: 3,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_sampler_ycbcr_conversion",
        number: 157,
        spec_version: 14,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_separate_depth_stencil_layouts",
        number: 242,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_shader_atomic_int64",
        number: 181,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_shader_bfloat16",
        number: 142,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_shader_clock",
        number: 182,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_shader_draw_parameters",
        number: 64,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_shader_expect_assume",
        number: 545,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_shader_float16_int8",
        number: 83,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_shader_float_controls",
        number: 198,
        spec_version: 4,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_shader_float_controls2",
        number: 529,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_shader_fma",
        number: 580,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_shader_integer_dot_product",
        number: 281,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_shader_maximal_reconvergence",
        number: 435,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_shader_non_semantic_info",
        number: 294,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_shader_quad_control",
        number: 236,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_shader_relaxed_extended_instruction",
        number: 559,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_shader_subgroup_extended_types",
        number: 176,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_shader_subgroup_rotate",
        number: 417,
        spec_version: 2,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_shader_subgroup_uniform_control_flow",
        number: 324,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_shader_terminate_invocation",
        number: 216,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_shader_untyped_pointers",
        number: 388,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_spirv_1_4",
        number: 237,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_storage_buffer_storage_class",
        number: 132,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_synchronization2",
        number: 315,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_timeline_semaphore",
        number: 208,
        spec_version: 2,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_uniform_buffer_standard_layout",
        number: 254,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_variable_pointers",
        number: 121,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_vertex_attribute_divisor",
        number: 526,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_vulkan_memory_model",
        number: 212,
        spec_version: 3,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_workgroup_memory_explicit_layout",
        number: 337,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_KHR_zero_initialize_workgroup_memory",
        number: 326,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_MESA_venus_protocol",
        number: 385,
        spec_version: 4,
        decodable: true,
    },
    ExtensionInfo {
        name: "VK_NV_compute_shader_derivatives",
        number: 202,
        spec_version: 1,
        decodable: false,
    },
    ExtensionInfo {
        name: "VK_VALVE_mutable_descriptor_type",
        number: 352,
        spec_version: 1,
        decodable: false,
    },
];

/// `vk_extension_mask1` for exactly the decodable extensions, validity
/// sentinel (bit 0) set: the mask the capset should carry.
pub const DECODABLE_EXTENSION_MASK: [u32; 32] = [
    0x00000001, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000003, 0x00000000, 0x00000000, 0x00000000,
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
];

/// `vk_extension_mask1` for every extension in the protocol, sentinel set:
/// what virglrenderer's `vn_info_extension_mask_init` advertises. For
/// comparison only — this crate cannot decode most of it.
pub const PROTOCOL_EXTENSION_MASK: [u32; 32] = [
    0x2001c001, 0x30402000, 0x005f6bef, 0xc25660c0, 0xf0bb6919, 0xa2658e0c, 0x41310562, 0xf0e47a0f,
    0x9625b474, 0x0800054d, 0x30b70a5a, 0xc6000233, 0x5002073b, 0x000800ca, 0x008d0150, 0x08198004,
    0x00c2e001, 0x01288007, 0x20000090, 0x00000020, 0x00000008, 0x00000000, 0x00000000, 0x00000000,
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000000,
];

/// The table entry for `name`.
#[must_use]
pub fn extension(name: &str) -> Option<&'static ExtensionInfo> {
    EXTENSIONS
        .binary_search_by(|e| e.name.cmp(name))
        .ok()
        .and_then(|i| EXTENSIONS.get(i))
}

/// Registry numbers of the decodable extensions, for
/// `capset::ExtensionMask::enumerating`.
pub fn decodable_extension_numbers() -> impl Iterator<Item = u32> {
    EXTENSIONS.iter().filter(|e| e.decodable).map(|e| e.number)
}
