// @generated by tools/venus-protocol/rust_protocol.py (templates/rust_group.rs)
// from venus-protocol git-70991d4c. DO NOT EDIT: regenerate with
//     python scripts/venus-gen.py

//! The `instance` group: its commands and the structures only they reach.

#![allow(unused_imports)]

use super::*;
use crate::venus::wire::{CommandHeader, Decoder, Encoder};

/// `VkApplicationInfo` (`VK_STRUCTURE_TYPE_APPLICATION_INFO`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkApplicationInfo<'a> {
    /// `const char* pApplicationName`
    pub p_application_name: Option<&'a [u8]>,
    /// `uint32_t applicationVersion`
    pub application_version: u32,
    /// `const char* pEngineName`
    pub p_engine_name: Option<&'a [u8]>,
    /// `uint32_t engineVersion`
    pub engine_version: u32,
    /// `uint32_t apiVersion`
    pub api_version: u32,
}

impl<'a> VkApplicationInfo<'a> {
    // No output parameter reaches this structure, so it has no skeleton
    // form and the `partial` flag below is ignored.

    /// `VK_STRUCTURE_TYPE_APPLICATION_INFO`.
    pub const STRUCTURE_TYPE: i32 = VK_STRUCTURE_TYPE_APPLICATION_INFO;

    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'a>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// `decode` or `decode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'a>, partial: bool) -> Result<Self, ProtocolError> {
        expect_structure_type(dec, "VkApplicationInfo", Self::STRUCTURE_TYPE)?;
        dec.empty_pnext_chain("VkApplicationInfo")?;
        Self::decode_body(dec, partial)
    }

    /// `encode` or `encode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        enc.structure_type(Self::STRUCTURE_TYPE)?;
        enc.simple_pointer(false)?;
        self.encode_body(enc, partial)
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them
    /// (`vn_decode_VkApplicationInfo_self_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_body(dec: &mut Decoder<'a>, _partial: bool) -> Result<Self, ProtocolError> {
        let p_application_name: Option<&'a [u8]> = dec.opt_string()?;
        let application_version: u32 = dec.u32()?;
        let p_engine_name: Option<&'a [u8]> = dec.opt_string()?;
        let engine_version: u32 = dec.u32()?;
        let api_version: u32 = dec.u32()?;
        Ok(Self {
            p_application_name,
            application_version,
            p_engine_name,
            engine_version,
            api_version,
        })
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_body(&self, enc: &mut Encoder, _partial: bool) -> Result<(), ProtocolError> {
        enc.opt_string(self.p_application_name)?;
        enc.u32(self.application_version)?;
        enc.opt_string(self.p_engine_name)?;
        enc.u32(self.engine_version)?;
        enc.u32(self.api_version)?;
        Ok(())
    }
}

/// `VkInstanceCreateInfo` (`VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkInstanceCreateInfo<'a> {
    /// `VkInstanceCreateFlags flags`
    pub flags: VkInstanceCreateFlags,
    /// `const VkApplicationInfo* pApplicationInfo`
    pub p_application_info: Option<VkApplicationInfo<'a>>,
    /// `uint32_t enabledLayerCount`
    pub enabled_layer_count: u32,
    /// `const char* const* ppEnabledLayerNames`
    pub pp_enabled_layer_names: Option<Vec<&'a [u8]>>,
    /// `uint32_t enabledExtensionCount`
    pub enabled_extension_count: u32,
    /// `const char* const* ppEnabledExtensionNames`
    pub pp_enabled_extension_names: Option<Vec<&'a [u8]>>,
}

impl<'a> VkInstanceCreateInfo<'a> {
    // No output parameter reaches this structure, so it has no skeleton
    // form and the `partial` flag below is ignored.

    /// `VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO`.
    pub const STRUCTURE_TYPE: i32 = VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO;

    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'a>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// `decode` or `decode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'a>, partial: bool) -> Result<Self, ProtocolError> {
        expect_structure_type(dec, "VkInstanceCreateInfo", Self::STRUCTURE_TYPE)?;
        dec.empty_pnext_chain("VkInstanceCreateInfo")?;
        Self::decode_body(dec, partial)
    }

    /// `encode` or `encode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        enc.structure_type(Self::STRUCTURE_TYPE)?;
        enc.simple_pointer(false)?;
        self.encode_body(enc, partial)
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them
    /// (`vn_decode_VkInstanceCreateInfo_self_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_body(dec: &mut Decoder<'a>, _partial: bool) -> Result<Self, ProtocolError> {
        let flags: VkInstanceCreateFlags = dec.u32()?;
        let p_application_info: Option<VkApplicationInfo<'a>> = if dec.simple_pointer()? {
            Some(VkApplicationInfo::decode_with(dec, false)?)
        } else {
            None
        };
        let enabled_layer_count: u32 = dec.u32()?;
        let pp_enabled_layer_names: Option<Vec<&'a [u8]>> =
            match array_presence(dec, u64::from(enabled_layer_count), NullArray::Checked)? {
                Some(n) => Some(decode_vec(dec, n, decode_string_element)?),
                None => None,
            };
        let enabled_extension_count: u32 = dec.u32()?;
        let pp_enabled_extension_names: Option<Vec<&'a [u8]>> =
            match array_presence(dec, u64::from(enabled_extension_count), NullArray::Checked)? {
                Some(n) => Some(decode_vec(dec, n, decode_string_element)?),
                None => None,
            };
        Ok(Self {
            flags,
            p_application_info,
            enabled_layer_count,
            pp_enabled_layer_names,
            enabled_extension_count,
            pp_enabled_extension_names,
        })
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_body(&self, enc: &mut Encoder, _partial: bool) -> Result<(), ProtocolError> {
        enc.u32(self.flags)?;
        enc.simple_pointer(self.p_application_info.is_some())?;
        if let Some(v) = &self.p_application_info {
            v.encode_with(enc, false)?;
        }
        enc.u32(self.enabled_layer_count)?;
        if let Some(v) = &self.pp_enabled_layer_names {
            let count = u64::from(self.enabled_layer_count);
            check_len(
                "VkInstanceCreateInfo",
                "ppEnabledLayerNames",
                count,
                v.len(),
            )?;
            enc.array_size(count)?;
            for e in v {
                enc.opt_string(Some(e))?;
            }
        } else {
            enc.array_size(0)?;
        }
        enc.u32(self.enabled_extension_count)?;
        if let Some(v) = &self.pp_enabled_extension_names {
            let count = u64::from(self.enabled_extension_count);
            check_len(
                "VkInstanceCreateInfo",
                "ppEnabledExtensionNames",
                count,
                v.len(),
            )?;
            enc.array_size(count)?;
            for e in v {
                enc.opt_string(Some(e))?;
            }
        } else {
            enc.array_size(0)?;
        }
        Ok(())
    }
}

/// The arguments of `vkCreateInstance`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place and sets `ret`, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct CreateInstanceArgs<'a> {
    /// `const VkInstanceCreateInfo* pCreateInfo` — in.
    pub p_create_info: Option<VkInstanceCreateInfo<'a>>,
    /// `VkInstance* pInstance` — out.
    pub p_instance: Option<VkInstance>,
    /// The return value (`VkResult`), written first in the reply.
    pub ret: VkResult,
}

impl<'a> CreateInstanceArgs<'a> {
    /// `VK_COMMAND_TYPE_vkCreateInstance_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_CREATE_INSTANCE_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkCreateInstance";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkCreateInstance_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'a>) -> Result<Self, ProtocolError> {
        let p_create_info: Option<VkInstanceCreateInfo<'a>> = if dec.simple_pointer()? {
            Some(VkInstanceCreateInfo::decode_with(dec, false)?)
        } else {
            return Err(null_pointer(dec, "vkCreateInstance", "pCreateInfo"));
        };
        dec.null_allocator()?;
        let p_instance: Option<VkInstance> = if dec.simple_pointer()? {
            Some(VkInstance(dec.handle()?))
        } else {
            return Err(null_pointer(dec, "vkCreateInstance", "pInstance"));
        };
        Ok(Self {
            p_create_info,
            p_instance,
            ret: Default::default(),
        })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkCreateInstance`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.simple_pointer(self.p_create_info.is_some())?;
        if let Some(v) = &self.p_create_info {
            v.encode_with(enc, false)?;
        }
        enc.null_allocator()?;
        enc.simple_pointer(self.p_instance.is_some())?;
        if let Some(v) = &self.p_instance {
            enc.handle(v.0)?;
        }
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkCreateInstance_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        enc.i32(self.ret)?;
        enc.simple_pointer(self.p_instance.is_some())?;
        if let Some(v) = &self.p_instance {
            enc.handle(v.0)?;
        }
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkCreateInstance_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'a>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        self.ret = dec.i32()?;
        self.p_instance = if dec.simple_pointer()? {
            Some(VkInstance(dec.handle()?))
        } else {
            None
        };
        Ok(())
    }
}

/// The arguments of `vkDestroyInstance`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct DestroyInstanceArgs {
    /// `VkInstance instance` — in.
    pub instance: VkInstance,
}

impl DestroyInstanceArgs {
    /// `VK_COMMAND_TYPE_vkDestroyInstance_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_DESTROY_INSTANCE_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkDestroyInstance";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkDestroyInstance_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        let instance: VkInstance = VkInstance(dec.handle()?);
        if instance.0 == 0 {
            return Err(null_dispatch_handle(dec, "vkDestroyInstance"));
        }
        dec.null_allocator()?;
        Ok(Self { instance })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkDestroyInstance`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.handle(self.instance.0)?;
        enc.null_allocator()?;
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkDestroyInstance_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkDestroyInstance_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'_>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        Ok(())
    }
}

/// The arguments of `vkEnumerateInstanceVersion`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place and sets `ret`, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct EnumerateInstanceVersionArgs {
    /// `uint32_t* pApiVersion` — out.
    pub p_api_version: Option<u32>,
    /// The return value (`VkResult`), written first in the reply.
    pub ret: VkResult,
}

impl EnumerateInstanceVersionArgs {
    /// `VK_COMMAND_TYPE_vkEnumerateInstanceVersion_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_ENUMERATE_INSTANCE_VERSION_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkEnumerateInstanceVersion";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkEnumerateInstanceVersion_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        let p_api_version: Option<u32> = if dec.simple_pointer()? {
            Some(Default::default())
        } else {
            return Err(null_pointer(
                dec,
                "vkEnumerateInstanceVersion",
                "pApiVersion",
            ));
        };
        Ok(Self {
            p_api_version,
            ret: Default::default(),
        })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkEnumerateInstanceVersion`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.simple_pointer(self.p_api_version.is_some())?;
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkEnumerateInstanceVersion_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        enc.i32(self.ret)?;
        enc.simple_pointer(self.p_api_version.is_some())?;
        if let Some(v) = &self.p_api_version {
            enc.u32(*v)?;
        }
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkEnumerateInstanceVersion_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'_>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        self.ret = dec.i32()?;
        self.p_api_version = if dec.simple_pointer()? {
            Some(dec.u32()?)
        } else {
            None
        };
        Ok(())
    }
}
