// @generated by tools/venus-protocol/rust_protocol.py (templates/rust_group.rs)
// from venus-protocol git-70991d4c. DO NOT EDIT: regenerate with
//     python scripts/venus-gen.py

//! The `pipeline_cache` group: its commands and the structures only they reach.

#![allow(unused_imports)]

use super::*;
use crate::venus::wire::{CommandHeader, Decoder, Encoder};

/// `VkPipelineCacheCreateInfo` (`VK_STRUCTURE_TYPE_PIPELINE_CACHE_CREATE_INFO`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkPipelineCacheCreateInfo<'a> {
    /// `VkPipelineCacheCreateFlags flags`
    pub flags: VkPipelineCacheCreateFlags,
    /// `size_t initialDataSize`
    pub initial_data_size: u64,
    /// `const void* pInitialData`
    pub p_initial_data: Option<&'a [u8]>,
}

impl<'a> VkPipelineCacheCreateInfo<'a> {
    // No output parameter reaches this structure, so it has no skeleton
    // form and the `partial` flag below is ignored.

    /// `VK_STRUCTURE_TYPE_PIPELINE_CACHE_CREATE_INFO`.
    pub const STRUCTURE_TYPE: i32 = VK_STRUCTURE_TYPE_PIPELINE_CACHE_CREATE_INFO;

    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'a>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// `decode` or `decode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'a>, partial: bool) -> Result<Self, ProtocolError> {
        expect_structure_type(dec, "VkPipelineCacheCreateInfo", Self::STRUCTURE_TYPE)?;
        dec.empty_pnext_chain("VkPipelineCacheCreateInfo")?;
        Self::decode_body(dec, partial)
    }

    /// `encode` or `encode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        enc.structure_type(Self::STRUCTURE_TYPE)?;
        enc.simple_pointer(false)?;
        self.encode_body(enc, partial)
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them
    /// (`vn_decode_VkPipelineCacheCreateInfo_self_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_body(dec: &mut Decoder<'a>, _partial: bool) -> Result<Self, ProtocolError> {
        let flags: VkPipelineCacheCreateFlags = dec.u32()?;
        let initial_data_size: u64 = dec.size()?;
        let p_initial_data: Option<&'a [u8]> =
            match array_presence(dec, initial_data_size, NullArray::Checked)? {
                Some(n) => Some(dec.blob(n)?),
                None => None,
            };
        Ok(Self {
            flags,
            initial_data_size,
            p_initial_data,
        })
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_body(&self, enc: &mut Encoder, _partial: bool) -> Result<(), ProtocolError> {
        enc.u32(self.flags)?;
        enc.size(self.initial_data_size)?;
        if let Some(v) = &self.p_initial_data {
            let count = self.initial_data_size;
            check_len("VkPipelineCacheCreateInfo", "pInitialData", count, v.len())?;
            enc.array_size(count)?;
            enc.blob(v)?;
        } else {
            enc.array_size(0)?;
        }
        Ok(())
    }
}

/// The arguments of `vkCreatePipelineCache`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place and sets `ret`, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct CreatePipelineCacheArgs<'a> {
    /// `VkDevice device` — in.
    pub device: VkDevice,
    /// `const VkPipelineCacheCreateInfo* pCreateInfo` — in.
    pub p_create_info: Option<VkPipelineCacheCreateInfo<'a>>,
    /// `VkPipelineCache* pPipelineCache` — out.
    pub p_pipeline_cache: Option<VkPipelineCache>,
    /// The return value (`VkResult`), written first in the reply.
    pub ret: VkResult,
}

impl<'a> CreatePipelineCacheArgs<'a> {
    /// `VK_COMMAND_TYPE_vkCreatePipelineCache_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_CREATE_PIPELINE_CACHE_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkCreatePipelineCache";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkCreatePipelineCache_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'a>) -> Result<Self, ProtocolError> {
        let device: VkDevice = VkDevice(dec.handle()?);
        if device.0 == 0 {
            return Err(null_dispatch_handle(dec, "vkCreatePipelineCache"));
        }
        let p_create_info: Option<VkPipelineCacheCreateInfo<'a>> = if dec.simple_pointer()? {
            Some(VkPipelineCacheCreateInfo::decode_with(dec, false)?)
        } else {
            return Err(null_pointer(dec, "vkCreatePipelineCache", "pCreateInfo"));
        };
        dec.null_allocator()?;
        let p_pipeline_cache: Option<VkPipelineCache> = if dec.simple_pointer()? {
            Some(VkPipelineCache(dec.handle()?))
        } else {
            return Err(null_pointer(dec, "vkCreatePipelineCache", "pPipelineCache"));
        };
        Ok(Self {
            device,
            p_create_info,
            p_pipeline_cache,
            ret: Default::default(),
        })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkCreatePipelineCache`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.handle(self.device.0)?;
        enc.simple_pointer(self.p_create_info.is_some())?;
        if let Some(v) = &self.p_create_info {
            v.encode_with(enc, false)?;
        }
        enc.null_allocator()?;
        enc.simple_pointer(self.p_pipeline_cache.is_some())?;
        if let Some(v) = &self.p_pipeline_cache {
            enc.handle(v.0)?;
        }
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkCreatePipelineCache_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        enc.i32(self.ret)?;
        enc.simple_pointer(self.p_pipeline_cache.is_some())?;
        if let Some(v) = &self.p_pipeline_cache {
            enc.handle(v.0)?;
        }
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkCreatePipelineCache_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'a>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        self.ret = dec.i32()?;
        self.p_pipeline_cache = if dec.simple_pointer()? {
            Some(VkPipelineCache(dec.handle()?))
        } else {
            None
        };
        Ok(())
    }
}

/// The arguments of `vkDestroyPipelineCache`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct DestroyPipelineCacheArgs {
    /// `VkDevice device` — in.
    pub device: VkDevice,
    /// `VkPipelineCache pipelineCache` — in.
    pub pipeline_cache: VkPipelineCache,
}

impl DestroyPipelineCacheArgs {
    /// `VK_COMMAND_TYPE_vkDestroyPipelineCache_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_DESTROY_PIPELINE_CACHE_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkDestroyPipelineCache";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkDestroyPipelineCache_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        let device: VkDevice = VkDevice(dec.handle()?);
        if device.0 == 0 {
            return Err(null_dispatch_handle(dec, "vkDestroyPipelineCache"));
        }
        let pipeline_cache: VkPipelineCache = VkPipelineCache(dec.handle()?);
        dec.null_allocator()?;
        Ok(Self {
            device,
            pipeline_cache,
        })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkDestroyPipelineCache`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.handle(self.device.0)?;
        enc.handle(self.pipeline_cache.0)?;
        enc.null_allocator()?;
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkDestroyPipelineCache_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkDestroyPipelineCache_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'_>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        Ok(())
    }
}

/// The arguments of `vkGetPipelineCacheData`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place and sets `ret`, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct GetPipelineCacheDataArgs {
    /// `VkDevice device` — in.
    pub device: VkDevice,
    /// `VkPipelineCache pipelineCache` — in.
    pub pipeline_cache: VkPipelineCache,
    /// `size_t* pDataSize` — in/out.
    pub p_data_size: Option<u64>,
    /// `void* pData` — out.
    pub p_data: Option<Vec<u8>>,
    /// The return value (`VkResult`), written first in the reply.
    pub ret: VkResult,
}

impl GetPipelineCacheDataArgs {
    /// `VK_COMMAND_TYPE_vkGetPipelineCacheData_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_GET_PIPELINE_CACHE_DATA_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkGetPipelineCacheData";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkGetPipelineCacheData_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        let device: VkDevice = VkDevice(dec.handle()?);
        if device.0 == 0 {
            return Err(null_dispatch_handle(dec, "vkGetPipelineCacheData"));
        }
        let pipeline_cache: VkPipelineCache = VkPipelineCache(dec.handle()?);
        let p_data_size: Option<u64> = if dec.simple_pointer()? {
            Some(dec.size()?)
        } else {
            return Err(null_pointer(dec, "vkGetPipelineCacheData", "pDataSize"));
        };
        let p_data: Option<Vec<u8>> =
            array_presence(dec, p_data_size.unwrap_or(0), NullArray::Unchecked)?
                .map(|_| Vec::new());
        Ok(Self {
            device,
            pipeline_cache,
            p_data_size,
            p_data,
            ret: Default::default(),
        })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkGetPipelineCacheData`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.handle(self.device.0)?;
        enc.handle(self.pipeline_cache.0)?;
        enc.simple_pointer(self.p_data_size.is_some())?;
        if let Some(v) = &self.p_data_size {
            enc.size(*v)?;
        }
        enc.array_size(if self.p_data.is_some() {
            self.p_data_size.unwrap_or(0)
        } else {
            0
        })?;
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkGetPipelineCacheData_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        enc.i32(self.ret)?;
        enc.simple_pointer(self.p_data_size.is_some())?;
        if let Some(v) = &self.p_data_size {
            enc.size(*v)?;
        }
        if let Some(v) = &self.p_data {
            let count = self.p_data_size.unwrap_or(0);
            check_len("vkGetPipelineCacheData", "pData", count, v.len())?;
            enc.array_size(count)?;
            enc.blob(v)?;
        } else {
            enc.array_size(0)?;
        }
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkGetPipelineCacheData_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'_>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        self.ret = dec.i32()?;
        self.p_data_size = if dec.simple_pointer()? {
            Some(dec.size()?)
        } else {
            None
        };
        self.p_data =
            match array_presence(dec, self.p_data_size.unwrap_or(0), NullArray::Unchecked)? {
                Some(n) => Some(decode_owned_blob(dec, n)?),
                None => None,
            };
        Ok(())
    }
}

/// The arguments of `vkMergePipelineCaches`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place and sets `ret`, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct MergePipelineCachesArgs {
    /// `VkDevice device` — in.
    pub device: VkDevice,
    /// `VkPipelineCache dstCache` — in.
    pub dst_cache: VkPipelineCache,
    /// `uint32_t srcCacheCount` — in.
    pub src_cache_count: u32,
    /// `const VkPipelineCache* pSrcCaches` — in.
    pub p_src_caches: Option<Vec<VkPipelineCache>>,
    /// The return value (`VkResult`), written first in the reply.
    pub ret: VkResult,
}

impl MergePipelineCachesArgs {
    /// `VK_COMMAND_TYPE_vkMergePipelineCaches_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_MERGE_PIPELINE_CACHES_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkMergePipelineCaches";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkMergePipelineCaches_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        let device: VkDevice = VkDevice(dec.handle()?);
        if device.0 == 0 {
            return Err(null_dispatch_handle(dec, "vkMergePipelineCaches"));
        }
        let dst_cache: VkPipelineCache = VkPipelineCache(dec.handle()?);
        let src_cache_count: u32 = dec.u32()?;
        let p_src_caches: Option<Vec<VkPipelineCache>> =
            match array_presence(dec, u64::from(src_cache_count), NullArray::Checked)? {
                Some(n) => Some(decode_vec(dec, n, |dec| {
                    dec.handle()
                        .map(VkPipelineCache)
                        .map_err(ProtocolError::from)
                })?),
                None => None,
            };
        Ok(Self {
            device,
            dst_cache,
            src_cache_count,
            p_src_caches,
            ret: Default::default(),
        })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkMergePipelineCaches`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.handle(self.device.0)?;
        enc.handle(self.dst_cache.0)?;
        enc.u32(self.src_cache_count)?;
        if let Some(v) = &self.p_src_caches {
            let count = u64::from(self.src_cache_count);
            check_len("vkMergePipelineCaches", "pSrcCaches", count, v.len())?;
            enc.array_size(count)?;
            for e in v {
                enc.handle(e.0)?;
            }
        } else {
            enc.array_size(0)?;
        }
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkMergePipelineCaches_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        enc.i32(self.ret)?;
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkMergePipelineCaches_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'_>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        self.ret = dec.i32()?;
        Ok(())
    }
}
