// @generated by tools/venus-protocol/rust_protocol.py (templates/rust_group.rs)
// from venus-protocol git-70991d4c. DO NOT EDIT: regenerate with
//     python scripts/venus-gen.py

//! The `sampler_ycbcr_conversion` group: its commands and the structures only they reach.

#![allow(unused_imports)]

use super::*;
use crate::venus::wire::{CommandHeader, Decoder, Encoder};

/// `VkSamplerYcbcrConversionCreateInfo` (`VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_CREATE_INFO`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkSamplerYcbcrConversionCreateInfo {
    /// `VkFormat format`
    pub format: VkFormat,
    /// `VkSamplerYcbcrModelConversion ycbcrModel`
    pub ycbcr_model: VkSamplerYcbcrModelConversion,
    /// `VkSamplerYcbcrRange ycbcrRange`
    pub ycbcr_range: VkSamplerYcbcrRange,
    /// `VkComponentMapping components`
    pub components: VkComponentMapping,
    /// `VkChromaLocation xChromaOffset`
    pub x_chroma_offset: VkChromaLocation,
    /// `VkChromaLocation yChromaOffset`
    pub y_chroma_offset: VkChromaLocation,
    /// `VkFilter chromaFilter`
    pub chroma_filter: VkFilter,
    /// `VkBool32 forceExplicitReconstruction`
    pub force_explicit_reconstruction: VkBool32,
}

impl VkSamplerYcbcrConversionCreateInfo {
    // No output parameter reaches this structure, so it has no skeleton
    // form and the `partial` flag below is ignored.

    /// `VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_CREATE_INFO`.
    pub const STRUCTURE_TYPE: i32 = VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_CREATE_INFO;

    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// `decode` or `decode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        expect_structure_type(
            dec,
            "VkSamplerYcbcrConversionCreateInfo",
            Self::STRUCTURE_TYPE,
        )?;
        dec.empty_pnext_chain("VkSamplerYcbcrConversionCreateInfo")?;
        Self::decode_body(dec, partial)
    }

    /// `encode` or `encode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        enc.structure_type(Self::STRUCTURE_TYPE)?;
        enc.simple_pointer(false)?;
        self.encode_body(enc, partial)
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them
    /// (`vn_decode_VkSamplerYcbcrConversionCreateInfo_self_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_body(dec: &mut Decoder<'_>, _partial: bool) -> Result<Self, ProtocolError> {
        let format: VkFormat = dec.i32()?;
        let ycbcr_model: VkSamplerYcbcrModelConversion = dec.i32()?;
        let ycbcr_range: VkSamplerYcbcrRange = dec.i32()?;
        let components: VkComponentMapping = VkComponentMapping::decode_with(dec, false)?;
        let x_chroma_offset: VkChromaLocation = dec.i32()?;
        let y_chroma_offset: VkChromaLocation = dec.i32()?;
        let chroma_filter: VkFilter = dec.i32()?;
        let force_explicit_reconstruction: VkBool32 = dec.u32()?;
        Ok(Self {
            format,
            ycbcr_model,
            ycbcr_range,
            components,
            x_chroma_offset,
            y_chroma_offset,
            chroma_filter,
            force_explicit_reconstruction,
        })
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_body(&self, enc: &mut Encoder, _partial: bool) -> Result<(), ProtocolError> {
        enc.i32(self.format)?;
        enc.i32(self.ycbcr_model)?;
        enc.i32(self.ycbcr_range)?;
        self.components.encode_with(enc, false)?;
        enc.i32(self.x_chroma_offset)?;
        enc.i32(self.y_chroma_offset)?;
        enc.i32(self.chroma_filter)?;
        enc.u32(self.force_explicit_reconstruction)?;
        Ok(())
    }
}

/// The arguments of `vkCreateSamplerYcbcrConversion`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place and sets `ret`, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct CreateSamplerYcbcrConversionArgs {
    /// `VkDevice device` — in.
    pub device: VkDevice,
    /// `const VkSamplerYcbcrConversionCreateInfo* pCreateInfo` — in.
    pub p_create_info: Option<VkSamplerYcbcrConversionCreateInfo>,
    /// `VkSamplerYcbcrConversion* pYcbcrConversion` — out.
    pub p_ycbcr_conversion: Option<VkSamplerYcbcrConversion>,
    /// The return value (`VkResult`), written first in the reply.
    pub ret: VkResult,
}

impl CreateSamplerYcbcrConversionArgs {
    /// `VK_COMMAND_TYPE_vkCreateSamplerYcbcrConversion_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_CREATE_SAMPLER_YCBCR_CONVERSION_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkCreateSamplerYcbcrConversion";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkCreateSamplerYcbcrConversion_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        let device: VkDevice = VkDevice(dec.handle()?);
        if device.0 == 0 {
            return Err(null_dispatch_handle(dec, "vkCreateSamplerYcbcrConversion"));
        }
        let p_create_info: Option<VkSamplerYcbcrConversionCreateInfo> = if dec.simple_pointer()? {
            Some(VkSamplerYcbcrConversionCreateInfo::decode_with(dec, false)?)
        } else {
            return Err(null_pointer(
                dec,
                "vkCreateSamplerYcbcrConversion",
                "pCreateInfo",
            ));
        };
        dec.null_allocator()?;
        let p_ycbcr_conversion: Option<VkSamplerYcbcrConversion> = if dec.simple_pointer()? {
            Some(VkSamplerYcbcrConversion(dec.handle()?))
        } else {
            return Err(null_pointer(
                dec,
                "vkCreateSamplerYcbcrConversion",
                "pYcbcrConversion",
            ));
        };
        Ok(Self {
            device,
            p_create_info,
            p_ycbcr_conversion,
            ret: Default::default(),
        })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkCreateSamplerYcbcrConversion`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.handle(self.device.0)?;
        enc.simple_pointer(self.p_create_info.is_some())?;
        if let Some(v) = &self.p_create_info {
            v.encode_with(enc, false)?;
        }
        enc.null_allocator()?;
        enc.simple_pointer(self.p_ycbcr_conversion.is_some())?;
        if let Some(v) = &self.p_ycbcr_conversion {
            enc.handle(v.0)?;
        }
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkCreateSamplerYcbcrConversion_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        enc.i32(self.ret)?;
        enc.simple_pointer(self.p_ycbcr_conversion.is_some())?;
        if let Some(v) = &self.p_ycbcr_conversion {
            enc.handle(v.0)?;
        }
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkCreateSamplerYcbcrConversion_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'_>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        self.ret = dec.i32()?;
        self.p_ycbcr_conversion = if dec.simple_pointer()? {
            Some(VkSamplerYcbcrConversion(dec.handle()?))
        } else {
            None
        };
        Ok(())
    }
}

/// The arguments of `vkDestroySamplerYcbcrConversion`, and its reply.
///
/// Inputs are as the guest sent them. Outputs are as the guest *sized*
/// them: present or null, output handles carrying the guest's chosen id,
/// output structures carrying their `sType` and chain skeleton. The executor
/// fills the outputs in place, then
/// [`Self::encode_reply`] writes them back.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct DestroySamplerYcbcrConversionArgs {
    /// `VkDevice device` — in.
    pub device: VkDevice,
    /// `VkSamplerYcbcrConversion ycbcrConversion` — in.
    pub ycbcr_conversion: VkSamplerYcbcrConversion,
}

impl DestroySamplerYcbcrConversionArgs {
    /// `VK_COMMAND_TYPE_vkDestroySamplerYcbcrConversion_EXT`.
    pub const OPCODE: u32 = VK_COMMAND_TYPE_DESTROY_SAMPLER_YCBCR_CONVERSION_EXT;

    /// The command's registry name.
    pub const NAME: &'static str = "vkDestroySamplerYcbcrConversion";

    /// Decode the arguments that follow the 8-byte command header
    /// (`vn_decode_vkDestroySamplerYcbcrConversion_args_temp`).
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        let device: VkDevice = VkDevice(dec.handle()?);
        if device.0 == 0 {
            return Err(null_dispatch_handle(dec, "vkDestroySamplerYcbcrConversion"));
        }
        let ycbcr_conversion: VkSamplerYcbcrConversion = VkSamplerYcbcrConversion(dec.handle()?);
        dec.null_allocator()?;
        Ok(Self {
            device,
            ycbcr_conversion,
        })
    }

    /// Encode the command as the guest's driver does, header included
    /// (`vn_encode_vkDestroySamplerYcbcrConversion`): outputs as skeletons.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode_command(&self, enc: &mut Encoder, flags: u32) -> Result<(), ProtocolError> {
        enc.command_header(CommandHeader {
            opcode: Self::OPCODE,
            flags,
        })?;
        enc.handle(self.device.0)?;
        enc.handle(self.ycbcr_conversion.0)?;
        enc.null_allocator()?;
        Ok(())
    }

    /// Encode the reply (`vn_encode_vkDestroySamplerYcbcrConversion_reply`): the opcode, the
    /// return value if any, then every output parameter.
    ///
    /// On `Err` the encoder holds a partial reply and must be dropped.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an output array that disagrees with
    /// its count.
    pub fn encode_reply(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        enc.reply_header(Self::OPCODE)?;
        Ok(())
    }

    /// Decode a reply into this command's outputs, as the guest's driver
    /// does (`vn_decode_vkDestroySamplerYcbcrConversion_reply`): arrays in a reply are never
    /// cross-checked in their null branch, and a null output is not fatal.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused.
    pub fn decode_reply(&mut self, dec: &mut Decoder<'_>) -> Result<(), ProtocolError> {
        let found = dec.reply_header()?;
        if found != Self::OPCODE {
            dec.set_fatal(crate::venus::wire::WireError::Poisoned);
            return Err(ProtocolError::WrongReplyOpcode {
                expected: Self::OPCODE,
                found,
            });
        }
        Ok(())
    }
}
