// @generated by tools/venus-protocol/rust_protocol.py (templates/rust_group.rs)
// from venus-protocol git-70991d4c. DO NOT EDIT: regenerate with
//     python scripts/venus-gen.py

//! Structures shared by more than one command group.

#![allow(unused_imports)]

use super::*;
use crate::venus::wire::{CommandHeader, Decoder, Encoder};

/// `VkExtent3D`.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkExtent3D {
    /// `uint32_t width`
    pub width: u32,
    /// `uint32_t height`
    pub height: u32,
    /// `uint32_t depth`
    pub depth: u32,
}

impl VkExtent3D {
    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Decode the skeleton an output structure is sent as inside a command
    /// (`vn_decode_VkExtent3D_partial_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_partial(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, true)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// Encode the skeleton form (`vn_encode_VkExtent3D_partial`).
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_partial(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, true)
    }

    /// `decode` or `decode_partial`.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        let width: u32 = if partial {
            Default::default()
        } else {
            dec.u32()?
        };
        let height: u32 = if partial {
            Default::default()
        } else {
            dec.u32()?
        };
        let depth: u32 = if partial {
            Default::default()
        } else {
            dec.u32()?
        };
        Ok(Self {
            width,
            height,
            depth,
        })
    }

    /// `encode` or `encode_partial`.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        if !partial {
            enc.u32(self.width)?;
        }
        if !partial {
            enc.u32(self.height)?;
        }
        if !partial {
            enc.u32(self.depth)?;
        }
        Ok(())
    }
}

/// `VkImageFormatListCreateInfo` (`VK_STRUCTURE_TYPE_IMAGE_FORMAT_LIST_CREATE_INFO`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkImageFormatListCreateInfo {
    /// `uint32_t viewFormatCount`
    pub view_format_count: u32,
    /// `const VkFormat* pViewFormats`
    pub p_view_formats: Option<Vec<VkFormat>>,
}

impl VkImageFormatListCreateInfo {
    // No output parameter reaches this structure, so it has no skeleton
    // form and the `partial` flag below is ignored.

    /// `VK_STRUCTURE_TYPE_IMAGE_FORMAT_LIST_CREATE_INFO`.
    pub const STRUCTURE_TYPE: i32 = VK_STRUCTURE_TYPE_IMAGE_FORMAT_LIST_CREATE_INFO;

    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// `decode` or `decode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        expect_structure_type(dec, "VkImageFormatListCreateInfo", Self::STRUCTURE_TYPE)?;
        dec.empty_pnext_chain("VkImageFormatListCreateInfo")?;
        Self::decode_body(dec, partial)
    }

    /// `encode` or `encode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        enc.structure_type(Self::STRUCTURE_TYPE)?;
        enc.simple_pointer(false)?;
        self.encode_body(enc, partial)
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them
    /// (`vn_decode_VkImageFormatListCreateInfo_self_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_body(dec: &mut Decoder<'_>, _partial: bool) -> Result<Self, ProtocolError> {
        let view_format_count: u32 = dec.u32()?;
        let p_view_formats: Option<Vec<VkFormat>> =
            match array_presence(dec, u64::from(view_format_count), NullArray::Checked)? {
                Some(n) => Some(decode_vec(dec, n, |dec| {
                    dec.i32().map_err(ProtocolError::from)
                })?),
                None => None,
            };
        Ok(Self {
            view_format_count,
            p_view_formats,
        })
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_body(&self, enc: &mut Encoder, _partial: bool) -> Result<(), ProtocolError> {
        enc.u32(self.view_format_count)?;
        if let Some(v) = &self.p_view_formats {
            let count = u64::from(self.view_format_count);
            check_len(
                "VkImageFormatListCreateInfo",
                "pViewFormats",
                count,
                v.len(),
            )?;
            enc.array_size(count)?;
            for e in v {
                enc.i32(*e)?;
            }
        } else {
            enc.array_size(0)?;
        }
        Ok(())
    }
}

/// `VkImageStencilUsageCreateInfo` (`VK_STRUCTURE_TYPE_IMAGE_STENCIL_USAGE_CREATE_INFO`).
#[derive(Debug, Clone, PartialEq, Default)]
pub struct VkImageStencilUsageCreateInfo {
    /// `VkImageUsageFlags stencilUsage`
    pub stencil_usage: VkImageUsageFlags,
}

impl VkImageStencilUsageCreateInfo {
    // No output parameter reaches this structure, so it has no skeleton
    // form and the `partial` flag below is ignored.

    /// `VK_STRUCTURE_TYPE_IMAGE_STENCIL_USAGE_CREATE_INFO`.
    pub const STRUCTURE_TYPE: i32 = VK_STRUCTURE_TYPE_IMAGE_STENCIL_USAGE_CREATE_INFO;

    /// Decode the whole structure, as an input carries it.
    ///
    /// # Errors
    /// Whatever the wire or this layer refused; `dec` is left fatal.
    pub fn decode(dec: &mut Decoder<'_>) -> Result<Self, ProtocolError> {
        Self::decode_with(dec, false)
    }

    /// Encode the whole structure, as a reply carries it.
    ///
    /// # Errors
    /// Whatever the encoder refused, or an array that disagrees with its count.
    pub fn encode(&self, enc: &mut Encoder) -> Result<(), ProtocolError> {
        self.encode_with(enc, false)
    }

    /// `decode` or `decode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_with(dec: &mut Decoder<'_>, partial: bool) -> Result<Self, ProtocolError> {
        expect_structure_type(dec, "VkImageStencilUsageCreateInfo", Self::STRUCTURE_TYPE)?;
        dec.empty_pnext_chain("VkImageStencilUsageCreateInfo")?;
        Self::decode_body(dec, partial)
    }

    /// `encode` or `encode_partial`: `sType`, the pNext chain, the body.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_with(&self, enc: &mut Encoder, partial: bool) -> Result<(), ProtocolError> {
        enc.structure_type(Self::STRUCTURE_TYPE)?;
        enc.simple_pointer(false)?;
        self.encode_body(enc, partial)
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them
    /// (`vn_decode_VkImageStencilUsageCreateInfo_self_temp`).
    ///
    /// # Errors
    /// As [`Self::decode`].
    pub fn decode_body(dec: &mut Decoder<'_>, _partial: bool) -> Result<Self, ProtocolError> {
        let stencil_usage: VkImageUsageFlags = dec.u32()?;
        Ok(Self { stencil_usage })
    }

    /// The fields after `sType` and `pNext`, as a chain link carries them.
    ///
    /// # Errors
    /// As [`Self::encode`].
    pub fn encode_body(&self, enc: &mut Encoder, _partial: bool) -> Result<(), ProtocolError> {
        enc.u32(self.stencil_usage)?;
        Ok(())
    }
}
