//! The host's real Vulkan, through `ash`: the one implementation of the Venus
//! executor's [`HostVulkan`] trait (EPIC 20 stage 5a.3, ADR-0004).
//!
//! # Loaded, not linked
//!
//! [`AshVulkan::load`] opens the system's Vulkan loader at run time
//! (`ash::Entry::load`: `vulkan-1.dll` on Windows, `libvulkan.so.1` on
//! Linux). Nothing links against it, so a host with no Vulkan at all builds,
//! runs and passes its tests; it simply cannot offer the executing renderer,
//! and `entangled run` says so before a guest ever boots.
//!
//! # Why this is outside `venus`
//!
//! Every Vulkan call is `unsafe`, and the `venus` module family keeps its one
//! `unsafe` in `venus::shmem`. So the executor, the object table and every
//! policy live there and see only the trait; this module is the only code
//! that turns a validated protocol value into a driver structure, and every
//! `unsafe` block in it says what makes that one call sound.
//!
//! What a call's soundness rests on, once, so each `SAFETY` comment can be
//! short:
//!
//! * **Handles are ours.** Every instance, physical device, device and child
//!   handle passed in was created by this type and is still alive: the
//!   executor's object table hands a host object out only while it holds it,
//!   and destroys children before parents ([`crate::venus::executor::objects`]).
//! * **Structures are ours.** Every structure a call reads or writes is built
//!   in the calling function, from `ash`'s `Default` (so `sType` is right and
//!   `pNext` null) and linked with `push_next`, and outlives the call; every
//!   slice it points at is a local `Vec` that does too.
//! * **Values are checked.** Every enum, flag word and count reaching a call
//!   was range-checked by the executor against Vulkan 1.3 core
//!   ([`crate::venus::executor::policy`]).
//! * **External synchronization** is the executor's per-context lock.
//! * **Imported pages outlive their import.** A host-visible
//!   `VkDeviceMemory` is our [`RingPages`], imported with
//!   `VK_EXT_external_memory_host`; [`HostMemory`] holds an `Arc` of them
//!   and [`HostVulkan::free_memory`] drops it only after `vkFreeMemory` has
//!   returned (and after the device went idle), so the driver never holds a
//!   pointer into pages that have been freed.
//!
//! # Stage 5b.2: the generated calls
//!
//! The ~140 commands of pipelines, descriptors, render passes, command
//! buffers and submission go through one method, [`HostVulkan::call`], into
//! [`calls`] — generated by `scripts/venus-exec-gen.py` from the same model
//! as the protocol. Each rebuilds its structures as their `ash` twins in an
//! [`arena::Arena`] (so "structures are ours" holds for every pointer the
//! driver is handed: each points into an arena copy that outlives the call)
//! and calls the core entry point through `ash`'s function table. The
//! contract that makes that call sound is the executor's translation
//! (`executor::generated`): every handle a live host object of the right
//! type and device, every enum and flag word core 1.3, every array its
//! count's length, the command core in the device's version.

pub mod arena;
pub mod calls;
pub mod convert;

use std::ffi::{c_char, c_void, CString};
use std::sync::Arc;

use ash::vk::{self, Handle};

use crate::venus::executor::host::{
    CallError, Dedicated, DeviceRequest, HostDeviceInfo, HostGroup, HostVulkan, ImageBind,
    InstanceRequest, MemoryRequest, RawHandle,
};
use crate::venus::executor::objects::Kind;
use crate::venus::executor::policy::{has_extension, EXTERNAL_MEMORY_HOST};
use crate::venus::executor::GuestDevice;
use crate::venus::protocol::Command;
use crate::venus::protocol::{
    VkBufferCreateInfo, VkBufferCreateInfoNext, VkBufferViewCreateInfo, VkCommandPoolCreateInfo,
    VkExtensionProperties, VkFormat, VkFormatProperties2, VkFormatProperties2Next,
    VkImageAspectFlagBits, VkImageCreateInfo, VkImageCreateInfoNext, VkImageFormatProperties2,
    VkImageFormatProperties2Next, VkImageSubresource, VkImageViewCreateInfo,
    VkImageViewCreateInfoNext, VkMemoryRequirements2, VkMemoryRequirements2Next,
    VkPhysicalDeviceFeatures, VkPhysicalDeviceFeatures2, VkPhysicalDeviceImageFormatInfo2,
    VkPhysicalDeviceImageFormatInfo2Next, VkPhysicalDeviceMemoryProperties,
    VkPhysicalDeviceProperties, VkPhysicalDeviceProperties2, VkQueueFamilyProperties, VkResult,
    VkSubresourceLayout, VK_ERROR_FEATURE_NOT_PRESENT, VK_ERROR_FORMAT_NOT_SUPPORTED,
    VK_ERROR_INITIALIZATION_FAILED, VK_ERROR_OUT_OF_DEVICE_MEMORY, VK_SUCCESS,
};
use crate::venus::shmem::RingPages;

use convert::{DeviceLinks, FromAsh, ToAsh};

/// The newest version the renderer uses of any host device.
const API_1_3: u32 = vk::API_VERSION_1_3;

/// The largest `minImportedHostPointerAlignment` the probe will honour. The
/// RTX 2070 says 4 KiB; anything past 2 MiB is a driver the probe does not
/// trust with a real allocation.
const MAX_IMPORT_ALIGNMENT: u64 = 2 << 20;

/// The handle type every guest-visible allocation is imported as.
const HOST_ALLOCATION: vk::ExternalMemoryHandleTypeFlags =
    vk::ExternalMemoryHandleTypeFlags::HOST_ALLOCATION_EXT;

/// A host `VkDevice`, and what calling it needs beyond `ash`'s table: its
/// instance and physical device (for the external-memory queries a resource
/// is created by) and the one extension entry point the renderer calls.
pub struct HostDevice {
    device: ash::Device,
    instance: ash::Instance,
    physical: vk::PhysicalDevice,
    /// `vkGetMemoryHostPointerPropertiesEXT`, resolved from the device (the
    /// renderer enables `VK_EXT_external_memory_host` on every one).
    host_pointer_properties: Option<vk::PFN_vkGetMemoryHostPointerPropertiesEXT>,
}

/// A host `VkDeviceMemory`, and — for an import — the pages the driver
/// imported, kept alive until after it is freed.
pub struct HostMemory {
    memory: vk::DeviceMemory,
    pages: Option<Arc<RingPages>>,
}

/// The host's Vulkan loader. See the module docs.
pub struct AshVulkan {
    entry: ash::Entry,
}

impl std::fmt::Debug for AshVulkan {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("AshVulkan").finish_non_exhaustive()
    }
}

impl AshVulkan {
    /// Open the system Vulkan loader.
    ///
    /// # Errors
    /// A sentence saying why the loader could not be opened.
    pub fn load() -> Result<Self, String> {
        // SAFETY: `Entry::load` dlopens the platform's Vulkan loader and
        // resolves `vkGetInstanceProcAddr` from it. Its safety condition is
        // that the library really is a Vulkan loader, which the platform's
        // own library name (`vulkan-1.dll`, `libvulkan.so.1`) is; the
        // returned `Entry` keeps the library loaded for as long as it lives.
        let entry = unsafe { ash::Entry::load() }
            .map_err(|e| format!("the host has no usable Vulkan loader: {e}"))?;
        Ok(Self { entry })
    }

    /// The devices a guest would be shown, and why the rest are hidden:
    /// [`crate::venus::executor::probe`] on this host.
    ///
    /// # Errors
    /// Why no device would be shown.
    pub fn usable_devices(&self) -> Result<Vec<GuestDevice>, String> {
        crate::venus::executor::probe(self)
    }

    /// `min(device apiVersion, 1.3)`: the structures a query may chain.
    fn device_api(instance: &ash::Instance, device: vk::PhysicalDevice) -> u32 {
        // SAFETY: `device` was enumerated from `instance` (module docs,
        // "handles are ours"); the call only writes the returned struct.
        let props = unsafe { instance.get_physical_device_properties(device) };
        props.api_version.min(API_1_3)
    }

    /// `vkGetMemoryHostPointerPropertiesEXT` for a page of our own memory:
    /// the memory types a host allocation can be imported into, or `None`.
    ///
    /// A throwaway device with `VK_EXT_external_memory_host` enabled is made
    /// for the question, because the query is device-level; the memory
    /// asked about is a [`RingPages`] allocation, the same kind of pages the
    /// next stage imports for real.
    fn probe_host_import(
        &self,
        instance: &ash::Instance,
        device: vk::PhysicalDevice,
        families: &[VkQueueFamilyProperties],
    ) -> Option<(u32, u64)> {
        let mut host_props = vk::PhysicalDeviceExternalMemoryHostPropertiesEXT::default();
        let mut props2 = vk::PhysicalDeviceProperties2::default().push_next(&mut host_props);
        // SAFETY: `device` is ours; `props2` and the one structure chained on
        // it are locals that outlive the call.
        unsafe { instance.get_physical_device_properties2(device, &mut props2) };
        let align = host_props.min_imported_host_pointer_alignment;
        if !align.is_power_of_two() || align > MAX_IMPORT_ALIGNMENT {
            return None;
        }
        let family = families.iter().position(|f| f.queue_count > 0)?;
        let family = u32::try_from(family).ok()?;
        let priorities = [1.0f32];
        let queues = [vk::DeviceQueueCreateInfo::default()
            .queue_family_index(family)
            .queue_priorities(&priorities)];
        let names = [vk::EXT_EXTERNAL_MEMORY_HOST_NAME.as_ptr()];
        let info = vk::DeviceCreateInfo::default()
            .queue_create_infos(&queues)
            .enabled_extension_names(&names);
        // SAFETY: `device` is ours; `info`, the queue array and the name
        // array are locals that outlive the call, and the extension is one
        // the device reported (the caller checked).
        let probe = unsafe { instance.create_device(device, &info, None) }.ok()?;

        // Resolved by hand rather than through `ash::ext::external_memory_host`,
        // whose fallback for a missing entry point panics.
        // SAFETY: `probe` is a live device created with the extension
        // enabled, and the name is a NUL-terminated literal.
        let raw = unsafe {
            instance.get_device_proc_addr(
                probe.handle(),
                c"vkGetMemoryHostPointerPropertiesEXT".as_ptr(),
            )
        };
        let answer = raw.and_then(|raw| {
            // SAFETY: the loader returned this pointer for exactly this
            // entry point, whose C signature `PFN_vkGetMemoryHostPointerPropertiesEXT`
            // is; transmuting between two `extern "system"` function pointer
            // types of the same ABI is how every Vulkan loader binding works.
            let get: vk::PFN_vkGetMemoryHostPointerPropertiesEXT =
                unsafe { std::mem::transmute(raw) };
            let pages = RingPages::new(align.checked_mul(2)?).ok()?;
            let base = pages.as_ptr();
            let offset = base.align_offset(usize::try_from(align).ok()?);
            let pointer = base.wrapping_add(offset).cast::<c_void>().cast_const();
            let mut out = vk::MemoryHostPointerPropertiesEXT::default();
            // SAFETY: `get` is the device's own entry point; `pointer` is
            // aligned to `minImportedHostPointerAlignment` and lies inside
            // `pages`, a live allocation of twice that size which outlives
            // the call; `out` is a local of the right type. The query only
            // inspects the pointer, it imports nothing.
            let result = unsafe {
                get(
                    probe.handle(),
                    vk::ExternalMemoryHandleTypeFlags::HOST_ALLOCATION_EXT,
                    pointer,
                    &mut out,
                )
            };
            drop(pages);
            (result == vk::Result::SUCCESS).then_some((out.memory_type_bits, align))
        });
        // SAFETY: `probe` was created above, owns no child, and is not used
        // after this.
        unsafe { probe.destroy_device(None) };
        answer
    }
}

fn result_code(error: vk::Result) -> VkResult {
    error.as_raw()
}

macro_rules! raw_handle {
    ($($t:ty),*) => {
        $(impl RawHandle for $t {
            fn raw(&self) -> u64 {
                self.as_raw()
            }
        })*
    };
}
raw_handle!(
    vk::Queue,
    vk::CommandPool,
    vk::Image,
    vk::Buffer,
    vk::BufferView,
    vk::ImageView
);

impl RawHandle for HostMemory {
    fn raw(&self) -> u64 {
        self.memory.as_raw()
    }
}

/// Keep a guest-supplied name only if it can be a C string.
fn c_string(text: &Option<String>) -> Option<CString> {
    text.as_deref().and_then(|t| CString::new(t).ok())
}

impl HostVulkan for AshVulkan {
    type Instance = ash::Instance;
    type PhysicalDevice = vk::PhysicalDevice;
    type Device = HostDevice;
    type Queue = vk::Queue;
    type CommandPool = vk::CommandPool;
    type Image = vk::Image;
    type Memory = HostMemory;
    type Buffer = vk::Buffer;
    type BufferView = vk::BufferView;
    type ImageView = vk::ImageView;

    fn instance_version(&self) -> Result<u32, VkResult> {
        // SAFETY: a global command with no arguments but the out value.
        match unsafe { self.entry.try_enumerate_instance_version() } {
            Ok(Some(version)) => Ok(version),
            Ok(None) => Ok(vk::API_VERSION_1_0),
            Err(error) => Err(result_code(error)),
        }
    }

    fn create_instance(&self, request: &InstanceRequest) -> Result<ash::Instance, VkResult> {
        let app_name = c_string(&request.application_name);
        let engine_name = c_string(&request.engine_name);
        let mut app = vk::ApplicationInfo::default()
            .application_version(request.application_version)
            .engine_version(request.engine_version)
            .api_version(API_1_3);
        if let Some(name) = &app_name {
            app = app.application_name(name);
        }
        if let Some(name) = &engine_name {
            app = app.engine_name(name);
        }
        let info = vk::InstanceCreateInfo::default().application_info(&app);
        // SAFETY: `info` and the application info and names it points at
        // are locals that outlive the call; no layer, no extension.
        unsafe { self.entry.create_instance(&info, None) }.map_err(result_code)
    }

    fn destroy_instance(&self, instance: ash::Instance) {
        // SAFETY: the executor destroyed every child first; the value is
        // consumed, so it cannot be used again.
        unsafe { instance.destroy_instance(None) };
    }

    fn enumerate_physical_devices(
        &self,
        instance: &ash::Instance,
    ) -> Result<Vec<vk::PhysicalDevice>, VkResult> {
        // SAFETY: `instance` is ours.
        unsafe { instance.enumerate_physical_devices() }.map_err(result_code)
    }

    fn describe_physical_device(
        &self,
        instance: &ash::Instance,
        device: vk::PhysicalDevice,
    ) -> HostDeviceInfo {
        let api = Self::device_api(instance, device);
        let (properties, features) = if api >= vk::API_VERSION_1_1 {
            // SAFETY: `device` is ours, and `api` gates every chained
            // structure to what its version knows (see `convert`).
            unsafe {
                (
                    convert::query_properties2(instance, device, api),
                    convert::query_features2(instance, device, api),
                )
            }
        } else {
            // SAFETY: `device` is ours; the calls only write their results.
            let (props, feats) = unsafe {
                (
                    instance.get_physical_device_properties(device),
                    instance.get_physical_device_features(device),
                )
            };
            (
                VkPhysicalDeviceProperties2 {
                    p_next: Vec::new(),
                    properties: VkPhysicalDeviceProperties::from_ash(&props),
                },
                VkPhysicalDeviceFeatures2 {
                    p_next: Vec::new(),
                    features: VkPhysicalDeviceFeatures::from_ash(&feats),
                },
            )
        };
        // SAFETY: `device` is ours; each call only writes its results.
        let (families, memory, extensions) = unsafe {
            (
                instance.get_physical_device_queue_family_properties(device),
                instance.get_physical_device_memory_properties(device),
                instance
                    .enumerate_device_extension_properties(device)
                    .unwrap_or_default(),
            )
        };
        let queue_families: Vec<VkQueueFamilyProperties> = families
            .iter()
            .map(VkQueueFamilyProperties::from_ash)
            .collect();
        let extensions: Vec<VkExtensionProperties> = extensions
            .iter()
            .map(VkExtensionProperties::from_ash)
            .collect();
        let host_import = (api >= vk::API_VERSION_1_1
            && has_extension(&extensions, EXTERNAL_MEMORY_HOST))
        .then(|| self.probe_host_import(instance, device, &queue_families))
        .flatten();
        HostDeviceInfo {
            properties,
            features,
            queue_families,
            memory: VkPhysicalDeviceMemoryProperties::from_ash(&memory),
            extensions,
            host_import_types: host_import.map(|(bits, _)| bits),
            host_import_alignment: host_import.map_or(0, |(_, align)| align),
        }
    }

    fn physical_device_groups(
        &self,
        instance: &ash::Instance,
    ) -> Result<Vec<HostGroup<vk::PhysicalDevice>>, VkResult> {
        // SAFETY: `instance` is ours; the second call writes exactly the
        // `len` structures the first reported, into a local vector of them.
        let groups = unsafe {
            let len = instance
                .enumerate_physical_device_groups_len()
                .map_err(result_code)?;
            let mut groups = vec![vk::PhysicalDeviceGroupProperties::default(); len];
            instance
                .enumerate_physical_device_groups(&mut groups)
                .map_err(result_code)?;
            groups
        };
        Ok(groups
            .iter()
            .map(|g| {
                let n = usize::try_from(g.physical_device_count)
                    .unwrap_or(0)
                    .min(g.physical_devices.len());
                HostGroup {
                    members: g.physical_devices.iter().take(n).copied().collect(),
                    subset_allocation: g.subset_allocation != 0,
                }
            })
            .collect())
    }

    fn format_properties(
        &self,
        instance: &ash::Instance,
        device: vk::PhysicalDevice,
        format: VkFormat,
        out: &mut VkFormatProperties2,
    ) {
        let api = Self::device_api(instance, device);
        let wants3 = api >= API_1_3
            && out
                .p_next
                .iter()
                .any(|l| matches!(l, VkFormatProperties2Next::VkFormatProperties3(_)));
        let mut props3 = vk::FormatProperties3::default();
        let mut head = vk::FormatProperties2::default();
        if wants3 {
            head = head.push_next(&mut props3);
        }
        // SAFETY: `device` is ours, `format` a checked 1.3 core format, and
        // `head` and its chain are locals that outlive the call.
        unsafe {
            instance.get_physical_device_format_properties2(
                device,
                vk::Format::from_raw(format),
                &mut head,
            );
        }
        out.format_properties = FromAsh::from_ash(&head.format_properties);
        // Only the links the executor admits reach here (`policy::admits_link`);
        // any other stays as the guest sized it.
        for link in &mut out.p_next {
            if let VkFormatProperties2Next::VkFormatProperties3(p) = link {
                if wants3 {
                    *p = FromAsh::from_ash(&props3);
                }
            }
        }
    }

    fn image_format_properties(
        &self,
        instance: &ash::Instance,
        device: vk::PhysicalDevice,
        info: &VkPhysicalDeviceImageFormatInfo2,
        out: &mut VkImageFormatProperties2,
    ) -> VkResult {
        let mut external = None;
        let mut list: Option<Vec<vk::Format>> = None;
        let mut stencil = None;
        for link in &info.p_next {
            match link {
                VkPhysicalDeviceImageFormatInfo2Next::VkPhysicalDeviceExternalImageFormatInfo(
                    e,
                ) => {
                    external = Some(e.to_ash());
                }
                VkPhysicalDeviceImageFormatInfo2Next::VkImageFormatListCreateInfo(l) => {
                    list = Some(
                        l.p_view_formats
                            .as_deref()
                            .unwrap_or_default()
                            .iter()
                            .map(|f| vk::Format::from_raw(*f))
                            .collect(),
                    );
                }
                VkPhysicalDeviceImageFormatInfo2Next::VkImageStencilUsageCreateInfo(s) => {
                    stencil = Some(s.to_ash());
                }
                // The executor refuses every other link before a host is
                // asked; a query that got here with one is not answered.
                _ => return VK_ERROR_FORMAT_NOT_SUPPORTED,
            }
        }
        let mut list_info = list
            .as_deref()
            .map(|formats| vk::ImageFormatListCreateInfo::default().view_formats(formats));
        let mut query: vk::PhysicalDeviceImageFormatInfo2<'_> = info.to_ash();
        if let Some(e) = external.as_mut() {
            query = query.push_next(e);
        }
        if let Some(l) = list_info.as_mut() {
            query = query.push_next(l);
        }
        if let Some(s) = stencil.as_mut() {
            query = query.push_next(s);
        }

        let mut external_out = vk::ExternalImageFormatProperties::default();
        let mut ycbcr_out = vk::SamplerYcbcrConversionImageFormatProperties::default();
        let wants_external = out.p_next.iter().any(|l| {
            matches!(
                l,
                VkImageFormatProperties2Next::VkExternalImageFormatProperties(_)
            )
        });
        let wants_ycbcr = out.p_next.iter().any(|l| {
            matches!(
                l,
                VkImageFormatProperties2Next::VkSamplerYcbcrConversionImageFormatProperties(_)
            )
        });
        let mut head = vk::ImageFormatProperties2::default();
        if wants_external {
            head = head.push_next(&mut external_out);
        }
        if wants_ycbcr {
            head = head.push_next(&mut ycbcr_out);
        }
        // SAFETY: `device` is ours; every field of `query` was checked
        // against 1.3 core; `query`, `head`, both chains and the view-format
        // slice are locals that outlive the call.
        let result = unsafe {
            instance.get_physical_device_image_format_properties2(device, &query, &mut head)
        };
        out.image_format_properties = FromAsh::from_ash(&head.image_format_properties);
        for link in &mut out.p_next {
            match link {
                VkImageFormatProperties2Next::VkExternalImageFormatProperties(p) => {
                    *p = FromAsh::from_ash(&external_out);
                }
                VkImageFormatProperties2Next::VkSamplerYcbcrConversionImageFormatProperties(p) => {
                    *p = FromAsh::from_ash(&ycbcr_out);
                }
                // Not admitted by the executor, so never here.
                _ => {}
            }
        }
        match result {
            Ok(()) => VK_SUCCESS,
            Err(error) => result_code(error),
        }
    }

    fn create_device(
        &self,
        instance: &ash::Instance,
        device: vk::PhysicalDevice,
        request: &DeviceRequest<vk::PhysicalDevice>,
    ) -> Result<HostDevice, VkResult> {
        let queues: Vec<vk::DeviceQueueCreateInfo<'_>> = request
            .queues
            .iter()
            .map(|q| {
                vk::DeviceQueueCreateInfo::default()
                    .flags(vk::DeviceQueueCreateFlags::from_raw(q.flags))
                    .queue_family_index(q.family)
                    .queue_priorities(&q.priorities)
            })
            .collect();
        let names: Vec<CString> = request
            .extensions
            .iter()
            .filter_map(|e| CString::new(e.as_str()).ok())
            .collect();
        let name_ptrs: Vec<*const c_char> = names.iter().map(|n| n.as_ptr()).collect();
        let features = request.features.as_ref().map(ToAsh::to_ash);
        let mut group = request
            .group
            .as_deref()
            .map(|members| vk::DeviceGroupDeviceCreateInfo::default().physical_devices(members));
        // The executor admits only links with a twin; one without is refused
        // rather than dropped.
        let Ok(mut links) = DeviceLinks::new(&request.chain) else {
            return Err(VK_ERROR_FEATURE_NOT_PRESENT);
        };
        let mut info = vk::DeviceCreateInfo::default()
            .queue_create_infos(&queues)
            .enabled_extension_names(&name_ptrs);
        if let Some(f) = features.as_ref() {
            info = info.enabled_features(f);
        }
        if let Some(g) = group.as_mut() {
            info = info.push_next(g);
        }
        info = links.push(info);
        // SAFETY: `device` is ours; the create info was rebuilt from checked
        // protocol values (families and counts within the host's, priorities
        // in [0, 1], extensions advertised or the renderer's own, features
        // no more than reported); every array and chained structure it
        // points at is a local that outlives the call.
        let created =
            unsafe { instance.create_device(device, &info, None) }.map_err(result_code)?;
        // Resolved by hand rather than through `ash::ext::external_memory_host`,
        // whose fallback for a missing entry point panics.
        // SAFETY: `created` is a live device made with the extension enabled
        // (the executor always asks for it), and the name is a NUL-terminated
        // literal.
        let raw = unsafe {
            instance.get_device_proc_addr(
                created.handle(),
                c"vkGetMemoryHostPointerPropertiesEXT".as_ptr(),
            )
        };
        let host_pointer_properties = raw.map(|raw| {
            // SAFETY: the loader returned this pointer for exactly this entry
            // point, whose C signature `PFN_vkGetMemoryHostPointerPropertiesEXT`
            // is; both are `extern "system"` function pointers of one ABI.
            unsafe {
                std::mem::transmute::<
                    unsafe extern "system" fn(),
                    vk::PFN_vkGetMemoryHostPointerPropertiesEXT,
                >(raw)
            }
        });
        Ok(HostDevice {
            device: created,
            instance: instance.clone(),
            physical: device,
            host_pointer_properties,
        })
    }

    fn destroy_device(&self, device: HostDevice) {
        // SAFETY: the executor destroyed every child first; the value is
        // consumed. Waiting for idle first is what vkr does on its worker
        // thread; this stage submits nothing, so it returns at once.
        unsafe {
            let _ = device.device.device_wait_idle();
            device.device.destroy_device(None);
        }
    }

    fn device_queue(&self, device: &HostDevice, flags: u32, family: u32, index: u32) -> vk::Queue {
        let device = &device.device;
        if flags == 0 {
            // SAFETY: `(family, index)` is a queue the device was created
            // with (the executor checked); plain `vkGetDeviceQueue` for
            // flags 0, as vkr does for drivers that predate the spec fix.
            unsafe { device.get_device_queue(family, index) }
        } else {
            let info = vk::DeviceQueueInfo2::default()
                .flags(vk::DeviceQueueCreateFlags::from_raw(flags))
                .queue_family_index(family)
                .queue_index(index);
            // SAFETY: as above, with the flags it was created with.
            unsafe { device.get_device_queue2(&info) }
        }
    }

    fn create_command_pool(
        &self,
        device: &HostDevice,
        info: &VkCommandPoolCreateInfo,
    ) -> Result<vk::CommandPool, VkResult> {
        let info = info.to_ash();
        // SAFETY: `device` is ours; flags and family were checked.
        unsafe { device.device.create_command_pool(&info, None) }.map_err(result_code)
    }

    fn destroy_command_pool(&self, device: &HostDevice, pool: vk::CommandPool) {
        // SAFETY: `pool` was created on `device` and is destroyed once.
        unsafe { device.device.destroy_command_pool(pool, None) };
    }

    fn image_accepts_host_memory(&self, device: &HostDevice, info: &VkImageCreateInfo) -> bool {
        let mut external =
            vk::PhysicalDeviceExternalImageFormatInfo::default().handle_type(HOST_ALLOCATION);
        let query = vk::PhysicalDeviceImageFormatInfo2::default()
            .format(vk::Format::from_raw(info.format))
            .ty(vk::ImageType::from_raw(info.image_type))
            .tiling(vk::ImageTiling::from_raw(info.tiling))
            .usage(vk::ImageUsageFlags::from_raw(info.usage))
            .flags(vk::ImageCreateFlags::from_raw(info.flags))
            .push_next(&mut external);
        let mut external_out = vk::ExternalImageFormatProperties::default();
        let mut out = vk::ImageFormatProperties2::default().push_next(&mut external_out);
        // SAFETY: the physical device is the device's own; every field was
        // checked against 1.3 core by the executor; `query`, `out` and their
        // chains are locals that outlive the call.
        let result = unsafe {
            device
                .instance
                .get_physical_device_image_format_properties2(device.physical, &query, &mut out)
        };
        result.is_ok()
            && external_out
                .external_memory_properties
                .external_memory_features
                .contains(vk::ExternalMemoryFeatureFlags::IMPORTABLE)
    }

    fn create_image(
        &self,
        device: &HostDevice,
        info: &VkImageCreateInfo,
        host_memory: bool,
    ) -> Result<vk::Image, VkResult> {
        with_image_create_info(info, host_memory, |create| {
            // SAFETY: `device` is ours; every field was range-checked and the
            // image checked against the host's own format limits; the create
            // info, its chain and its slices are locals of the helper that
            // outlive the call.
            unsafe { device.device.create_image(create, None) }.map_err(result_code)
        })?
    }

    fn destroy_image(&self, device: &HostDevice, image: vk::Image) {
        // SAFETY: `image` was created on `device` and is destroyed once.
        unsafe { device.device.destroy_image(image, None) };
    }

    fn image_memory_requirements(
        &self,
        device: &HostDevice,
        image: vk::Image,
        plane: Option<VkImageAspectFlagBits>,
        out: &mut VkMemoryRequirements2,
    ) {
        let mut plane_info = plane.map(|aspect| {
            vk::ImagePlaneMemoryRequirementsInfo::default().plane_aspect(
                vk::ImageAspectFlags::from_raw(u32::try_from(aspect).unwrap_or(0)),
            )
        });
        let mut info = vk::ImageMemoryRequirementsInfo2::default().image(image);
        if let Some(p) = plane_info.as_mut() {
            info = info.push_next(p);
        }
        with_requirements(out, |head| {
            // SAFETY: `image` was created on `device`; the plane aspect was
            // checked; `info`, `head` and their chains are locals that
            // outlive the call.
            unsafe { device.device.get_image_memory_requirements2(&info, head) };
        });
    }

    fn device_image_memory_requirements(
        &self,
        device: &HostDevice,
        info: &VkImageCreateInfo,
        host_memory: bool,
        plane: Option<VkImageAspectFlagBits>,
        out: &mut VkMemoryRequirements2,
    ) {
        let aspect =
            vk::ImageAspectFlags::from_raw(plane.and_then(|p| u32::try_from(p).ok()).unwrap_or(0));
        let _ = with_image_create_info(info, host_memory, |create| {
            let query = vk::DeviceImageMemoryRequirements::default()
                .create_info(create)
                .plane_aspect(aspect);
            with_requirements(out, |head| {
                // SAFETY: the executor asks this only of a device of Vulkan
                // 1.3 (where the entry point is core); the create info was
                // checked as `vkCreateImage` checks it; every structure is a
                // local that outlives the call.
                unsafe {
                    device
                        .device
                        .get_device_image_memory_requirements(&query, head)
                };
            });
        });
    }

    fn image_subresource_layout(
        &self,
        device: &HostDevice,
        image: vk::Image,
        subresource: &VkImageSubresource,
    ) -> VkSubresourceLayout {
        let sub = vk::ImageSubresource {
            aspect_mask: vk::ImageAspectFlags::from_raw(subresource.aspect_mask),
            mip_level: subresource.mip_level,
            array_layer: subresource.array_layer,
        };
        // SAFETY: `image` is a linear image of `device`, and the subresource
        // one aspect, level and layer it has (the executor checked).
        let layout = unsafe { device.device.get_image_subresource_layout(image, sub) };
        VkSubresourceLayout {
            offset: layout.offset,
            size: layout.size,
            row_pitch: layout.row_pitch,
            array_pitch: layout.array_pitch,
            depth_pitch: layout.depth_pitch,
        }
    }

    fn bind_image_memory(
        &self,
        device: &HostDevice,
        binds: &[ImageBind<'_, vk::Image, HostMemory>],
    ) -> VkResult {
        let mut planes: Vec<Option<vk::BindImagePlaneMemoryInfo<'_>>> = binds
            .iter()
            .map(|b| {
                b.plane.map(|aspect| {
                    vk::BindImagePlaneMemoryInfo::default().plane_aspect(
                        vk::ImageAspectFlags::from_raw(u32::try_from(aspect).unwrap_or(0)),
                    )
                })
            })
            .collect();
        let infos: Vec<vk::BindImageMemoryInfo<'_>> = binds
            .iter()
            .zip(planes.iter_mut())
            .map(|(b, plane)| {
                let info = vk::BindImageMemoryInfo::default()
                    .image(b.image)
                    .memory(b.memory.memory)
                    .memory_offset(b.offset);
                match plane.as_mut() {
                    Some(p) => info.push_next(p),
                    None => info,
                }
            })
            .collect();
        // SAFETY: every image and memory is of `device` and unbound; every
        // offset is aligned and every requirement fits its memory (the
        // executor checked); `infos` and the plane structures are locals
        // that outlive the call.
        match unsafe { device.device.bind_image_memory2(&infos) } {
            Ok(()) => VK_SUCCESS,
            Err(error) => result_code(error),
        }
    }

    fn create_image_view(
        &self,
        device: &HostDevice,
        image: vk::Image,
        info: &VkImageViewCreateInfo,
    ) -> Result<vk::ImageView, VkResult> {
        let mut usage = None;
        for link in &info.p_next {
            match link {
                VkImageViewCreateInfoNext::VkImageViewUsageCreateInfo(u) => {
                    usage = Some(
                        vk::ImageViewUsageCreateInfo::default()
                            .usage(vk::ImageUsageFlags::from_raw(u.usage)),
                    );
                }
                // The executor refuses every other link first.
                _ => return Err(VK_ERROR_INITIALIZATION_FAILED),
            }
        }
        let c = &info.components;
        let r = &info.subresource_range;
        let mut create = vk::ImageViewCreateInfo::default()
            .flags(vk::ImageViewCreateFlags::from_raw(info.flags))
            .image(image)
            .view_type(vk::ImageViewType::from_raw(info.view_type))
            .format(vk::Format::from_raw(info.format))
            .components(vk::ComponentMapping {
                r: vk::ComponentSwizzle::from_raw(c.r),
                g: vk::ComponentSwizzle::from_raw(c.g),
                b: vk::ComponentSwizzle::from_raw(c.b),
                a: vk::ComponentSwizzle::from_raw(c.a),
            })
            .subresource_range(vk::ImageSubresourceRange {
                aspect_mask: vk::ImageAspectFlags::from_raw(r.aspect_mask),
                base_mip_level: r.base_mip_level,
                level_count: r.level_count,
                base_array_layer: r.base_array_layer,
                layer_count: r.layer_count,
            });
        if let Some(u) = usage.as_mut() {
            create = create.push_next(u);
        }
        // SAFETY: `image` is a bound image of `device`; the view type, format,
        // swizzles and range were checked against the image and 1.3 core;
        // `create` and its chain are locals that outlive the call.
        unsafe { device.device.create_image_view(&create, None) }.map_err(result_code)
    }

    fn destroy_image_view(&self, device: &HostDevice, view: vk::ImageView) {
        // SAFETY: `view` was created on `device` and is destroyed once.
        unsafe { device.device.destroy_image_view(view, None) };
    }

    fn host_pointer_types(&self, device: &HostDevice, pages: &RingPages) -> Result<u32, VkResult> {
        let Some(get) = device.host_pointer_properties else {
            return Err(VK_ERROR_OUT_OF_DEVICE_MEMORY);
        };
        let mut out = vk::MemoryHostPointerPropertiesEXT::default();
        // SAFETY: `get` is the device's own entry point; `pages` is a live
        // allocation aligned to the driver's `minImportedHostPointerAlignment`
        // (`RingPages::for_memory`) that outlives the call; `out` is a local
        // of the right type. The query imports nothing.
        let result = unsafe {
            get(
                device.device.handle(),
                HOST_ALLOCATION,
                pages.as_ptr().cast::<c_void>().cast_const(),
                &mut out,
            )
        };
        if result == vk::Result::SUCCESS {
            Ok(out.memory_type_bits)
        } else {
            Err(result_code(result))
        }
    }

    fn allocate_memory(
        &self,
        device: &HostDevice,
        request: &MemoryRequest<vk::Buffer, vk::Image>,
    ) -> Result<HostMemory, VkResult> {
        let mut import = request.import.as_ref().map(|pages| {
            vk::ImportMemoryHostPointerInfoEXT::default()
                .handle_type(HOST_ALLOCATION)
                .host_pointer(pages.as_ptr().cast::<c_void>())
        });
        let mut flags = request.flags.map(|(flags, mask)| {
            vk::MemoryAllocateFlagsInfo::default()
                .flags(vk::MemoryAllocateFlags::from_raw(flags))
                .device_mask(mask)
        });
        let mut dedicated = request.dedicated.map(|d| match d {
            Dedicated::Buffer(buffer) => vk::MemoryDedicatedAllocateInfo::default().buffer(buffer),
            Dedicated::Image(image) => vk::MemoryDedicatedAllocateInfo::default().image(image),
        });
        let mut info = vk::MemoryAllocateInfo::default()
            .allocation_size(request.size)
            .memory_type_index(request.type_index);
        if let Some(i) = import.as_mut() {
            info = info.push_next(i);
        }
        if let Some(f) = flags.as_mut() {
            info = info.push_next(f);
        }
        if let Some(d) = dedicated.as_mut() {
            info = info.push_next(d);
        }
        // SAFETY: `device` is ours; the type index, size, flags and dedicated
        // resource were checked by the executor. For an import, the pointer
        // is the base of `pages`, aligned to `minImportedHostPointerAlignment`
        // and `request.size` (= `pages.mapped_len()`, a multiple of it) bytes
        // long, and the executor asked `vkGetMemoryHostPointerPropertiesEXT`
        // that the type accepts it. Those pages outlive the import: the
        // `HostMemory` built below holds an `Arc` of them, which
        // `free_memory` releases only after `vkFreeMemory` has returned.
        // Every chained structure is a local that outlives the call.
        let memory = unsafe { device.device.allocate_memory(&info, None) }.map_err(result_code)?;
        Ok(HostMemory {
            memory,
            pages: request.import.clone(),
        })
    }

    fn free_memory(&self, device: &HostDevice, memory: HostMemory) {
        if memory.pages.is_some() {
            // The pages go back to the allocator after this, so no GPU work
            // may still be writing them. Nothing is submitted in this stage
            // but a test's own work; the wait is what keeps that true once
            // the guest submits too (stage 5b.3).
            // SAFETY: `device` is ours, and the executor's context lock is
            // external synchronization for every queue of it.
            let _ = unsafe { device.device.device_wait_idle() };
        }
        // SAFETY: `memory` was allocated on `device` and is freed once (the
        // value is consumed).
        unsafe { device.device.free_memory(memory.memory, None) };
        // Only now may the imported pages go (if this was their last holder).
        drop(memory.pages);
    }

    fn memory_commitment(&self, device: &HostDevice, memory: &HostMemory) -> u64 {
        // SAFETY: `memory` is of `device` and of a lazily allocated type (the
        // executor asks nothing else).
        unsafe { device.device.get_device_memory_commitment(memory.memory) }
    }

    fn buffer_accepts_host_memory(&self, device: &HostDevice, flags: u32, usage: u32) -> bool {
        let info = vk::PhysicalDeviceExternalBufferInfo::default()
            .flags(vk::BufferCreateFlags::from_raw(flags))
            .usage(vk::BufferUsageFlags::from_raw(usage))
            .handle_type(HOST_ALLOCATION);
        let mut out = vk::ExternalBufferProperties::default();
        // SAFETY: the physical device is the device's own; flags and usage
        // were checked against 1.3 core; `info` and `out` are locals.
        unsafe {
            device
                .instance
                .get_physical_device_external_buffer_properties(device.physical, &info, &mut out)
        };
        out.external_memory_properties
            .external_memory_features
            .contains(vk::ExternalMemoryFeatureFlags::IMPORTABLE)
    }

    fn create_buffer(
        &self,
        device: &HostDevice,
        info: &VkBufferCreateInfo,
        host_memory: bool,
    ) -> Result<vk::Buffer, VkResult> {
        with_buffer_create_info(info, host_memory, |create| {
            // SAFETY: `device` is ours; every field was checked; the create
            // info and its chain are locals of the helper that outlive the
            // call.
            unsafe { device.device.create_buffer(create, None) }.map_err(result_code)
        })?
    }

    fn destroy_buffer(&self, device: &HostDevice, buffer: vk::Buffer) {
        // SAFETY: `buffer` was created on `device` and is destroyed once.
        unsafe { device.device.destroy_buffer(buffer, None) };
    }

    fn buffer_memory_requirements(
        &self,
        device: &HostDevice,
        buffer: vk::Buffer,
        out: &mut VkMemoryRequirements2,
    ) {
        let info = vk::BufferMemoryRequirementsInfo2::default().buffer(buffer);
        with_requirements(out, |head| {
            // SAFETY: `buffer` was created on `device`; `info` and `head` are
            // locals that outlive the call.
            unsafe { device.device.get_buffer_memory_requirements2(&info, head) };
        });
    }

    fn device_buffer_memory_requirements(
        &self,
        device: &HostDevice,
        info: &VkBufferCreateInfo,
        host_memory: bool,
        out: &mut VkMemoryRequirements2,
    ) {
        let _ = with_buffer_create_info(info, host_memory, |create| {
            let query = vk::DeviceBufferMemoryRequirements::default().create_info(create);
            with_requirements(out, |head| {
                // SAFETY: the executor asks this only of a device of Vulkan
                // 1.3 (where the entry point is core); the create info was
                // checked as `vkCreateBuffer` checks it; every structure is a
                // local that outlives the call.
                unsafe {
                    device
                        .device
                        .get_device_buffer_memory_requirements(&query, head)
                };
            });
        });
    }

    fn bind_buffer_memory(
        &self,
        device: &HostDevice,
        binds: &[(vk::Buffer, &HostMemory, u64)],
    ) -> VkResult {
        let infos: Vec<vk::BindBufferMemoryInfo<'_>> = binds
            .iter()
            .map(|(buffer, memory, offset)| {
                vk::BindBufferMemoryInfo::default()
                    .buffer(*buffer)
                    .memory(memory.memory)
                    .memory_offset(*offset)
            })
            .collect();
        // SAFETY: every buffer and memory is of `device`, every buffer
        // unbound, every offset aligned and every requirement inside its
        // memory (the executor checked); `infos` is a local that outlives the
        // call.
        match unsafe { device.device.bind_buffer_memory2(&infos) } {
            Ok(()) => VK_SUCCESS,
            Err(error) => result_code(error),
        }
    }

    fn buffer_device_address(&self, device: &HostDevice, buffer: vk::Buffer) -> u64 {
        let info = vk::BufferDeviceAddressInfo::default().buffer(buffer);
        // SAFETY: `buffer` is a bound buffer of `device` created with
        // `SHADER_DEVICE_ADDRESS` usage, on a device that enabled
        // `bufferDeviceAddress` (the executor checked all three).
        unsafe { device.device.get_buffer_device_address(&info) }
    }

    fn create_buffer_view(
        &self,
        device: &HostDevice,
        buffer: vk::Buffer,
        info: &VkBufferViewCreateInfo,
    ) -> Result<vk::BufferView, VkResult> {
        let create = vk::BufferViewCreateInfo::default()
            .buffer(buffer)
            .format(vk::Format::from_raw(info.format))
            .offset(info.offset)
            .range(info.range);
        // SAFETY: `buffer` is a bound texel buffer of `device`; the format,
        // offset and range were checked against it; `create` is a local.
        unsafe { device.device.create_buffer_view(&create, None) }.map_err(result_code)
    }

    fn destroy_buffer_view(&self, device: &HostDevice, view: vk::BufferView) {
        // SAFETY: `view` was created on `device` and is destroyed once.
        unsafe { device.device.destroy_buffer_view(view, None) };
    }

    fn call(&self, device: &HostDevice, command: &mut Command<'_>) -> Result<(), CallError> {
        // SAFETY: `call`'s contract, which the executor keeps: the command
        // was translated by `executor::generated::translate` against this
        // context's table (every handle a live object of `device` of the
        // field's type, or null where Vulkan allows null there; every enum
        // and flag word a core 1.3 value; every count its array's length),
        // the executor refused it unless it is core in the device's version
        // (`generated::min_api`), and the executor's context lock is held,
        // which is the external synchronisation every object named needs.
        unsafe { calls::call(&device.device, command) }
    }

    fn destroy_object(&self, device: &HostDevice, kind: Kind, raw: u64) {
        let d = &device.device;
        // SAFETY: `raw` is a live handle of `kind` created on `device`
        // through `call`, which the executor has just taken out of its table,
        // so it is destroyed exactly once; the executor waited for any work
        // that may still use it first (`executor::submit`). The 1.1 and 1.3
        // entry points are only reached for objects a create of that version
        // made, which the executor allows only on a device of that version.
        unsafe {
            match kind {
                Kind::ShaderModule => {
                    d.destroy_shader_module(vk::ShaderModule::from_raw(raw), None)
                }
                Kind::PipelineLayout => {
                    d.destroy_pipeline_layout(vk::PipelineLayout::from_raw(raw), None);
                }
                Kind::DescriptorSetLayout => {
                    d.destroy_descriptor_set_layout(vk::DescriptorSetLayout::from_raw(raw), None);
                }
                Kind::DescriptorPool => {
                    d.destroy_descriptor_pool(vk::DescriptorPool::from_raw(raw), None);
                }
                Kind::DescriptorUpdateTemplate => d.destroy_descriptor_update_template(
                    vk::DescriptorUpdateTemplate::from_raw(raw),
                    None,
                ),
                Kind::Sampler => d.destroy_sampler(vk::Sampler::from_raw(raw), None),
                Kind::SamplerYcbcrConversion => d.destroy_sampler_ycbcr_conversion(
                    vk::SamplerYcbcrConversion::from_raw(raw),
                    None,
                ),
                Kind::PipelineCache => {
                    d.destroy_pipeline_cache(vk::PipelineCache::from_raw(raw), None);
                }
                Kind::Pipeline => d.destroy_pipeline(vk::Pipeline::from_raw(raw), None),
                Kind::RenderPass => d.destroy_render_pass(vk::RenderPass::from_raw(raw), None),
                Kind::Framebuffer => d.destroy_framebuffer(vk::Framebuffer::from_raw(raw), None),
                Kind::QueryPool => d.destroy_query_pool(vk::QueryPool::from_raw(raw), None),
                Kind::Event => d.destroy_event(vk::Event::from_raw(raw), None),
                Kind::Fence => d.destroy_fence(vk::Fence::from_raw(raw), None),
                Kind::PrivateDataSlot => {
                    d.destroy_private_data_slot(vk::PrivateDataSlot::from_raw(raw), None);
                }
                // Freed with their pools, or by the guest's own
                // vkFree*; never destroyed one by one here.
                _ => {}
            }
        }
    }

    fn device_wait_idle(&self, device: &HostDevice) -> VkResult {
        // SAFETY: `device` is ours; the executor's context lock is the
        // external synchronisation for every queue of it.
        match unsafe { device.device.device_wait_idle() } {
            Ok(()) => VK_SUCCESS,
            Err(error) => result_code(error),
        }
    }
}

/// Run `f` on `out`'s `ash` twin, chaining `VkMemoryDedicatedRequirements`
/// exactly when `out` carries it, and copy the answer back.
fn with_requirements(
    out: &mut VkMemoryRequirements2,
    f: impl FnOnce(&mut vk::MemoryRequirements2<'_>),
) {
    let wants_dedicated = !out.p_next.is_empty();
    let mut dedicated = vk::MemoryDedicatedRequirements::default();
    let mut head = vk::MemoryRequirements2::default();
    if wants_dedicated {
        head = head.push_next(&mut dedicated);
    }
    f(&mut head);
    out.memory_requirements = FromAsh::from_ash(&head.memory_requirements);
    for link in &mut out.p_next {
        let VkMemoryRequirements2Next::VkMemoryDedicatedRequirements(d) = link;
        *d = FromAsh::from_ash(&dedicated);
    }
}

/// Build the `ash` create info of a checked `VkImageCreateInfo` — with a
/// `VkExternalMemoryImageCreateInfo` for host allocations when
/// `host_memory` — and run `f` on it while every structure it points at is
/// alive.
///
/// # Errors
/// `VK_ERROR_INITIALIZATION_FAILED` for a link the executor does not admit
/// (it refuses those first; one reaching here is not built).
fn with_image_create_info<T>(
    info: &VkImageCreateInfo,
    host_memory: bool,
    f: impl FnOnce(&vk::ImageCreateInfo<'_>) -> T,
) -> Result<T, VkResult> {
    let families: Vec<u32> = info.p_queue_family_indices.clone().unwrap_or_default();
    let mut list: Option<Vec<vk::Format>> = None;
    let mut stencil = None;
    for link in &info.p_next {
        match link {
            // The guest's is always empty (the executor refuses any handle
            // type); ours replaces it.
            VkImageCreateInfoNext::VkExternalMemoryImageCreateInfo(_) => {}
            VkImageCreateInfoNext::VkImageFormatListCreateInfo(l) => {
                list = Some(
                    l.p_view_formats
                        .as_deref()
                        .unwrap_or_default()
                        .iter()
                        .map(|f| vk::Format::from_raw(*f))
                        .collect(),
                );
            }
            VkImageCreateInfoNext::VkImageStencilUsageCreateInfo(s) => {
                stencil = Some(s.to_ash());
            }
            _ => return Err(VK_ERROR_INITIALIZATION_FAILED),
        }
    }
    let mut external = host_memory
        .then(|| vk::ExternalMemoryImageCreateInfo::default().handle_types(HOST_ALLOCATION));
    let mut list_info = list
        .as_deref()
        .map(|formats| vk::ImageFormatListCreateInfo::default().view_formats(formats));
    let mut create = vk::ImageCreateInfo::default()
        .flags(vk::ImageCreateFlags::from_raw(info.flags))
        .image_type(vk::ImageType::from_raw(info.image_type))
        .format(vk::Format::from_raw(info.format))
        .extent(info.extent.to_ash())
        .mip_levels(info.mip_levels)
        .array_layers(info.array_layers)
        .samples(vk::SampleCountFlags::from_raw(
            u32::try_from(info.samples).unwrap_or(1),
        ))
        .tiling(vk::ImageTiling::from_raw(info.tiling))
        .usage(vk::ImageUsageFlags::from_raw(info.usage))
        .sharing_mode(vk::SharingMode::from_raw(info.sharing_mode))
        .initial_layout(vk::ImageLayout::from_raw(info.initial_layout));
    if info.sharing_mode == vk::SharingMode::CONCURRENT.as_raw() {
        create = create.queue_family_indices(&families);
    }
    if let Some(e) = external.as_mut() {
        create = create.push_next(e);
    }
    if let Some(l) = list_info.as_mut() {
        create = create.push_next(l);
    }
    if let Some(s) = stencil.as_mut() {
        create = create.push_next(s);
    }
    Ok(f(&create))
}

/// [`with_image_create_info`] for a buffer.
///
/// # Errors
/// As there.
fn with_buffer_create_info<T>(
    info: &VkBufferCreateInfo,
    host_memory: bool,
    f: impl FnOnce(&vk::BufferCreateInfo<'_>) -> T,
) -> Result<T, VkResult> {
    let families: Vec<u32> = info.p_queue_family_indices.clone().unwrap_or_default();
    for link in &info.p_next {
        match link {
            // Both are empty by the time they get here (a handle type and a
            // capture address are refused first), so neither is forwarded.
            VkBufferCreateInfoNext::VkExternalMemoryBufferCreateInfo(_)
            | VkBufferCreateInfoNext::VkBufferOpaqueCaptureAddressCreateInfo(_) => {}
            _ => return Err(VK_ERROR_INITIALIZATION_FAILED),
        }
    }
    let mut external = host_memory
        .then(|| vk::ExternalMemoryBufferCreateInfo::default().handle_types(HOST_ALLOCATION));
    let mut create = vk::BufferCreateInfo::default()
        .flags(vk::BufferCreateFlags::from_raw(info.flags))
        .size(info.size)
        .usage(vk::BufferUsageFlags::from_raw(info.usage))
        .sharing_mode(vk::SharingMode::from_raw(info.sharing_mode));
    if info.sharing_mode == vk::SharingMode::CONCURRENT.as_raw() {
        create = create.queue_family_indices(&families);
    }
    if let Some(e) = external.as_mut() {
        create = create.push_next(e);
    }
    Ok(f(&create))
}

impl AshVulkan {
    /// Test-only: have the host GPU fill `size` bytes of `buffer` at
    /// `offset` with `data` (`vkCmdFillBuffer`) on `queue` of `family`, and
    /// wait until the writes are visible to the host. A throwaway command
    /// pool on `family`, one
    /// command buffer, one fence, all destroyed before returning. Queue
    /// submission for the guest is stage 5b.3; this proves the memory path
    /// end to end before it exists.
    ///
    /// # Errors
    /// The first failing Vulkan call.
    #[cfg(test)]
    pub(crate) fn fill_buffer(
        &self,
        device: &HostDevice,
        (queue, family): (vk::Queue, u32),
        buffer: vk::Buffer,
        offset: u64,
        size: u64,
        data: u32,
    ) -> Result<(), vk::Result> {
        let d = &device.device;
        let pool_info = vk::CommandPoolCreateInfo::default().queue_family_index(family);
        // SAFETY: test-only; every handle is of `d`, every structure a local
        // that outlives its call, and everything created here is destroyed
        // here, after the fence says the GPU is done with it. `buffer` is
        // bound to memory of `d` and `queue` is a queue of `d` of `family`.
        unsafe {
            let pool = d.create_command_pool(&pool_info, None)?;
            let result = (|| {
                let alloc = vk::CommandBufferAllocateInfo::default()
                    .command_pool(pool)
                    .level(vk::CommandBufferLevel::PRIMARY)
                    .command_buffer_count(1);
                let cmd = *d
                    .allocate_command_buffers(&alloc)?
                    .first()
                    .ok_or(vk::Result::ERROR_UNKNOWN)?;
                d.begin_command_buffer(
                    cmd,
                    &vk::CommandBufferBeginInfo::default()
                        .flags(vk::CommandBufferUsageFlags::ONE_TIME_SUBMIT),
                )?;
                d.cmd_fill_buffer(cmd, buffer, offset, size, data);
                // The fence makes the writes available on the device; this is
                // what makes them visible to a host read.
                let barrier = vk::MemoryBarrier::default()
                    .src_access_mask(vk::AccessFlags::TRANSFER_WRITE)
                    .dst_access_mask(vk::AccessFlags::HOST_READ);
                d.cmd_pipeline_barrier(
                    cmd,
                    vk::PipelineStageFlags::TRANSFER,
                    vk::PipelineStageFlags::HOST,
                    vk::DependencyFlags::empty(),
                    &[barrier],
                    &[],
                    &[],
                );
                d.end_command_buffer(cmd)?;
                let fence = d.create_fence(&vk::FenceCreateInfo::default(), None)?;
                let cmds = [cmd];
                let submit = vk::SubmitInfo::default().command_buffers(&cmds);
                let waited = d
                    .queue_submit(queue, &[submit], fence)
                    .and_then(|()| d.wait_for_fences(&[fence], true, 10_000_000_000));
                d.destroy_fence(fence, None);
                waited
            })();
            d.destroy_command_pool(pool, None);
            result
        }
    }
}

#[cfg(test)]
mod pipeline_tests;
#[cfg(test)]
mod tests;
