[package]
name = "virtio-block"
description = "virtio-blk device with a RAW file backend"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
tracing.workspace = true
virtio-core.workspace = true
virtio-queue.workspace = true
vm-memory.workspace = true

[dev-dependencies]
virtio-core = { workspace = true, features = ["test-utils"] }

[lints]
workspace = true
